# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: yrpc.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='yrpc.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\nyrpc.proto\"\x19\n\tAddresses\x12\x0c\n\x04list\x18\x01 \x03(\t\"K\n\x0c\x41\x64\x64ressPrice\x12\x0f\n\x07\x61\x64\x64ress\x18\x01 \x01(\t\x12\r\n\x05price\x18\x02 \x01(\x01\x12\x0c\n\x04unit\x18\x03 \x01(\t\x12\r\n\x05\x62lock\x18\x04 \x01(\x03\x32;\n\rYearnExporter\x12*\n\tGetPrices\x12\n.Addresses\x1a\r.AddressPrice\"\x00\x30\x01\x62\x06proto3'
)




_ADDRESSES = _descriptor.Descriptor(
  name='Addresses',
  full_name='Addresses',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='list', full_name='Addresses.list', index=0,
      number=1, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=14,
  serialized_end=39,
)


_ADDRESSPRICE = _descriptor.Descriptor(
  name='AddressPrice',
  full_name='AddressPrice',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='address', full_name='AddressPrice.address', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='price', full_name='AddressPrice.price', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='unit', full_name='AddressPrice.unit', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='block', full_name='AddressPrice.block', index=3,
      number=4, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=41,
  serialized_end=116,
)

DESCRIPTOR.message_types_by_name['Addresses'] = _ADDRESSES
DESCRIPTOR.message_types_by_name['AddressPrice'] = _ADDRESSPRICE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Addresses = _reflection.GeneratedProtocolMessageType('Addresses', (_message.Message,), {
  'DESCRIPTOR' : _ADDRESSES,
  '__module__' : 'yrpc_pb2'
  # @@protoc_insertion_point(class_scope:Addresses)
  })
_sym_db.RegisterMessage(Addresses)

AddressPrice = _reflection.GeneratedProtocolMessageType('AddressPrice', (_message.Message,), {
  'DESCRIPTOR' : _ADDRESSPRICE,
  '__module__' : 'yrpc_pb2'
  # @@protoc_insertion_point(class_scope:AddressPrice)
  })
_sym_db.RegisterMessage(AddressPrice)



_YEARNEXPORTER = _descriptor.ServiceDescriptor(
  name='YearnExporter',
  full_name='YearnExporter',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=118,
  serialized_end=177,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetPrices',
    full_name='YearnExporter.GetPrices',
    index=0,
    containing_service=None,
    input_type=_ADDRESSES,
    output_type=_ADDRESSPRICE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_YEARNEXPORTER)

DESCRIPTOR.services_by_name['YearnExporter'] = _YEARNEXPORTER

# @@protoc_insertion_point(module_scope)
