# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: yrpc.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='yrpc.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\nyrpc.proto\"k\n\x0fGetPriceRequest\x12+\n\taddresses\x18\x01 \x03(\x0b\x32\x18.GetPriceRequest.Address\x1a+\n\x07\x41\x64\x64ress\x12\x0f\n\x07\x61\x64\x64ress\x18\x01 \x01(\t\x12\x0f\n\x07network\x18\x02 \x01(\t\"U\n\x0c\x41\x64\x64ressPrice\x12\x0f\n\x07\x61\x64\x64ress\x18\x01 \x01(\t\x12\r\n\x05price\x18\x02 \x01(\x01\x12\x10\n\x08\x63hain_id\x18\x03 \x01(\x05\x12\x13\n\x0b\x64\x65nominator\x18\x04 \x01(\t2A\n\rYearnExporter\x12\x30\n\tGetPrices\x12\x10.GetPriceRequest\x1a\r.AddressPrice\"\x00\x30\x01\x62\x06proto3'
)




_GETPRICEREQUEST_ADDRESS = _descriptor.Descriptor(
  name='Address',
  full_name='GetPriceRequest.Address',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='address', full_name='GetPriceRequest.Address.address', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='network', full_name='GetPriceRequest.Address.network', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=78,
  serialized_end=121,
)

_GETPRICEREQUEST = _descriptor.Descriptor(
  name='GetPriceRequest',
  full_name='GetPriceRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='addresses', full_name='GetPriceRequest.addresses', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[_GETPRICEREQUEST_ADDRESS, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=14,
  serialized_end=121,
)


_ADDRESSPRICE = _descriptor.Descriptor(
  name='AddressPrice',
  full_name='AddressPrice',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='address', full_name='AddressPrice.address', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='price', full_name='AddressPrice.price', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='chain_id', full_name='AddressPrice.chain_id', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='denominator', full_name='AddressPrice.denominator', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=123,
  serialized_end=208,
)

_GETPRICEREQUEST_ADDRESS.containing_type = _GETPRICEREQUEST
_GETPRICEREQUEST.fields_by_name['addresses'].message_type = _GETPRICEREQUEST_ADDRESS
DESCRIPTOR.message_types_by_name['GetPriceRequest'] = _GETPRICEREQUEST
DESCRIPTOR.message_types_by_name['AddressPrice'] = _ADDRESSPRICE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

GetPriceRequest = _reflection.GeneratedProtocolMessageType('GetPriceRequest', (_message.Message,), {

  'Address' : _reflection.GeneratedProtocolMessageType('Address', (_message.Message,), {
    'DESCRIPTOR' : _GETPRICEREQUEST_ADDRESS,
    '__module__' : 'yrpc_pb2'
    # @@protoc_insertion_point(class_scope:GetPriceRequest.Address)
    })
  ,
  'DESCRIPTOR' : _GETPRICEREQUEST,
  '__module__' : 'yrpc_pb2'
  # @@protoc_insertion_point(class_scope:GetPriceRequest)
  })
_sym_db.RegisterMessage(GetPriceRequest)
_sym_db.RegisterMessage(GetPriceRequest.Address)

AddressPrice = _reflection.GeneratedProtocolMessageType('AddressPrice', (_message.Message,), {
  'DESCRIPTOR' : _ADDRESSPRICE,
  '__module__' : 'yrpc_pb2'
  # @@protoc_insertion_point(class_scope:AddressPrice)
  })
_sym_db.RegisterMessage(AddressPrice)



_YEARNEXPORTER = _descriptor.ServiceDescriptor(
  name='YearnExporter',
  full_name='YearnExporter',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=210,
  serialized_end=275,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetPrices',
    full_name='YearnExporter.GetPrices',
    index=0,
    containing_service=None,
    input_type=_GETPRICEREQUEST,
    output_type=_ADDRESSPRICE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_YEARNEXPORTER)

DESCRIPTOR.services_by_name['YearnExporter'] = _YEARNEXPORTER

# @@protoc_insertion_point(module_scope)
