# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import yrpc.yrpc_pb2 as yrpc__pb2


class YearnExporterStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetPrices = channel.unary_stream(
                '/YearnExporter/GetPrices',
                request_serializer=yrpc__pb2.Addresses.SerializeToString,
                response_deserializer=yrpc__pb2.AddressPrice.FromString,
                )


class YearnExporterServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetPrices(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_YearnExporterServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetPrices': grpc.unary_stream_rpc_method_handler(
                    servicer.GetPrices,
                    request_deserializer=yrpc__pb2.Addresses.FromString,
                    response_serializer=yrpc__pb2.AddressPrice.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'YearnExporter', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class YearnExporter(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetPrices(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/YearnExporter/GetPrices',
            yrpc__pb2.Addresses.SerializeToString,
            yrpc__pb2.AddressPrice.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
