{
 "title": "Ape.Tax Vault Overview",
 "description": "Look up individual vault stats here",
 "tags": [
  "yVault",
  "Version 2",
  "Experimental"
 ],
 "time": { "from": "2021-11-07T04:23:11.723Z", "to": "2021-12-10T14:10:35.563Z" },
 "templating": {
  "list": [
   {
    "name": "networks",
    "label": "network",
    "query": {
     "query": "yearn_strategy{experimental=\"false\", param=\"totalLoss\"}"
    }
   },
   {
    "name": "vaults",
    "label": "vaults",
    "query": {
     "query": "yearn_strategy{network=\"$networks\", experimental=\"true\"}"
    }
   }
  ]
 },
 "panels": [
  { "title": "Strategies", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "$vaults Strategies",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(yearn_strategy{network=\"$networks\", vault=\"$vaults\", param=\"isActive\"})",
     "legendFormat": "{{strategy}}"
    }
   ]
  },
  {
   "title": "$vaults Strategies Active",
   "type": "stat",
   "gridPos": { "h": 9, "w": 10, "x": 2, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "yearn_strategy{network=\"$networks\", vault=\"$vaults\", param=\"isActive\"} > 0",
     "legendFormat": "{{strategy}}"
    }
   ]
  },
  {
   "title": "$vaults Strategies Inactive",
   "type": "stat",
   "gridPos": { "h": 9, "w": 10, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "yearn_strategy{network=\"$networks\", vault=\"$vaults\", param=\"isActive\"} < 0.1",
     "legendFormat": "{{strategy}}"
    }
   ]
  },
  {
   "title": "$vaults Strategies - Inactive",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 22, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(yearn_strategy{network=\"$networks\", vault=\"$vaults\", param=\"isActive\"} < 0.1)",
     "legendFormat": "{{strategy}}"
    }
   ]
  },
  { "title": "Assets", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "totalAssets",
   "type": "stat",
   "description": "Total amount of Deposit tokens in vault",
   "gridPos": { "h": 4, "w": 4, "x": 2, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "yearn_vault{network=\"$networks\", param=\"totalAssets\", vault=~\"$vaults\"}",
     "legendFormat": "{{param}}"
    }
   ]
  },
  {
   "title": "totalAssets ($)",
   "type": "stat",
   "description": "The total amount of Deposit tokens in the vault in dollars",
   "gridPos": { "h": 4, "w": 4, "x": 6, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "yearn_vault{network=\"$networks\", param=\"tvl\", vault=~\"$vaults\"}",
     "legendFormat": "{{param}}"
    }
   ]
  },
  {
   "title": "totalDebt",
   "type": "stat",
   "description": "The total amount of deposit token allocated to strategies.",
   "gridPos": { "h": 4, "w": 4, "x": 10, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(yearn_strategy{network=\"$networks\", param=\"totalDebt\", vault=~\"$vaults\"})",
     "legendFormat": "{{param}}"
    }
   ]
  },
  {
   "title": "totalGain",
   "type": "stat",
   "description": "Sum of the total amount of gain from all strategies in underlying token.",
   "gridPos": { "h": 4, "w": 4, "x": 14, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(yearn_strategy{network=\"$networks\", param=\"totalGain\", vault=~\"$vaults\"})",
     "legendFormat": "{{param}}"
    }
   ]
  },
  {
   "title": "% to Deposit Limit",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 18, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "yearn_vault{network=\"$networks\", param=\"totalAssets\", vault=\"$vaults\"} / on(vault,version) yearn_vault{network=\"$networks\", param=\"depositLimit\", vault=\"$vaults\"}",
     "legendFormat": "% to Limit"
    }
   ]
  },
  {
   "title": "Share Price",
   "type": "stat",
   "description": "Share price of Vault token",
   "gridPos": { "h": 4, "w": 4, "x": 2, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "yearn_vault{network=\"$networks\", param=\"pricePerShare\", vault=~\"$vaults\"}",
     "legendFormat": "{{param}}"
    }
   ]
  },
  {
   "title": "% Share Price Change over Time Range",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 6, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "(yearn_vault{network=\"$networks\", param=\"pricePerShare\", vault=~\"$vaults\"} / yearn_vault{network=\"$networks\", param=\"pricePerShare\", vault=~\"$vaults\"} offset $__range) - 1",
     "legendFormat": "{{vault}}"
    }
   ]
  },
  {
   "title": "% of Assets Deployed",
   "type": "stat",
   "description": "totalDebt / totalAssets",
   "gridPos": { "h": 4, "w": 4, "x": 10, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(yearn_strategy{network=\"$networks\", param=\"totalDebt\", vault=~\"$vaults\"}) / on(vault, version) sum(yearn_vault{network=\"$networks\", param=\"totalAssets\", vault=~\"$vaults\"})",
     "legendFormat": "% to Limit"
    }
   ]
  },
  {
   "title": "Amount of Free Funds",
   "type": "stat",
   "description": "totalAssets - totalDebt. If you are looking to make a withdrawal this is how much the vault has free for lower fee withdrawals that wont pull from the funds of strategies that are currently deployed. Denominated in deposit token.",
   "gridPos": { "h": 4, "w": 4, "x": 14, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(yearn_vault{network=\"$networks\", param=\"totalAssets\", vault=~\"$vaults\"}) - on(vault, version) sum(yearn_strategy{network=\"$networks\", param=\"totalDebt\", vault=~\"$vaults\"})"
    }
   ]
  },
  {
   "title": "totalLoss",
   "type": "stat",
   "description": "Sum of all losses actualized from all strategies in underlying token terms",
   "gridPos": { "h": 4, "w": 4, "x": 18, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "yearn_strategy{network=\"$networks\", param=\"totalLoss\", vault=~\"$vaults\"}",
     "legendFormat": "{{param}}"
    }
   ]
  },
  {
   "title": "Deposit Limits",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 },
   "collapsed": true,
   "panels": [
    {
     "title": "Deposit Limit",
     "type": "graph",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 20 },
     "yaxes": [
      { "format": "short", "label": "Amount of Underlying Token" }
     ],
     "targets": [
      {
       "expr": "yearn_vault{network=\"$networks\", param=\"totalAssets\", vault=~\"$vaults\"}",
       "legendFormat": "Total Assets"
      },
      {
       "expr": "yearn_vault{network=\"$networks\", param=\"depositLimit\", vault=~\"$vaults\"}",
       "legendFormat": "Deposit Limit"
      },
      {
       "expr": "yearn_vault{network=\"$networks\", param=\"totalAssets\", vault=\"$vaults\"} / on(vault,version) yearn_vault{network=\"$networks\", param=\"depositLimit\", vault=\"$vaults\"}",
       "legendFormat": "% to Deposit Limit"
      }
     ]
    }
   ]
  },
  {
   "title": "Assets Graphs",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 },
   "collapsed": true,
   "panels": [
    {
     "title": "Strategy Allocations Overview",
     "type": "graph",
     "description": "Breakdown of assets in vault",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 21 },
     "yaxes": [
      { "format": "short", "label": "totalDebt - Strategies" }
     ],
     "targets": [
      {
       "expr": "yearn_vault{network=\"$networks\", param=\"totalAssets\", vault=~\"$vaults\"}",
       "legendFormat": "{{param}}"
      },
      {
       "expr": "sum(yearn_strategy{network=\"$networks\", param=\"totalDebt\", vault=~\"$vaults\"})",
       "legendFormat": "TotalDebt"
      }
     ]
    },
    {
     "title": "totalDebt",
     "type": "graph",
     "description": "Total amount of Deposit tokens in strategy",
     "gridPos": { "h": 9, "w": 16, "x": 0, "y": 30 },
     "yaxes": [
      {
       "format": "short",
       "label": "TotalDebt (Assets) in Strategies"
      }
     ],
     "targets": [
      {
       "expr": "yearn_strategy{network=\"$networks\", param=\"totalDebt\", vault=~\"$vaults\"}",
       "legendFormat": "{{strategy}}"
      }
     ]
    },
    {
     "title": "Strategy Allocations Overview",
     "type": "piechart",
     "description": "Breakdown of assets in vault",
     "gridPos": { "h": 9, "w": 8, "x": 16, "y": 30 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sort_desc(yearn_strategy{network=\"$networks\", param=\"totalDebt\", vault=~\"$vaults\"} > 0)",
       "legendFormat": "{{strategy}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Assets Delta",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 },
   "collapsed": true,
   "panels": [
    {
     "title": "TVL- 1D change",
     "type": "stat",
     "gridPos": { "h": 3, "w": 4, "x": 0, "y": 22 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "yearn_vault{network=\"$networks\", param=\"tvl\", vault=~\"$vaults\"} - yearn_vault{network=\"$networks\", param=\"tvl\", vault=~\"$vaults\"} offset 1d",
       "legendFormat": "{{vault}}"
      }
     ]
    },
    {
     "title": "TVL - 1D % change",
     "type": "stat",
     "gridPos": { "h": 3, "w": 4, "x": 4, "y": 22 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "(yearn_vault{network=\"$networks\", param=\"tvl\", vault=~\"$vaults\"} / yearn_vault{network=\"$networks\", param=\"tvl\", vault=~\"$vaults\"} offset 1d ) - 1",
       "legendFormat": "{{vault}}"
      }
     ]
    },
    {
     "title": "totalDebt - 1D change",
     "type": "stat",
     "gridPos": { "h": 3, "w": 4, "x": 8, "y": 22 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(yearn_strategy{network=\"$networks\", param=\"totalDebt\", vault=~\"$vaults\"}) - sum(yearn_strategy{network=\"$networks\", param=\"totalDebt\", vault=~\"$vaults\"} offset 1d)",
       "legendFormat": "{{strategy}}"
      }
     ]
    },
    {
     "title": "totalDebt - 1D % change",
     "type": "stat",
     "gridPos": { "h": 3, "w": 4, "x": 12, "y": 22 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "(sum(yearn_strategy{network=\"$networks\", param=\"totalDebt\", vault=~\"$vaults\"}) / sum(yearn_strategy{network=\"$networks\", param=\"totalDebt\", vault=~\"$vaults\"} offset 1d)) - 1",
       "legendFormat": "{{vault}}"
      }
     ]
    },
    {
     "title": "totalLoss - 1D change",
     "type": "stat",
     "gridPos": { "h": 3, "w": 4, "x": 16, "y": 22 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(yearn_strategy{network=\"$networks\", param=\"totalLoss\", vault=~\"$vaults\"}) - sum(yearn_strategy{network=\"$networks\", param=\"totalLoss\", vault=~\"$vaults\"} offset 1d)",
       "legendFormat": "{{strategy}}"
      }
     ]
    },
    {
     "title": "totalLoss - 1D % change",
     "type": "stat",
     "gridPos": { "h": 3, "w": 4, "x": 20, "y": 22 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "(sum(yearn_strategy{network=\"$networks\", param=\"totalLoss\", vault=~\"$vaults\"}) / sum(yearn_strategy{network=\"$networks\", param=\"totalLoss\", vault=~\"$vaults\"} offset 1d)) - 1",
       "legendFormat": "{{vault}}"
      }
     ]
    },
    {
     "title": "TVL- 7D change",
     "type": "stat",
     "gridPos": { "h": 3, "w": 4, "x": 0, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "yearn_vault{network=\"$networks\", param=\"tvl\", vault=~\"$vaults\"} - yearn_vault{network=\"$networks\", param=\"tvl\", vault=~\"$vaults\"} offset 7d",
       "legendFormat": "{{vault}}"
      }
     ]
    },
    {
     "title": "TVL - 7D % change",
     "type": "stat",
     "gridPos": { "h": 3, "w": 4, "x": 4, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "(yearn_vault{network=\"$networks\", param=\"tvl\", vault=~\"$vaults\"} / yearn_vault{network=\"$networks\", param=\"tvl\", vault=~\"$vaults\"} offset 7d ) - 1",
       "legendFormat": "{{vault}}"
      }
     ]
    },
    {
     "title": "totalDebt - 7D change",
     "type": "stat",
     "gridPos": { "h": 3, "w": 4, "x": 8, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(yearn_strategy{network=\"$networks\", param=\"totalDebt\", vault=~\"$vaults\"}) - sum(yearn_strategy{network=\"$networks\", param=\"totalDebt\", vault=~\"$vaults\"} offset 7d)",
       "legendFormat": "{{strategy}}"
      }
     ]
    },
    {
     "title": "totalDebt - 7D % change",
     "type": "stat",
     "gridPos": { "h": 3, "w": 4, "x": 12, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "(sum(yearn_strategy{network=\"$networks\", param=\"totalDebt\", vault=~\"$vaults\"}) / sum(yearn_strategy{network=\"$networks\", param=\"totalDebt\", vault=~\"$vaults\"} offset 7d)) - 1",
       "legendFormat": "{{vault}}"
      }
     ]
    },
    {
     "title": "totalLoss - 7D change",
     "type": "stat",
     "gridPos": { "h": 3, "w": 4, "x": 16, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(yearn_strategy{network=\"$networks\", param=\"totalLoss\", vault=~\"$vaults\"}) - sum(yearn_strategy{network=\"$networks\", param=\"totalLoss\", vault=~\"$vaults\"} offset 7d)",
       "legendFormat": "{{strategy}}"
      }
     ]
    },
    {
     "title": "totalLoss - 7D % change",
     "type": "stat",
     "gridPos": { "h": 3, "w": 4, "x": 20, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "(sum(yearn_strategy{network=\"$networks\", param=\"totalLoss\", vault=~\"$vaults\"}) / sum(yearn_strategy{network=\"$networks\", param=\"totalLoss\", vault=~\"$vaults\"} offset 7d)) - 1",
       "legendFormat": "{{vault}}"
      }
     ]
    },
    {
     "title": "Total Gain",
     "type": "graph",
     "description": "Total amount of Deposit tokens in strategy",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 28 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "yearn_strategy{network=\"$networks\", param=\"totalGain\", vault=~\"$vaults\"}",
       "legendFormat": "{{strategy}}"
      },
      {
       "expr": "sum(yearn_strategy{network=\"$networks\", param=\"totalGain\", vault=~\"$vaults\"})",
       "legendFormat": "totalGain"
      }
     ]
    },
    {
     "title": "Total Gain Delta",
     "type": "graph",
     "description": "Rate of increase of totalGain for strategies",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 28 },
     "yaxes": [
      { "format": "short", "label": "Rate of increase" }
     ],
     "targets": [
      {
       "expr": "delta(yearn_strategy{network=\"$networks\", param=\"totalGain\", vault=~\"$vaults\"}[5m])",
       "legendFormat": "{{strategy}}"
      }
     ]
    },
    {
     "title": "Total loss",
     "type": "graph",
     "description": "totalLoss per strategy ",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 37 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "yearn_strategy{network=\"$networks\", param=\"totalLoss\", vault=~\"$vaults\"}",
       "legendFormat": "{{strategy}}"
      },
      {
       "expr": "sum(yearn_strategy{network=\"$networks\", param=\"totalLoss\", vault=~\"$vaults\"})",
       "legendFormat": "totalLoss"
      }
     ]
    },
    {
     "title": "Total Loss Delta",
     "type": "graph",
     "description": "Rate of change of totalLoss per strategy 5m delta",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 37 },
     "yaxes": [
      { "format": "short", "label": "Rate of increase" }
     ],
     "targets": [
      {
       "expr": "delta(yearn_strategy{network=\"$networks\", param=\"totalLoss\", vault=~\"$vaults\"}[5m])",
       "legendFormat": "{{strategy}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Assets Delta Extra",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 },
   "collapsed": true,
   "panels": [
    {
     "title": "Total Gain - Loss ",
     "type": "graph",
     "description": "Total amount of Gain - Loss ",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 23 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by (strategy) (yearn_strategy{network=\"$networks\", param=~\"totalGain\", vault=~\"$vaults\"}) - sum by (strategy) (yearn_strategy{network=\"$networks\", param=\"totalLoss\", vault=~\"$vaults\"})",
       "legendFormat": "{{strategy}}"
      }
     ]
    },
    {
     "title": "Total Gain - Loss Delta",
     "type": "graph",
     "description": "Rate of change of total 5m delta",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 23 },
     "yaxes": [
      { "format": "short", "label": "Rate of increase" }
     ],
     "targets": [
      {
       "expr": "sum by (strategy) (delta(yearn_strategy{network=\"$networks\", param=~\"totalGain\", vault=~\"$vaults\"}[5m])) - sum by (strategy) (delta(yearn_strategy{network=\"$networks\", param=\"totalLoss\", vault=~\"$vaults\"}[5m]))",
       "legendFormat": "{{strategy}}"
      }
     ]
    }
   ]
  },
  { "title": "Harvest", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 } },
  {
   "title": "Last Harvest",
   "type": "stat",
   "gridPos": { "h": 14, "w": 11, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sort(time() - (yearn_strategy{network=\"$networks\", param=\"lastReport\", vault=~\"$vaults\"}))",
     "legendFormat": "{{strategy}}"
    }
   ]
  },
  {
   "title": "maxReportDelay",
   "type": "stat",
   "description": "Keepers need to call Havest before this time. ",
   "gridPos": { "h": 14, "w": 7, "x": 11, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sort(yearn_strategy{network=\"$networks\", param=\"maxReportDelay\", vault=~\"$vaults\"})",
     "legendFormat": "{{strategy}}"
    }
   ]
  },
  {
   "title": "minReportDelay",
   "type": "stat",
   "description": "Min amount of before Keepers can call harvest again",
   "gridPos": { "h": 14, "w": 6, "x": 18, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sort(yearn_strategy{network=\"$networks\", param=\"minReportDelay\", vault=~\"$vaults\"})",
     "legendFormat": "{{strategy}}"
    }
   ]
  },
  {
   "title": "Share Price",
   "type": "stat",
   "description": "Current Share Price for the vault selected",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "yearn_vault{network=\"$networks\", param=\"pricePerShare\", vault=~\"$vaults\"}",
     "legendFormat": "{{vault}}"
    }
   ]
  },
  {
   "title": "Share Price - Change over Time Range Selected",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 8, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "yearn_vault{network=\"$networks\", param=\"pricePerShare\", vault=~\"$vaults\"} - yearn_vault{network=\"$networks\", param=\"pricePerShare\", vault=~\"$vaults\"} offset $__range",
     "legendFormat": "{{vault}}"
    }
   ]
  },
  {
   "title": "Share Price - % Share Price Change over Time Range Selected",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 16, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "(yearn_vault{network=\"$networks\", param=\"pricePerShare\", vault=~\"$vaults\"} / yearn_vault{network=\"$networks\", param=\"pricePerShare\", vault=~\"$vaults\"} offset $__range) - 1",
     "legendFormat": "{{vault}}"
    }
   ]
  },
  {
   "title": "share price",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "yearn_vault{network=\"$networks\", param=\"pricePerShare\", vault=~\"$vaults\"}",
     "legendFormat": "{{vault}}"
    }
   ]
  },
  {
   "title": "Static Variables",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 51 },
   "collapsed": true,
   "panels": [
    {
     "title": "debtRatio  Strategies",
     "type": "stat",
     "gridPos": { "h": 20, "w": 4, "x": 0, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sort_desc((yearn_strategy{network=\"$networks\", param=\"debtRatio\", vault=~\"$vaults\"}/100 > 0))",
       "legendFormat": "{{strategy}}"
      }
     ]
    },
    {
     "title": "debtThreshold",
     "type": "stat",
     "gridPos": { "h": 20, "w": 4, "x": 4, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sort_desc(yearn_strategy{network=\"$networks\", param=\"debtThreshold\", vault=~\"$vaults\"}/1000000000000000)",
       "legendFormat": "{{strategy}}"
      }
     ]
    },
    {
     "title": "maxDebtPerHarvest",
     "type": "stat",
     "description": "Max amount of allocatable funds per harvest",
     "gridPos": { "h": 20, "w": 4, "x": 8, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "sort_desc(yearn_strategy{network=\"$networks\", param=\"maxDebtPerHarvest\", vault=~\"$vaults\"})",
       "legendFormat": "{{strategy}}"
      }
     ]
    },
    {
     "title": "debtRatio Vault",
     "type": "stat",
     "description": "Vault debtRatio",
     "gridPos": { "h": 4, "w": 2, "x": 12, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "yearn_vault{network=\"$networks\", param=\"debtRatio\", vault=~\"$vaults\"}/100",
       "legendFormat": "{{param}}"
      }
     ]
    },
    {
     "title": "debtRatio Strategies",
     "type": "stat",
     "description": "Strategies debtRatio summed",
     "gridPos": { "h": 4, "w": 2, "x": 14, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(yearn_strategy{network=\"$networks\", param=\"debtRatio\", vault=~\"$vaults\"}/100)",
       "legendFormat": "{{strategy}}"
      }
     ]
    },
    {
     "title": "minDebtPerHarvest",
     "type": "stat",
     "description": "Min amount of allocatable funds per harvest",
     "gridPos": { "h": 20, "w": 4, "x": 16, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "sort_desc(yearn_strategy{network=\"$networks\", param=\"minDebtPerHarvest\", vault=~\"$vaults\"})",
       "legendFormat": "{{strategy}}"
      }
     ]
    },
    {
     "title": "Date Added ",
     "type": "stat",
     "description": "Activation Date",
     "gridPos": { "h": 19, "w": 4, "x": 20, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sort(time() - yearn_strategy{network=\"$networks\", param=\"activation\", vault=~\"$vaults\"})",
       "legendFormat": "{{strategy}}"
      }
     ]
    },
    {
     "title": "buffer",
     "type": "stat",
     "description": "Amount of funds to keep for withdrawals",
     "gridPos": { "h": 4, "w": 4, "x": 12, "y": 29 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "yearn_strategy{network=\"$networks\", param=\"buffer\", vault=~\"$vaults\"}/1000",
       "legendFormat": "{{param}}"
      }
     ]
    },
    {
     "title": "Deposit Limit ",
     "type": "stat",
     "description": "availableDepositLimit",
     "gridPos": { "h": 4, "w": 4, "x": 12, "y": 33 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "yearn_vault{network=\"$networks\", param=\"availableDepositLimit\", vault=~\"$vaults\"}",
       "legendFormat": "{{param}}"
      }
     ]
    },
    {
     "title": "lockedProfit",
     "type": "stat",
     "gridPos": { "h": 4, "w": 4, "x": 12, "y": 37 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "yearn_vault{network=\"$networks\", param=\"lockedProfit\", vault=~\"$vaults\"}"
      }
     ]
    },
    {
     "title": "lockedProfitDegradation",
     "type": "stat",
     "gridPos": { "h": 4, "w": 4, "x": 12, "y": 41 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "yearn_vault{network=\"$networks\", param=\"lockedProfitDegradation\", vault=~\"$vaults\"}"
      }
     ]
    }
   ]
  }
 ]
}