{
 "title": "APY Technical",
 "description": "This dashboard give you an overview of net apy for vaults",
 "tags": [
  "APY",
  "Overview"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "The Recommended Method - What Yearn.Finance uses",
   "type": "text",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "# APY Taking the Weekly Difference of Share Price\n### With Weekly Compounding\n\n           "
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "v2 yVaults",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "panels": [
    {
     "title": "v2 - Net APY",
     "type": "bargauge",
     "description": "This looks at the share price rate of change and factors in compounding on a weekly basis. ",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sort_desc(((delta(yearn_vault{param=\"pricePerShare\", experimental=\"false\"}[1w]) + 1) ^ (1/7)) ^ 365 - 1) ",
       "legendFormat": "{{vault}}"
      }
     ]
    },
    {
     "title": "v2 - Net APY",
     "type": "graph",
     "description": "This looks at the share price rate of change and factors in compounding on a weekly basis. ",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "((delta(yearn_vault{param=\"pricePerShare\", experimental=\"false\"}[1w]) + 1) ^ (1/7)) ^ 365 - 1",
       "legendFormat": "{{vault}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Earn",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "collapsed": true,
   "panels": [
    {
     "title": "busd.curve.fi Earn v3 - Net APY",
     "type": "bargauge",
     "description": "This looks at the share price rate of change and factors in compounding on a weekly basis. ",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 24 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sort_desc(((delta(iearn{param=\"price per share\", vault=~\".*v3\"}[1w]) + 1) ^ (1/7)) ^ 365 - 1) ",
       "legendFormat": "{{vault}}"
      }
     ]
    },
    {
     "title": "y.curve.fi Earn v2 - Net APY",
     "type": "bargauge",
     "description": "This looks at the share price rate of change and factors in compounding on a weekly basis. ",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 35 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sort_desc(((delta(iearn{param=\"price per share\", vault=~\".*v2\"}[1w]) + 1) ^ (1/7)) ^ 365 - 1) ",
       "legendFormat": "{{vault}}"
      }
     ]
    },
    {
     "title": "Earn Net APY",
     "type": "graph",
     "description": "This looks at the share price rate of change and factors in compounding on a weekly basis. ",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 46 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "((delta(iearn{param=\"price per share\"}[1w]) + 1) ^ (1/7)) ^ 365 - 1",
       "legendFormat": "{{vault}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Experimental yVaults",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "collapsed": true,
   "panels": [
    {
     "title": "Experimental Vault's - Net APY",
     "type": "bargauge",
     "description": "This looks at the share price rate of change and factors in compounding on a weekly basis. ",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 57 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sort_desc(((delta(yearn_vault{param=\"pricePerShare\",experimental=\"true\"}[1w]) + 1) ^ (1/7)) ^ 365 - 1)",
       "legendFormat": "{{vault}}"
      }
     ]
    },
    {
     "title": "Experimental Vault's - Net APY",
     "type": "graph",
     "description": "This looks at the share price rate of increase and factors in compounding on a weekly basis. ",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 68 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "((delta(yearn_vault{param=\"pricePerShare\",experimental=\"true\"}[1w]) + 1) ^ (1/7)) ^ 365 - 1",
       "legendFormat": "{{vault}}"
      }
     ]
    }
   ]
  },
  {
   "title": "v1 yVaults",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "collapsed": true,
   "panels": [
    {
     "title": "v1 - Net APY",
     "type": "bargauge",
     "description": "This looks at the share price rate of change and factors in compounding on a weekly basis. ",
     "gridPos": { "h": 8, "w": 20, "x": 0, "y": 79 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sort_desc(((delta(yearn{param=\"share price\"}[1w]) + 1) ^ (1/7)) ^ 365 - 1) ",
       "legendFormat": "{{vault}}"
      }
     ]
    },
    {
     "title": "v1 - Net APY",
     "type": "graph",
     "description": "This looks at the share price rate of change and factors in compounding on a weekly basis. ",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 87 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "((delta(yearn{param=\"share price\"}[1w]) + 1) ^ (1/7)) ^ 365 - 1",
       "legendFormat": "{{vault}}"
      }
     ]
    }
   ]
  },
  {
   "title": "v2 yVaults - APY taking the Weekly Difference of Share Price with Bi-Weekly Compounding",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "collapsed": true,
   "panels": [
    {
     "title": "v2 - Net APY",
     "type": "bargauge",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sort_desc(((delta(yearn_vault{param=\"pricePerShare\", experimental=\"false\"}[1w]) + 1) ^ (2/7)) ^ 365 - 1) ",
       "legendFormat": "{{vault}}"
      }
     ]
    },
    {
     "title": "v2 - Net APY",
     "type": "graph",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "((delta(yearn_vault{param=\"pricePerShare\", experimental=\"false\"}[1w]) + 1) ^ (2/7)) ^ 365 - 1",
       "legendFormat": "{{vault}}"
      }
     ]
    }
   ]
  },
  {
   "title": "v2 yVaults - APY taking the Daily Difference of Share Price with Weekly Compounding",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "collapsed": true,
   "panels": [
    {
     "title": "v2 - Net APY",
     "type": "bargauge",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sort_desc(((delta(yearn_vault{param=\"pricePerShare\", experimental=\"false\"}[1d]) + 1) ^ (1/7)) ^ 365 - 1) ",
       "legendFormat": "{{vault}}"
      }
     ]
    },
    {
     "title": "v2 - Net APY",
     "type": "graph",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "((delta(yearn_vault{param=\"pricePerShare\", experimental=\"false\"}[1d]) + 1) ^ (1/7)) ^ 365 - 1 ",
       "legendFormat": "{{vault}}"
      }
     ]
    }
   ]
  },
  {
   "title": "v2 yVaults - APY taking the Daily Difference of Share Price with Bi-Weekly Compounding",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "collapsed": true,
   "panels": [
    {
     "title": "v2 - Net APY",
     "type": "bargauge",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sort_desc(((delta(yearn_vault{param=\"pricePerShare\", experimental=\"false\"}[1d]) + 1) ^ (2/7)) ^ 365 - 1) ",
       "legendFormat": "{{vault}}"
      }
     ]
    },
    {
     "title": "v2 - Net APY ",
     "type": "graph",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "((delta(yearn_vault{param=\"pricePerShare\", experimental=\"false\"}[1d]) + 1) ^ (2/7)) ^ 365 - 1",
       "legendFormat": "{{vault}}"
      }
     ]
    }
   ]
  },
  {
   "title": "v2 yVaults - APY taking the Monthly Difference of Share Price with Weekly Compounding",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 },
   "collapsed": true,
   "panels": [
    {
     "title": "v2 - Net APY",
     "type": "bargauge",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sort_desc(((delta(yearn_vault{param=\"pricePerShare\", experimental=\"false\"}[30d]) + 1) ^ (1/7)) ^ 365 - 1) ",
       "legendFormat": "{{vault}}"
      }
     ]
    },
    {
     "title": "v2 - Net APY",
     "type": "graph",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "((delta(yearn_vault{param=\"pricePerShare\", experimental=\"false\"}[30d]) + 1) ^ (1/7)) ^ 365 - 1",
       "legendFormat": "{{vault}}"
      }
     ]
    }
   ]
  },
  {
   "title": "v2 yVaults - APY taking the Monthly Difference of Share Price with Bi-Weekly Compounding",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 },
   "collapsed": true,
   "panels": [
    {
     "title": "v2 - Net APY",
     "type": "bargauge",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sort_desc(((delta(yearn_vault{param=\"pricePerShare\", experimental=\"false\"}[30d]) + 1) ^ (2/7)) ^ 365 - 1) ",
       "legendFormat": "{{vault}}"
      }
     ]
    },
    {
     "title": "v2 - Net APY",
     "type": "graph",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "((delta(yearn_vault{param=\"pricePerShare\", experimental=\"false\"}[30d]) + 1) ^ (2/7)) ^ 365 - 1",
       "legendFormat": "{{vault}}"
      }
     ]
    }
   ]
  }
 ]
}