{
 "title": "Overview",
 "tags": [ "Overview" ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 0 },
   "options": {
    "content": "### Total Value Locked\ntotal value locked across yearn products"
   }
  },
  {
   "title": "total",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(yearn{param=\"tvl\"}) + sum(ironbank{param=\"tvl\"}) + sum(yearn_vault{param=\"tvl\"}) + sum(iearn{param=\"tvl\"})"
    }
   ]
  },
  {
   "title": "daily delta",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(delta(yearn{param=\"tvl\"}[1d])) + sum(delta(ironbank{param=\"tvl\"}[1d])) + sum(delta(yearn_vault{param=\"tvl\"}[1d])) + sum(delta(iearn{param=\"tvl\"}[1d]))"
    }
   ]
  },
  {
   "title": "weekly delta",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(delta(yearn{param=\"tvl\"}[1w])) + sum(delta(ironbank{param=\"tvl\"}[1w])) + sum(delta(yearn_vault{param=\"tvl\"}[1w])) + sum(delta(iearn{param=\"tvl\"}[1w]))"
    }
   ]
  },
  {
   "title": "vecrv balance",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(yearn{param=\"vecrv balance\"})"
    }
   ]
  },
  {
   "title": "vecrv share",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(yearn{param=\"vecrv balance\"}) / avg(yearn{param=\"vecrv total\"})"
    }
   ]
  },
  {
   "title": "yearn tvl",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 3 },
   "yaxes": [
    { "format": "currencyUSD" }
   ],
   "targets": [
    {
     "expr": "sum(iearn{param=\"tvl\"})",
     "legendFormat": "earn"
    },
    {
     "expr": "sum(ironbank{param=\"tvl\"})",
     "legendFormat": "ironbank"
    },
    {
     "expr": "sum(yearn{param=\"tvl\"})",
     "legendFormat": "v1"
    },
    {
     "expr": "sum(yearn_vault{param=\"tvl\"})",
     "legendFormat": "v2"
    }
   ]
  },
  {
   "title": "yearn tvl daily change",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 3 },
   "yaxes": [
    { "format": "currencyUSD" }
   ],
   "targets": [
    {
     "expr": "sum(delta(iearn{param=\"tvl\"}[1d]))",
     "legendFormat": "earn"
    },
    {
     "expr": "sum(delta(ironbank{param=\"tvl\"}[1d]))",
     "legendFormat": "ironbank"
    },
    {
     "expr": "sum(delta(yearn{param=\"tvl\"}[1d]))",
     "legendFormat": "v1"
    },
    {
     "expr": "sum(delta(yearn_vault{param=\"tvl\"}[1d]))",
     "legendFormat": "v2"
    }
   ]
  },
  {
   "title": "v2 tvl",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "currencyUSD" }
   ],
   "targets": [
    {
     "expr": "yearn_vault{param=\"tvl\",experimental=\"false\"} != 0",
     "legendFormat": "{{vault}}"
    }
   ]
  },
  {
   "title": "v2 tvl daily",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
   "yaxes": [
    { "format": "currencyUSD" }
   ],
   "targets": [
    {
     "expr": "delta(yearn_vault{param=\"tvl\",experimental=\"false\"}[1d]) != 0",
     "legendFormat": "{{vault}}"
    },
    {
     "expr": "sum(delta(yearn_vault{param=\"tvl\",experimental=\"false\"}[1d]))",
     "legendFormat": "net inflow/outflow"
    }
   ]
  },
  {
   "title": "v1 tvl",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "currencyUSD" }
   ],
   "targets": [
    {
     "expr": "yearn{param=\"tvl\"} != 0",
     "legendFormat": "{{vault}}"
    }
   ]
  },
  {
   "title": "v1 tvl daily",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
   "yaxes": [
    { "format": "currencyUSD" }
   ],
   "targets": [
    {
     "expr": "delta(yearn{param=\"tvl\"}[1d]) != 0",
     "legendFormat": "{{vault}}"
    },
    {
     "expr": "sum(delta(yearn{param=\"tvl\"}[1d]))",
     "legendFormat": "net inflow/outflow"
    }
   ]
  },
  {
   "title": "ironbank tvl",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "currencyUSD" }
   ],
   "targets": [
    {
     "expr": "ironbank{param=\"tvl\"} != 0",
     "legendFormat": "{{vault}}"
    }
   ]
  },
  {
   "title": "ironbank tvl daily",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
   "yaxes": [
    { "format": "currencyUSD" }
   ],
   "targets": [
    {
     "expr": "delta(ironbank{param=\"tvl\"}[1d]) != 0",
     "legendFormat": "{{vault}}"
    },
    {
     "expr": "sum(delta(ironbank{param=\"tvl\"}[1d]))",
     "legendFormat": "net inflow/outflow"
    }
   ]
  },
  {
   "title": "iearn tvl",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 35 },
   "yaxes": [
    { "format": "currencyUSD" }
   ],
   "targets": [
    {
     "expr": "iearn{param=\"tvl\"} != 0",
     "legendFormat": "{{vault}}"
    }
   ]
  },
  {
   "title": "iearn tvl daily",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 35 },
   "yaxes": [
    { "format": "currencyUSD" }
   ],
   "targets": [
    {
     "expr": "delta(iearn{param=\"tvl\"}[1d]) != 0",
     "legendFormat": "{{vault}}"
    },
    {
     "expr": "sum(delta(iearn{param=\"tvl\"}[1d]))",
     "legendFormat": "net inflow/outflow"
    }
   ]
  },
  {
   "title": "ve tvl",
   "type": "graph",
   "description": "Experimental vaults on ape.tax TVL",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 43 },
   "yaxes": [
    { "format": "currencyUSD" }
   ],
   "targets": [
    {
     "expr": "yearn_vault{param=\"tvl\", experimental=\"true\"} != 0",
     "legendFormat": "{{vault}}"
    }
   ]
  },
  {
   "title": "ve tvl daily",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 43 },
   "yaxes": [
    { "format": "currencyUSD" }
   ],
   "targets": [
    {
     "expr": "delta(yearn_vault{param=\"tvl\", experimental=\"true\"}[1d]) != 0",
     "legendFormat": "{{vault}}"
    },
    {
     "expr": "sum(delta(yearn_vault{param=\"tvl\", experimental=\"true\"}[1d]))",
     "legendFormat": "net inflow/outflow"
    }
   ]
  },
  {
   "title": "time since last report",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 51 },
   "yaxes": [
    { "format": "dtdurations" }
   ],
   "targets": [
    {
     "expr": "time() - yearn_vault{param=\"lastReport\", experimental=\"false\", vault!~\"yvUSDC 0.2.2|yvDAI 0.2.2|yvWBTC 0.3.1|yvHEGIC 0.3.0\"}",
     "legendFormat": "{{vault}}"
    }
   ]
  },
  {
   "title": "price per share",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 51 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "yearn_vault{param=\"pricePerShare\",experimental=\"false\"}",
     "legendFormat": "{{vault}}"
    },
    {
     "expr": "yearn{param=\"share price\"}",
     "legendFormat": "{{vault}}"
    },
    {
     "expr": "yearn_vault{param=\"pricePerShare\",experimental=\"true\"}",
     "legendFormat": "{{vault}} - exp"
    }
   ]
  },
  {
   "title": "vecrv balance",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 59 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "yearn{vault=\"curve.fi/3pool\",param=\"vecrv balance\"}",
     "legendFormat": "{{param}}"
    },
    {
     "expr": "avg(yearn{vault=\"curve.fi/3pool\",param=\"vecrv balance\"}) / avg(yearn{vault=\"curve.fi/3pool\",param=\"vecrv total\"})",
     "legendFormat": "vecrv share"
    }
   ]
  },
  {
   "title": "price per share change 1d annualized",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 59 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "delta(yearn_vault{param=\"pricePerShare\",experimental=\"false\"}[1d]) * 365",
     "legendFormat": "{{vault}}"
    },
    {
     "expr": "delta(yearn{param=\"share price\"}[1d]) * 365",
     "legendFormat": "{{vault}}"
    },
    {
     "expr": "delta(yearn_vault{param=\"pricePerShare\",experimental=\"true\"}[1d]) * 365",
     "legendFormat": "{{vault}} - exp"
    }
   ]
  }
 ]
}