{
 "title": "Vault Management",
 "time": { "from": "now-30d", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "TVL ($)",
   "type": "stat",
   "description": "Total TVL of yearn vaults not subtracting delegated deposits",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(sum by (vault) (yearn_vault{param=\"tvl\", experimental=\"false\", vault!~\"yvUSDC 0.2.2|yvDAI 0.2.2|yvWBTC 0.3.1|yvHEGIC 0.3.0\"}))",
     "legendFormat": "Unallocated TVL ($)"
    }
   ]
  },
  {
   "title": "Unallocated TVL ($)",
   "type": "stat",
   "description": "$ of Funds unallocated",
   "gridPos": { "h": 4, "w": 3, "x": 7, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(sum by (vault) (yearn_vault{param=\"tvl\", experimental=\"false\", vault!~\"yvUSDC 0.2.2|yvDAI 0.2.2|yvWBTC 0.3.1|yvHEGIC 0.3.0\"}) * ((sum by (vault) (yearn_vault{param=\"totalAssets\", experimental=\"false\", vault!~\"yvUSDC 0.2.2|yvDAI 0.2.2|yvWBTC 0.3.1|yvHEGIC 0.3.0\"})-(sum by (vault) (yearn_vault{param=\"totalDebt\", experimental=\"false\", vault!~\"yvUSDC 0.2.2|yvDAI 0.2.2|yvWBTC 0.3.1|yvHEGIC 0.3.0\"}))) / (sum by (vault) (yearn_vault{param=\"totalAssets\", experimental=\"false\", vault!~\"yvUSDC 0.2.2|yvDAI 0.2.2|yvWBTC 0.3.1|yvHEGIC 0.3.0\"}) )))",
     "legendFormat": "Unallocated TVL ($)"
    }
   ]
  },
  {
   "title": "Unallocated TVL (%)",
   "type": "stat",
   "description": "% of Funds unallocated",
   "gridPos": { "h": 4, "w": 3, "x": 11, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(sum by (vault) (yearn_vault{param=\"tvl\", experimental=\"false\", vault!~\"yvUSDC 0.2.2|yvDAI 0.2.2|yvWBTC 0.3.1|yvHEGIC 0.3.0\"}) * ((sum by (vault) (yearn_vault{param=\"totalAssets\", experimental=\"false\", vault!~\"yvUSDC 0.2.2|yvDAI 0.2.2|yvWBTC 0.3.1|yvHEGIC 0.3.0\"}))-(sum by (vault) (yearn_vault{param=\"totalDebt\", experimental=\"false\", vault!~\"yvUSDC 0.2.2|yvDAI 0.2.2|yvWBTC 0.3.1|yvHEGIC 0.3.0\"}))) / (sum by (vault) (yearn_vault{param=\"totalAssets\", experimental=\"false\", vault!~\"yvUSDC 0.2.2|yvDAI 0.2.2|yvWBTC 0.3.1|yvHEGIC 0.3.0\"}) )) / sum((yearn_vault{param=\"tvl\", experimental=\"false\", vault!~\"yvUSDC 0.2.2|yvDAI 0.2.2|yvWBTC 0.3.1|yvHEGIC 0.3.0\"}))",
     "legendFormat": "Unallocated TVL (%)"
    }
   ]
  },
  {
   "title": "Avg APY",
   "type": "stat",
   "description": "Avg summed apy for all production vaults. This is with weekly compounding taking the share price difference over a week.",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg((((delta(yearn_vault{param=\"pricePerShare\", experimental=\"false\", vault!~\"yvUSDC 0.2.2|yvDAI 0.2.2|yvWBTC 0.3.1|yvHEGIC 0.3.0\"}[7d]) + 1) ^ (1/7)) ^ 365 - 1) < 1000)",
     "legendFormat": "APY (avg) (%)"
    }
   ]
  },
  {
   "title": "σ APY",
   "type": "stat",
   "description": "Current Standard Deviation of summed APY ",
   "gridPos": { "h": 4, "w": 3, "x": 19, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "stddev((((delta(yearn_vault{param=\"pricePerShare\", experimental=\"false\", vault!~\"yvUSDC 0.2.2|yvDAI 0.2.2|yvWBTC 0.3.1|yvHEGIC 0.3.0\"}[7d]) + 1) ^ (1/7)) ^ 365 - 1) < 1000)",
     "legendFormat": "APY (std)"
    }
   ]
  },
  {
   "title": "Δ 7 Days",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "panels": [
    {
     "title": "TVL ($)",
     "type": "stat",
     "description": "$ of Funds unallocated from 7 days ago",
     "gridPos": { "h": 3, "w": 3, "x": 3, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(sum by (vault) (yearn_vault{param=\"tvl\", experimental=\"false\", vault!~\"yvUSDC 0.2.2|yvDAI 0.2.2|yvWBTC 0.3.1|yvHEGIC 0.3.0\"})) offset 7d",
       "legendFormat": "Unallocated TVL ($)"
      }
     ]
    },
    {
     "title": "Unallocated TVL ($)",
     "type": "stat",
     "description": "$ of Funds unallocated from 7 days ago",
     "gridPos": { "h": 3, "w": 3, "x": 7, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(sum by (vault) (yearn_vault{param=\"tvl\", experimental=\"false\", vault!~\"yvUSDC 0.2.2|yvDAI 0.2.2|yvWBTC 0.3.1|yvHEGIC 0.3.0\"}) * ((sum by (vault) (yearn_vault{param=\"totalAssets\", experimental=\"false\", vault!~\"yvUSDC 0.2.2|yvDAI 0.2.2|yvWBTC 0.3.1|yvHEGIC 0.3.0\"})-(sum by (vault) (yearn_vault{param=\"totalDebt\", experimental=\"false\", vault!~\"yvUSDC 0.2.2|yvDAI 0.2.2|yvWBTC 0.3.1|yvHEGIC 0.3.0\"}))) / (sum by (vault) (yearn_vault{param=\"totalAssets\", experimental=\"false\", vault!~\"yvUSDC 0.2.2|yvDAI 0.2.2|yvWBTC 0.3.1|yvHEGIC 0.3.0\"}) ))) offset 7d",
       "legendFormat": "Unallocated TVL ($)"
      }
     ]
    },
    {
     "title": "Unallocated TVL (%)",
     "type": "stat",
     "description": "% of Funds unallocated from 7 days ago",
     "gridPos": { "h": 3, "w": 3, "x": 11, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(sum by (vault) (yearn_vault{param=\"tvl\", experimental=\"false\", vault!~\"yvUSDC 0.2.2|yvDAI 0.2.2|yvWBTC 0.3.1|yvHEGIC 0.3.0\"}) * ((sum by (vault) (yearn_vault{param=\"totalAssets\", experimental=\"false\", vault!~\"yvUSDC 0.2.2|yvDAI 0.2.2|yvWBTC 0.3.1|yvHEGIC 0.3.0\"}))-(sum by (vault) (yearn_vault{param=\"totalDebt\", experimental=\"false\", vault!~\"yvUSDC 0.2.2|yvDAI 0.2.2|yvWBTC 0.3.1|yvHEGIC 0.3.0\"}))) / (sum by (vault) (yearn_vault{param=\"totalAssets\", experimental=\"false\", vault!~\"yvUSDC 0.2.2|yvDAI 0.2.2|yvWBTC 0.3.1|yvHEGIC 0.3.0\"}) )) / sum((yearn_vault{param=\"tvl\", experimental=\"false\", vault!~\"yvUSDC 0.2.2|yvDAI 0.2.2|yvWBTC 0.3.1|yvHEGIC 0.3.0\"})) offset 7d",
       "legendFormat": "Unallocated TVL (%)"
      }
     ]
    },
    {
     "title": "Avg APY",
     "type": "stat",
     "description": "Avg summed apy for all production vaults. This is with weekly compunding taking the share price difference over a week from 7 days ago. ",
     "gridPos": { "h": 3, "w": 3, "x": 15, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "avg((((delta(yearn_vault{param=\"pricePerShare\", experimental=\"false\", vault!~\"yvUSDC 0.2.2|yvDAI 0.2.2|yvWBTC 0.3.1|yvHEGIC 0.3.0\"}[7d]) + 1) ^ (1/7)) ^ 365 - 1) < 1000) offset 7d",
       "legendFormat": "APY (avg) (%)"
      }
     ]
    },
    {
     "title": "σ APY",
     "type": "stat",
     "description": "Standard deviation from 7 days ago",
     "gridPos": { "h": 3, "w": 3, "x": 19, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "stddev((((delta(yearn_vault{param=\"pricePerShare\", experimental=\"false\", vault!~\"yvUSDC 0.2.2|yvDAI 0.2.2|yvWBTC 0.3.1|yvHEGIC 0.3.0\"}[7d]) + 1) ^ (1/7)) ^ 365 - 1) < 1000) offset 7d",
       "legendFormat": "APY (std)"
      }
     ]
    },
    {
     "title": "Δ TVL ($)",
     "type": "stat",
     "description": "% of TVL from 7 days ago,  % change from 7 day to current",
     "gridPos": { "h": 2, "w": 3, "x": 3, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(sum by (vault) (yearn_vault{param=\"tvl\", experimental=\"false\", vault!~\"yvUSDC 0.2.2|yvDAI 0.2.2|yvWBTC 0.3.1|yvHEGIC 0.3.0\"}))",
       "legendFormat": "Unallocated TVL (%) "
      },
      {
       "expr": "sum(sum by (vault) (yearn_vault{param=\"tvl\", experimental=\"false\", vault!~\"yvUSDC 0.2.2|yvDAI 0.2.2|yvWBTC 0.3.1|yvHEGIC 0.3.0\"})) offset 7d",
       "legendFormat": "Unallocated TVL (%) 7 day"
      }
     ]
    },
    {
     "title": "Δ Unallocated TVL %",
     "type": "stat",
     "description": "$ of Funds unallocated from 7 days ago, % change from 7 day to current",
     "gridPos": { "h": 2, "w": 3, "x": 7, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(sum by (vault) (yearn_vault{param=\"tvl\", experimental=\"false\", vault!~\"yvUSDC 0.2.2|yvDAI 0.2.2|yvWBTC 0.3.1|yvHEGIC 0.3.0\"}) * ((sum by (vault) (yearn_vault{param=\"totalAssets\", experimental=\"false\", vault!~\"yvUSDC 0.2.2|yvDAI 0.2.2|yvWBTC 0.3.1|yvHEGIC 0.3.0\"})-(sum by (vault) (yearn_vault{param=\"totalDebt\", experimental=\"false\", vault!~\"yvUSDC 0.2.2|yvDAI 0.2.2|yvWBTC 0.3.1|yvHEGIC 0.3.0\"}))) / (sum by (vault) (yearn_vault{param=\"totalAssets\", experimental=\"false\", vault!~\"yvUSDC 0.2.2|yvDAI 0.2.2|yvWBTC 0.3.1|yvHEGIC 0.3.0\"}) )))",
       "legendFormat": "Unallocated TVL %"
      },
      {
       "expr": "sum(sum by (vault) (yearn_vault{param=\"tvl\", experimental=\"false\", vault!~\"yvUSDC 0.2.2|yvDAI 0.2.2|yvWBTC 0.3.1|yvHEGIC 0.3.0\"}) * ((sum by (vault) (yearn_vault{param=\"totalAssets\", experimental=\"false\", vault!~\"yvUSDC 0.2.2|yvDAI 0.2.2|yvWBTC 0.3.1|yvHEGIC 0.3.0\"})-(sum by (vault) (yearn_vault{param=\"totalDebt\", experimental=\"false\", vault!~\"yvUSDC 0.2.2|yvDAI 0.2.2|yvWBTC 0.3.1|yvHEGIC 0.3.0\"}))) / (sum by (vault) (yearn_vault{param=\"totalAssets\", experimental=\"false\", vault!~\"yvUSDC 0.2.2|yvDAI 0.2.2|yvWBTC 0.3.1|yvHEGIC 0.3.0\"}) ))) offset 7d",
       "legendFormat": "Unallocated TVL % 7 day offset"
      }
     ]
    },
    {
     "title": "Δ Unallocated TVL %",
     "type": "stat",
     "description": "$ of Funds unallocated from 7 days ago, % change from 7 day to current",
     "gridPos": { "h": 2, "w": 3, "x": 11, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(sum by (vault) (yearn_vault{param=\"tvl\", experimental=\"false\", vault!~\"yvUSDC 0.2.2|yvDAI 0.2.2|yvWBTC 0.3.1|yvHEGIC 0.3.0\"}) * ((sum by (vault) (yearn_vault{param=\"totalAssets\", experimental=\"false\", vault!~\"yvUSDC 0.2.2|yvDAI 0.2.2|yvWBTC 0.3.1|yvHEGIC 0.3.0\"}))-(sum by (vault) (yearn_vault{param=\"totalDebt\", experimental=\"false\", vault!~\"yvUSDC 0.2.2|yvDAI 0.2.2|yvWBTC 0.3.1|yvHEGIC 0.3.0\"}))) / (sum by (vault) (yearn_vault{param=\"totalAssets\", experimental=\"false\", vault!~\"yvUSDC 0.2.2|yvDAI 0.2.2|yvWBTC 0.3.1|yvHEGIC 0.3.0\"}) )) / sum((yearn_vault{param=\"tvl\", experimental=\"false\", vault!~\"yvUSDC 0.2.2|yvDAI 0.2.2|yvWBTC 0.3.1|yvHEGIC 0.3.0\"})) ",
       "legendFormat": "Unallocated TVL %"
      },
      {
       "expr": "sum(sum by (vault) (yearn_vault{param=\"tvl\", experimental=\"false\", vault!~\"yvUSDC 0.2.2|yvDAI 0.2.2|yvWBTC 0.3.1|yvHEGIC 0.3.0\"}) * ((sum by (vault) (yearn_vault{param=\"totalAssets\", experimental=\"false\", vault!~\"yvUSDC 0.2.2|yvDAI 0.2.2|yvWBTC 0.3.1|yvHEGIC 0.3.0\"}))-(sum by (vault) (yearn_vault{param=\"totalDebt\", experimental=\"false\", vault!~\"yvUSDC 0.2.2|yvDAI 0.2.2|yvWBTC 0.3.1|yvHEGIC 0.3.0\"}))) / (sum by (vault) (yearn_vault{param=\"totalAssets\", experimental=\"false\", vault!~\"yvUSDC 0.2.2|yvDAI 0.2.2|yvWBTC 0.3.1|yvHEGIC 0.3.0\"}) )) / sum((yearn_vault{param=\"tvl\", experimental=\"false\", vault!~\"yvUSDC 0.2.2|yvDAI 0.2.2|yvWBTC 0.3.1|yvHEGIC 0.3.0\"})) offset 7d",
       "legendFormat": "Unallocated TVL % 7 day offset"
      }
     ]
    },
    {
     "title": "Δ Avg APY",
     "type": "stat",
     "description": "Avg summed apy for all production vaults. This is with weekly compunding taking the share price difference over a week from 7 days ago,  % change from 7 day to current",
     "gridPos": { "h": 2, "w": 3, "x": 15, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "avg((((delta(yearn_vault{param=\"pricePerShare\", experimental=\"false\", vault!~\"yvUSDC 0.2.2|yvDAI 0.2.2|yvWBTC 0.3.1|yvHEGIC 0.3.0\"}[7d]) + 1) ^ (1/7)) ^ 365 - 1) < 1000)",
       "legendFormat": "APY (avg) (%) "
      },
      {
       "expr": "avg((((delta(yearn_vault{param=\"pricePerShare\", experimental=\"false\", vault!~\"yvUSDC 0.2.2|yvDAI 0.2.2|yvWBTC 0.3.1|yvHEGIC 0.3.0\"}[7d]) + 1) ^ (1/7)) ^ 365 - 1) < 1000) offset 7d",
       "legendFormat": "APY (avg) (%)  7d"
      }
     ]
    },
    {
     "title": "Δ σ APY",
     "type": "stat",
     "description": "Standard deviation from 7 days ago,  % change from 7 day to current",
     "gridPos": { "h": 2, "w": 3, "x": 19, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "stddev((((delta(yearn_vault{param=\"pricePerShare\", experimental=\"false\", vault!~\"yvUSDC 0.2.2|yvDAI 0.2.2|yvWBTC 0.3.1|yvHEGIC 0.3.0\"}[7d]) + 1) ^ (1/7)) ^ 365 - 1) < 1000)",
       "legendFormat": "APY (std)"
      },
      {
       "expr": "stddev((((delta(yearn_vault{param=\"pricePerShare\", experimental=\"false\", vault!~\"yvUSDC 0.2.2|yvDAI 0.2.2|yvWBTC 0.3.1|yvHEGIC 0.3.0\"}[7d]) + 1) ^ (1/7)) ^ 365 - 1) < 1000) offset 7d",
       "legendFormat": "APY (std) 7 day"
      }
     ]
    }
   ]
  },
  {
   "title": "Δ Over Time Range Selected",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "collapsed": true,
   "panels": [
    {
     "title": "TVL ($)",
     "type": "stat",
     "description": "$ of Funds unallocated from time range selected",
     "gridPos": { "h": 3, "w": 3, "x": 3, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(sum by (vault) (yearn_vault{param=\"tvl\", experimental=\"false\", vault!~\"yvUSDC 0.2.2|yvDAI 0.2.2|yvWBTC 0.3.1|yvHEGIC 0.3.0\"})) offset $__range",
       "legendFormat": "Unallocated TVL ($)"
      }
     ]
    },
    {
     "title": "Unallocated TVL ($)",
     "type": "stat",
     "description": "$ of Funds unallocated from time range selected",
     "gridPos": { "h": 3, "w": 3, "x": 7, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(sum by (vault) (yearn_vault{param=\"tvl\", experimental=\"false\", vault!~\"yvUSDC 0.2.2|yvDAI 0.2.2|yvWBTC 0.3.1|yvHEGIC 0.3.0\"}) * ((sum by (vault) (yearn_vault{param=\"totalAssets\", experimental=\"false\", vault!~\"yvUSDC 0.2.2|yvDAI 0.2.2|yvWBTC 0.3.1|yvHEGIC 0.3.0\"})-(sum by (vault) (yearn_vault{param=\"totalDebt\", experimental=\"false\", vault!~\"yvUSDC 0.2.2|yvDAI 0.2.2|yvWBTC 0.3.1|yvHEGIC 0.3.0\"}))) / (sum by (vault) (yearn_vault{param=\"totalAssets\", experimental=\"false\", vault!~\"yvUSDC 0.2.2|yvDAI 0.2.2|yvWBTC 0.3.1|yvHEGIC 0.3.0\"}) ))) offset $__range",
       "legendFormat": "Unallocated TVL ($)"
      }
     ]
    },
    {
     "title": "Unallocated TVL (%)",
     "type": "stat",
     "description": "% of Funds unallocated from time range selected",
     "gridPos": { "h": 3, "w": 3, "x": 11, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(sum by (vault) (yearn_vault{param=\"tvl\", experimental=\"false\", vault!~\"yvUSDC 0.2.2|yvDAI 0.2.2|yvWBTC 0.3.1|yvHEGIC 0.3.0\"}) * ((sum by (vault) (yearn_vault{param=\"totalAssets\", experimental=\"false\", vault!~\"yvUSDC 0.2.2|yvDAI 0.2.2|yvWBTC 0.3.1|yvHEGIC 0.3.0\"}))-(sum by (vault) (yearn_vault{param=\"totalDebt\", experimental=\"false\", vault!~\"yvUSDC 0.2.2|yvDAI 0.2.2|yvWBTC 0.3.1|yvHEGIC 0.3.0\"}))) / (sum by (vault) (yearn_vault{param=\"totalAssets\", experimental=\"false\", vault!~\"yvUSDC 0.2.2|yvDAI 0.2.2|yvWBTC 0.3.1|yvHEGIC 0.3.0\"}) )) / sum((yearn_vault{param=\"tvl\", experimental=\"false\", vault!~\"yvUSDC 0.2.2|yvDAI 0.2.2|yvWBTC 0.3.1|yvHEGIC 0.3.0\"})) offset $__range",
       "legendFormat": "Unallocated TVL (%)"
      }
     ]
    },
    {
     "title": "Avg APY",
     "type": "stat",
     "description": "Avg summed apy for all production vaults. This is with weekly compounding taking the share price difference over a week from time range selected.",
     "gridPos": { "h": 3, "w": 3, "x": 15, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "avg((((delta(yearn_vault{param=\"pricePerShare\", experimental=\"false\", vault!~\"yvUSDC 0.2.2|yvDAI 0.2.2|yvWBTC 0.3.1|yvHEGIC 0.3.0\"}[7d]) + 1) ^ (1/7)) ^ 365 - 1) < 1000) offset $__range",
       "legendFormat": "APY (avg) (%)"
      }
     ]
    },
    {
     "title": "σ APY",
     "type": "stat",
     "description": "Standard deviation from time range selected",
     "gridPos": { "h": 3, "w": 3, "x": 19, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "stddev((((delta(yearn_vault{param=\"pricePerShare\", experimental=\"false\", vault!~\"yvUSDC 0.2.2|yvDAI 0.2.2|yvWBTC 0.3.1|yvHEGIC 0.3.0\"}[7d]) + 1) ^ (1/7)) ^ 365 - 1) < 1000) offset $__range",
       "legendFormat": "APY (std)"
      }
     ]
    },
    {
     "title": "Δ TVL ($)",
     "type": "stat",
     "description": "% of TVL from 7 days ago,  % change from time range selected to current",
     "gridPos": { "h": 2, "w": 3, "x": 3, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(sum by (vault) (yearn_vault{param=\"tvl\", experimental=\"false\", vault!~\"yvUSDC 0.2.2|yvDAI 0.2.2|yvWBTC 0.3.1|yvHEGIC 0.3.0\"}))",
       "legendFormat": "Unallocated TVL (%) "
      },
      {
       "expr": "sum(sum by (vault) (yearn_vault{param=\"tvl\", experimental=\"false\", vault!~\"yvUSDC 0.2.2|yvDAI 0.2.2|yvWBTC 0.3.1|yvHEGIC 0.3.0\"})) offset $__range",
       "legendFormat": "Unallocated TVL (%) 7 day"
      }
     ]
    },
    {
     "title": "Δ Unallocated TVL %",
     "type": "stat",
     "description": "$ of Funds unallocated from time range selected, % change from time range selected to current",
     "gridPos": { "h": 2, "w": 3, "x": 7, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(sum by (vault) (yearn_vault{param=\"tvl\", experimental=\"false\", vault!~\"yvUSDC 0.2.2|yvDAI 0.2.2|yvWBTC 0.3.1|yvHEGIC 0.3.0\"}) * ((sum by (vault) (yearn_vault{param=\"totalAssets\", experimental=\"false\", vault!~\"yvUSDC 0.2.2|yvDAI 0.2.2|yvWBTC 0.3.1|yvHEGIC 0.3.0\"})-(sum by (vault) (yearn_vault{param=\"totalDebt\", experimental=\"false\", vault!~\"yvUSDC 0.2.2|yvDAI 0.2.2|yvWBTC 0.3.1|yvHEGIC 0.3.0\"}))) / (sum by (vault) (yearn_vault{param=\"totalAssets\", experimental=\"false\", vault!~\"yvUSDC 0.2.2|yvDAI 0.2.2|yvWBTC 0.3.1|yvHEGIC 0.3.0\"}) )))",
       "legendFormat": "Unallocated TVL %"
      },
      {
       "expr": "sum(sum by (vault) (yearn_vault{param=\"tvl\", experimental=\"false\", vault!~\"yvUSDC 0.2.2|yvDAI 0.2.2|yvWBTC 0.3.1|yvHEGIC 0.3.0\"}) * ((sum by (vault) (yearn_vault{param=\"totalAssets\", experimental=\"false\", vault!~\"yvUSDC 0.2.2|yvDAI 0.2.2|yvWBTC 0.3.1|yvHEGIC 0.3.0\"})-(sum by (vault) (yearn_vault{param=\"totalDebt\", experimental=\"false\", vault!~\"yvUSDC 0.2.2|yvDAI 0.2.2|yvWBTC 0.3.1|yvHEGIC 0.3.0\"}))) / (sum by (vault) (yearn_vault{param=\"totalAssets\", experimental=\"false\", vault!~\"yvUSDC 0.2.2|yvDAI 0.2.2|yvWBTC 0.3.1|yvHEGIC 0.3.0\"}) ))) offset $__range",
       "legendFormat": "Unallocated TVL % 7 day offset"
      }
     ]
    },
    {
     "title": "Δ Unallocated TVL %",
     "type": "stat",
     "description": "$ of Funds unallocated from time range selected, % change from time range selected to current",
     "gridPos": { "h": 2, "w": 3, "x": 11, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(sum by (vault) (yearn_vault{param=\"tvl\", experimental=\"false\", vault!~\"yvUSDC 0.2.2|yvDAI 0.2.2|yvWBTC 0.3.1|yvHEGIC 0.3.0\"}) * ((sum by (vault) (yearn_vault{param=\"totalAssets\", experimental=\"false\", vault!~\"yvUSDC 0.2.2|yvDAI 0.2.2|yvWBTC 0.3.1|yvHEGIC 0.3.0\"}))-(sum by (vault) (yearn_vault{param=\"totalDebt\", experimental=\"false\", vault!~\"yvUSDC 0.2.2|yvDAI 0.2.2|yvWBTC 0.3.1|yvHEGIC 0.3.0\"}))) / (sum by (vault) (yearn_vault{param=\"totalAssets\", experimental=\"false\", vault!~\"yvUSDC 0.2.2|yvDAI 0.2.2|yvWBTC 0.3.1|yvHEGIC 0.3.0\"}) )) / sum((yearn_vault{param=\"tvl\", experimental=\"false\", vault!~\"yvUSDC 0.2.2|yvDAI 0.2.2|yvWBTC 0.3.1|yvHEGIC 0.3.0\"})) ",
       "legendFormat": "Unallocated TVL %"
      },
      {
       "expr": "sum(sum by (vault) (yearn_vault{param=\"tvl\", experimental=\"false\", vault!~\"yvUSDC 0.2.2|yvDAI 0.2.2|yvWBTC 0.3.1|yvHEGIC 0.3.0\"}) * ((sum by (vault) (yearn_vault{param=\"totalAssets\", experimental=\"false\", vault!~\"yvUSDC 0.2.2|yvDAI 0.2.2|yvWBTC 0.3.1|yvHEGIC 0.3.0\"}))-(sum by (vault) (yearn_vault{param=\"totalDebt\", experimental=\"false\", vault!~\"yvUSDC 0.2.2|yvDAI 0.2.2|yvWBTC 0.3.1|yvHEGIC 0.3.0\"}))) / (sum by (vault) (yearn_vault{param=\"totalAssets\", experimental=\"false\", vault!~\"yvUSDC 0.2.2|yvDAI 0.2.2|yvWBTC 0.3.1|yvHEGIC 0.3.0\"}) )) / sum((yearn_vault{param=\"tvl\", experimental=\"false\", vault!~\"yvUSDC 0.2.2|yvDAI 0.2.2|yvWBTC 0.3.1|yvHEGIC 0.3.0\"})) offset $__range",
       "legendFormat": "Unallocated TVL % 7 day offset"
      }
     ]
    },
    {
     "title": "Δ Avg APY",
     "type": "stat",
     "description": "Avg summed apy for all production vaults. This is with weekly compunding taking the share price difference over a week from time range selected,  % change from time range selected to current",
     "gridPos": { "h": 2, "w": 3, "x": 15, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "avg((((delta(yearn_vault{param=\"pricePerShare\", experimental=\"false\", vault!~\"yvUSDC 0.2.2|yvDAI 0.2.2|yvWBTC 0.3.1|yvHEGIC 0.3.0\"}[7d]) + 1) ^ (1/7)) ^ 365 - 1) < 1000)",
       "legendFormat": "APY (avg) (%) "
      },
      {
       "expr": "avg((((delta(yearn_vault{param=\"pricePerShare\", experimental=\"false\", vault!~\"yvUSDC 0.2.2|yvDAI 0.2.2|yvWBTC 0.3.1|yvHEGIC 0.3.0\"}[7d]) + 1) ^ (1/7)) ^ 365 - 1) < 1000) offset $__range",
       "legendFormat": "APY (avg) (%)  7d"
      }
     ]
    },
    {
     "title": "Δ σ APY",
     "type": "stat",
     "description": "Standard deviation from time range selected,  % change from time range selected to current",
     "gridPos": { "h": 2, "w": 3, "x": 19, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "stddev((((delta(yearn_vault{param=\"pricePerShare\", experimental=\"false\", vault!~\"yvUSDC 0.2.2|yvDAI 0.2.2|yvWBTC 0.3.1|yvHEGIC 0.3.0\"}[7d]) + 1) ^ (1/7)) ^ 365 - 1) < 1000)",
       "legendFormat": "APY (std)"
      },
      {
       "expr": "stddev((((delta(yearn_vault{param=\"pricePerShare\", experimental=\"false\", vault!~\"yvUSDC 0.2.2|yvDAI 0.2.2|yvWBTC 0.3.1|yvHEGIC 0.3.0\"}[7d]) + 1) ^ (1/7)) ^ 365 - 1) < 1000) offset $__range",
       "legendFormat": "APY (std) 7 day"
      }
     ]
    }
   ]
  },
  { "title": "Graphs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "Unallocated TVL ($)",
   "type": "timeseries",
   "description": "Unalllocated tvl > 35m",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "expr": "sum(sum by (vault) (yearn_vault{param=\"tvl\", experimental=\"false\", vault!~\"yvUSDC 0.2.2|yvDAI 0.2.2|yvWBTC 0.3.1|yvHEGIC 0.3.0\"}) * ((sum by (vault) (yearn_vault{param=\"totalAssets\", experimental=\"false\", vault!~\"yvUSDC 0.2.2|yvDAI 0.2.2|yvWBTC 0.3.1|yvHEGIC 0.3.0\"})-(sum by (vault) (yearn_vault{param=\"totalDebt\", experimental=\"false\", vault!~\"yvUSDC 0.2.2|yvDAI 0.2.2|yvWBTC 0.3.1|yvHEGIC 0.3.0\"}))) / (sum by (vault) (yearn_vault{param=\"totalAssets\", experimental=\"false\", vault!~\"yvUSDC 0.2.2|yvDAI 0.2.2|yvWBTC 0.3.1|yvHEGIC 0.3.0\"}) )))",
     "legendFormat": "Unallocated TVL ($)"
    }
   ]
  },
  {
   "title": "Unallocated TVL (%)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(sum by (vault) (yearn_vault{param=\"tvl\", experimental=\"false\", vault!~\"yvUSDC 0.2.2|yvDAI 0.2.2|yvWBTC 0.3.1|yvHEGIC 0.3.0\"}) * ((sum by (vault) (yearn_vault{param=\"totalAssets\", experimental=\"false\", vault!~\"yvUSDC 0.2.2|yvDAI 0.2.2|yvWBTC 0.3.1|yvHEGIC 0.3.0\"}))-(sum by (vault) (yearn_vault{param=\"totalDebt\", experimental=\"false\", vault!~\"yvUSDC 0.2.2|yvDAI 0.2.2|yvWBTC 0.3.1|yvHEGIC 0.3.0\"}))) / (sum by (vault) (yearn_vault{param=\"totalAssets\", experimental=\"false\", vault!~\"yvUSDC 0.2.2|yvDAI 0.2.2|yvWBTC 0.3.1|yvHEGIC 0.3.0\"}) )) / sum((yearn_vault{param=\"tvl\", experimental=\"false\", vault!~\"yvUSDC 0.2.2|yvDAI 0.2.2|yvWBTC 0.3.1|yvHEGIC 0.3.0\"}))",
     "legendFormat": "Unallocated TVL (%)"
    }
   ]
  },
  {
   "title": "TVL ($)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "expr": "sum(sum by (vault) (yearn_vault{param=\"tvl\", experimental=\"false\", vault!~\"yvUSDC 0.2.2|yvDAI 0.2.2|yvWBTC 0.3.1|yvHEGIC 0.3.0\"}))",
     "legendFormat": "TVL ($) - Total"
    },
    {
     "expr": "sum(sum by (vault) (yearn_vault{network=\"ETH\", param=\"tvl\", experimental=\"false\", vault!~\"yvUSDC 0.2.2|yvDAI 0.2.2|yvWBTC 0.3.1|yvHEGIC 0.3.0\"}))",
     "legendFormat": "TVL ($) - ETH"
    },
    {
     "expr": "sum(sum by (vault) (yearn_vault{network=\"FTM\", param=\"tvl\", experimental=\"false\"}))",
     "legendFormat": "TVL ($) - FTM"
    }
   ]
  },
  {
   "title": "Avg APY",
   "type": "graph",
   "description": "Avg summed apy for all production vaults. This is with weekly compunding taking the share price difference over a week. ",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "avg((((delta(yearn_vault{param=\"pricePerShare\", experimental=\"false\", vault!~\"yvUSDC 0.2.2|yvDAI 0.2.2|yvWBTC 0.3.1|yvHEGIC 0.3.0\"}[7d]) + 1) ^ (1/7)) ^ 365 - 1) < 1000)",
     "legendFormat": "APY (avg) (%)"
    },
    {
     "expr": "stddev((((delta(yearn_vault{param=\"pricePerShare\", experimental=\"false\", vault!~\"yvUSDC 0.2.2|yvDAI 0.2.2|yvWBTC 0.3.1|yvHEGIC 0.3.0\"}[7d]) + 1) ^ (1/7)) ^ 365 - 1) < 1000)",
     "legendFormat": "APY (std - σ)"
    }
   ]
  },
  {
   "title": "Strategy Debt Allocation by Vault",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 },
   "collapsed": true,
   "panels": [
    {
     "title": "Total Debt Allocation - ETH",
     "type": "timeseries",
     "gridPos": { "h": 17, "w": 24, "x": 0, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "(avg by (vault) (yearn_vault{param=\"totalDebt\", experimental=\"false\", vault!~\"yvUSDC 0.2.2|yvDAI 0.2.2|yvWBTC 0.3.1|yvHEGIC 0.3.0\", network=\"ETH\"}) / avg by (vault) (yearn_vault{param=\"totalAssets\", experimental=\"false\", vault!~\"yvUSDC 0.2.2|yvDAI 0.2.2|yvWBTC 0.3.1|yvHEGIC 0.3.0\", network=\"ETH\"}) )",
       "legendFormat": "{{vault}}"
      }
     ]
    },
    {
     "title": "Total Debt Allocation - FTM",
     "type": "timeseries",
     "gridPos": { "h": 17, "w": 24, "x": 0, "y": 43 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "(avg by (vault) (yearn_vault{param=\"totalDebt\", experimental=\"false\", vault!~\"yvAVAX 0.4.3\", network=\"FTM\"}) / avg by (vault) (yearn_vault{param=\"totalAssets\", experimental=\"false\", vault!~\"yvAVAX 0.4.3\", network=\"FTM\"}) )",
       "legendFormat": "{{vault}}"
      }
     ]
    }
   ]
  }
 ]
}