{
 "title": "Vault Overview",
 "description": "Look up individual vault stats here",
 "tags": [
  "yVault",
  "Version 2",
  "Production"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "vaults",
    "label": "vaults",
    "query": {
     "query": "yearn_strategy{network=\"ETH\", experimental=\"false\"}"
    }
   }
  ]
 },
 "panels": [
  { "title": "Strategies", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "$vaults Strategies",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(yearn_strategy{network=\"ETH\", vault=\"$vaults\", param=\"isActive\"})",
     "legendFormat": "{{strategy}}"
    }
   ]
  },
  {
   "title": "$vaults Strategies Active",
   "type": "stat",
   "gridPos": { "h": 4, "w": 22, "x": 2, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "yearn_strategy{network=\"ETH\", vault=\"$vaults\", param=\"isActive\"} > 0",
     "legendFormat": "{{strategy}}"
    }
   ]
  },
  {
   "title": "$vaults Strategies - Inactive",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(yearn_strategy{network=\"ETH\", vault=\"$vaults\", param=\"isActive\"} < 0.1)",
     "legendFormat": "{{strategy}}"
    }
   ]
  },
  {
   "title": "$vaults Strategies Inactive",
   "type": "stat",
   "gridPos": { "h": 3, "w": 22, "x": 2, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "yearn_strategy{network=\"ETH\", vault=\"$vaults\", param=\"isActive\"} < 0.1",
     "legendFormat": "{{strategy}}"
    }
   ]
  },
  { "title": "Assets", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "totalAssets",
   "type": "stat",
   "description": "Total amount of Deposit tokens in vault",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "yearn_vault{network=\"ETH\", param=\"totalAssets\", vault=~\"$vaults\"}",
     "legendFormat": "{{param}}"
    }
   ]
  },
  {
   "title": "totalAssets ($)",
   "type": "stat",
   "description": "The total amount of Deposit tokens in the vault in dollars",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "yearn_vault{network=\"ETH\", param=\"tvl\", vault=~\"$vaults\"}",
     "legendFormat": "{{param}}"
    }
   ]
  },
  {
   "title": "totalDebt",
   "type": "stat",
   "description": "The total amount of underlying allocated to strategies.",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(yearn_strategy{network=\"ETH\", param=\"totalDebt\", vault=~\"$vaults\"})",
     "legendFormat": "{{param}}"
    }
   ]
  },
  {
   "title": "totalGain",
   "type": "stat",
   "description": "Sum of the total amount of gain from all strategies in underlying token.",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(yearn_strategy{network=\"ETH\", param=\"totalGain\", vault=~\"$vaults\"})",
     "legendFormat": "{{param}}"
    }
   ]
  },
  {
   "title": "totalLoss",
   "type": "stat",
   "description": "Sum of all losses actualized from all strategies in underlying token terms",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "yearn_strategy{network=\"ETH\", param=\"totalLoss\", vault=~\"$vaults\"}",
     "legendFormat": "{{param}}"
    }
   ]
  },
  {
   "title": "% to Deposit Limit",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "yearn_vault{network=\"ETH\", param=\"totalAssets\", vault=\"$vaults\"} / on(vault,version) yearn_vault{network=\"ETH\", param=\"depositLimit\", vault=\"$vaults\"}",
     "legendFormat": "% to Limit"
    }
   ]
  },
  {
   "title": "Share Price",
   "type": "stat",
   "description": "Share price of Vault token",
   "gridPos": { "h": 4, "w": 8, "x": 4, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "yearn_vault{network=\"ETH\", param=\"pricePerShare\", vault=~\"$vaults\"}",
     "legendFormat": "{{param}}"
    }
   ]
  },
  {
   "title": "% of Assets Deployed",
   "type": "stat",
   "description": "totalDebt / totalAssets",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(yearn_strategy{network=\"ETH\", param=\"totalDebt\", vault=~\"$vaults\"}) / on(vault, version) sum(yearn_vault{network=\"ETH\", param=\"totalAssets\", vault=~\"$vaults\"})",
     "legendFormat": "% to Limit"
    }
   ]
  },
  {
   "title": "Deposit Limits",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "collapsed": true,
   "panels": [
    {
     "title": "Deposit Limit",
     "type": "graph",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 18 },
     "yaxes": [
      { "format": "short", "label": "Amount of Underlying Token" }
     ],
     "targets": [
      {
       "expr": "yearn_vault{network=\"ETH\", param=\"totalAssets\", vault=~\"$vaults\"}",
       "legendFormat": "Total Assets"
      },
      {
       "expr": "yearn_vault{network=\"ETH\", param=\"depositLimit\", vault=~\"$vaults\"}",
       "legendFormat": "Deposit Limit"
      },
      {
       "expr": "yearn_vault{network=\"ETH\", param=\"totalAssets\", vault=\"$vaults\"} / on(vault,version) yearn_vault{network=\"ETH\", param=\"depositLimit\", vault=\"$vaults\"}",
       "legendFormat": "% to Deposit Limit"
      }
     ]
    }
   ]
  },
  {
   "title": "Assets Graphs",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 },
   "collapsed": true,
   "panels": [
    {
     "title": "Strategy Allocations Overview",
     "type": "graph",
     "description": "Breakdown of assets in vault",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 4 },
     "yaxes": [
      { "format": "short", "label": "totalDebt - Strategies" }
     ],
     "targets": [
      {
       "expr": "yearn_vault{network=\"ETH\", param=\"totalAssets\", vault=~\"$vaults\"}",
       "legendFormat": "{{param}}"
      },
      {
       "expr": "yearn_strategy{network=\"ETH\", param=\"totalDebt\", vault=~\"$vaults\"} > 0",
       "legendFormat": "{{strategy}}"
      },
      {
       "expr": "sum(yearn_strategy{network=\"ETH\", param=\"totalDebt\", vault=~\"$vaults\"})",
       "legendFormat": "TotalDebt"
      }
     ]
    },
    {
     "title": "totalDebt",
     "type": "graph",
     "description": "Total amount of Deposit tokens in strategy",
     "gridPos": { "h": 9, "w": 16, "x": 0, "y": 13 },
     "yaxes": [
      {
       "format": "short",
       "label": "TotalDebt (Assets) in Strategies"
      }
     ],
     "targets": [
      {
       "expr": "sort(yearn_strategy{network=\"ETH\", param=\"totalDebt\", vault=~\"$vaults\"} > 0 )",
       "legendFormat": "{{strategy}}"
      }
     ]
    },
    {
     "title": "Strategy Allocations Overview",
     "type": "piechart",
     "description": "Breakdown of assets in vault",
     "gridPos": { "h": 9, "w": 8, "x": 16, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sort_desc(yearn_strategy{network=\"ETH\", param=\"totalDebt\", vault=~\"$vaults\"} > 0)",
       "legendFormat": "{{strategy}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Assets Delta",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 },
   "collapsed": true,
   "panels": [
    {
     "title": "TVL- 1D change",
     "type": "stat",
     "gridPos": { "h": 3, "w": 4, "x": 0, "y": 29 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "yearn_vault{network=\"ETH\", param=\"tvl\", vault=~\"$vaults\"} - yearn_vault{network=\"ETH\", param=\"tvl\", vault=~\"$vaults\"} offset 1d",
       "legendFormat": "{{vault}}"
      }
     ]
    },
    {
     "title": "TVL - 1D % change",
     "type": "stat",
     "gridPos": { "h": 3, "w": 4, "x": 4, "y": 29 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "(yearn_vault{network=\"ETH\", param=\"tvl\", vault=~\"$vaults\"} / yearn_vault{network=\"ETH\", param=\"tvl\", vault=~\"$vaults\"} offset 1d ) - 1",
       "legendFormat": "{{vault}}"
      }
     ]
    },
    {
     "title": "totalDebt - 1D change",
     "type": "stat",
     "gridPos": { "h": 3, "w": 4, "x": 8, "y": 29 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(yearn_strategy{network=\"ETH\", param=\"totalDebt\", vault=~\"$vaults\"}) - sum(yearn_strategy{network=\"ETH\", param=\"totalDebt\", vault=~\"$vaults\"} offset 1d)",
       "legendFormat": "{{strategy}}"
      }
     ]
    },
    {
     "title": "totalDebt - 1D % change",
     "type": "stat",
     "gridPos": { "h": 3, "w": 4, "x": 12, "y": 29 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "(sum(yearn_strategy{network=\"ETH\", param=\"totalDebt\", vault=~\"$vaults\"}) / sum(yearn_strategy{network=\"ETH\", param=\"totalDebt\", vault=~\"$vaults\"} offset 1d)) - 1",
       "legendFormat": "{{vault}}"
      }
     ]
    },
    {
     "title": "totalLoss - 1D change",
     "type": "stat",
     "gridPos": { "h": 3, "w": 4, "x": 16, "y": 29 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(yearn_strategy{network=\"ETH\", param=\"totalLoss\", vault=~\"$vaults\"}) - sum(yearn_strategy{network=\"ETH\", param=\"totalLoss\", vault=~\"$vaults\"} offset 1d)",
       "legendFormat": "{{strategy}}"
      }
     ]
    },
    {
     "title": "totalLoss - 1D % change",
     "type": "stat",
     "gridPos": { "h": 3, "w": 4, "x": 20, "y": 29 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "(sum(yearn_strategy{network=\"ETH\", param=\"totalLoss\", vault=~\"$vaults\"}) / sum(yearn_strategy{network=\"ETH\", param=\"totalLoss\", vault=~\"$vaults\"} offset 1d)) - 1",
       "legendFormat": "{{vault}}"
      }
     ]
    },
    {
     "title": "TVL- 7D change",
     "type": "stat",
     "gridPos": { "h": 3, "w": 4, "x": 0, "y": 32 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "yearn_vault{network=\"ETH\", param=\"tvl\", vault=~\"$vaults\"} - yearn_vault{network=\"ETH\", param=\"tvl\", vault=~\"$vaults\"} offset 7d",
       "legendFormat": "{{vault}}"
      }
     ]
    },
    {
     "title": "TVL - 7D % change",
     "type": "stat",
     "gridPos": { "h": 3, "w": 4, "x": 4, "y": 32 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "(yearn_vault{network=\"ETH\", param=\"tvl\", vault=~\"$vaults\"} / yearn_vault{network=\"ETH\", param=\"tvl\", vault=~\"$vaults\"} offset 7d ) - 1",
       "legendFormat": "{{vault}}"
      }
     ]
    },
    {
     "title": "totalDebt - 7D change",
     "type": "stat",
     "gridPos": { "h": 3, "w": 4, "x": 8, "y": 32 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(yearn_strategy{network=\"ETH\", param=\"totalDebt\", vault=~\"$vaults\"}) - sum(yearn_strategy{network=\"ETH\", param=\"totalDebt\", vault=~\"$vaults\"} offset 7d)",
       "legendFormat": "{{strategy}}"
      }
     ]
    },
    {
     "title": "totalDebt - 7D % change",
     "type": "stat",
     "gridPos": { "h": 3, "w": 4, "x": 12, "y": 32 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "(sum(yearn_strategy{network=\"ETH\", param=\"totalDebt\", vault=~\"$vaults\"}) / sum(yearn_strategy{network=\"ETH\", param=\"totalDebt\", vault=~\"$vaults\"} offset 7d)) - 1",
       "legendFormat": "{{vault}}"
      }
     ]
    },
    {
     "title": "totalLoss - 7D change",
     "type": "stat",
     "gridPos": { "h": 3, "w": 4, "x": 16, "y": 32 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(yearn_strategy{network=\"ETH\", param=\"totalLoss\", vault=~\"$vaults\"}) - sum(yearn_strategy{network=\"ETH\", param=\"totalLoss\", vault=~\"$vaults\"} offset 7d)",
       "legendFormat": "{{strategy}}"
      }
     ]
    },
    {
     "title": "totalLoss - 7D % change",
     "type": "stat",
     "gridPos": { "h": 3, "w": 4, "x": 20, "y": 32 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "(sum(yearn_strategy{network=\"ETH\", param=\"totalLoss\", vault=~\"$vaults\"}) / sum(yearn_strategy{network=\"ETH\", param=\"totalLoss\", vault=~\"$vaults\"} offset 7d)) - 1",
       "legendFormat": "{{vault}}"
      }
     ]
    },
    {
     "title": "Total Gain",
     "type": "graph",
     "description": "Total amount of Deposit tokens in strategy",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 35 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "yearn_strategy{network=\"ETH\", param=\"totalGain\", vault=~\"$vaults\"}",
       "legendFormat": "{{strategy}}"
      },
      {
       "expr": "sum(yearn_strategy{network=\"ETH\", param=\"totalGain\", vault=~\"$vaults\"})",
       "legendFormat": "totalGain"
      }
     ]
    },
    {
     "title": "Total Gain Delta",
     "type": "graph",
     "description": "Rate of increase of totalGain for strategies",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 35 },
     "yaxes": [
      { "format": "short", "label": "Rate of increase" }
     ],
     "targets": [
      {
       "expr": "delta(yearn_strategy{network=\"ETH\", param=\"totalGain\", vault=~\"$vaults\"}[5m])",
       "legendFormat": "{{strategy}}"
      }
     ]
    },
    {
     "title": "Total loss",
     "type": "graph",
     "description": "totalLoss per strategy ",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 44 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "yearn_strategy{network=\"ETH\", param=\"totalLoss\", vault=~\"$vaults\"}",
       "legendFormat": "{{strategy}}"
      },
      {
       "expr": "sum(yearn_strategy{network=\"ETH\", param=\"totalLoss\", vault=~\"$vaults\"})",
       "legendFormat": "totalLoss"
      }
     ]
    },
    {
     "title": "Total Loss Delta",
     "type": "graph",
     "description": "Rate of change of totalLoss per strategy 5m delta",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 44 },
     "yaxes": [
      { "format": "short", "label": "Rate of increase" }
     ],
     "targets": [
      {
       "expr": "delta(yearn_strategy{network=\"ETH\", param=\"totalLoss\", vault=~\"$vaults\"}[5m])",
       "legendFormat": "{{strategy}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Assets Delta Extra",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 },
   "collapsed": true,
   "panels": [
    {
     "title": "Total Gain - Loss ",
     "type": "graph",
     "description": "Total amount of Gain - Loss ",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 24 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by (strategy) (yearn_strategy{network=\"ETH\", param=~\"totalGain\", vault=~\"$vaults\"}) - sum by (strategy) (yearn_strategy{network=\"ETH\", param=\"totalLoss\", vault=~\"$vaults\"})",
       "legendFormat": "{{strategy}}"
      }
     ]
    },
    {
     "title": "Total Gain - Loss Delta",
     "type": "graph",
     "description": "Rate of change of total 5m delta",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 24 },
     "yaxes": [
      { "format": "short", "label": "Rate of increase" }
     ],
     "targets": [
      {
       "expr": "sum by (strategy) (delta(yearn_strategy{network=\"ETH\", param=~\"totalGain\", vault=~\"$vaults\"}[5m])) - sum by (strategy) (delta(yearn_strategy{network=\"ETH\", param=\"totalLoss\", vault=~\"$vaults\"}[5m]))",
       "legendFormat": "{{strategy}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Harvest",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 },
   "collapsed": true,
   "panels": [
    {
     "title": "Last Harvest",
     "type": "stat",
     "gridPos": { "h": 4, "w": 24, "x": 0, "y": 55 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "time() - (yearn_strategy{network=\"ETH\", param=\"lastReport\", vault=~\"$vaults\"})",
       "legendFormat": "{{strategy}}"
      }
     ]
    },
    {
     "title": "share price",
     "type": "stat",
     "gridPos": { "h": 3, "w": 12, "x": 0, "y": 59 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "yearn_vault{network=\"ETH\", param=\"pricePerShare\", vault=~\"$vaults\"}",
       "legendFormat": "{{vault}}"
      }
     ]
    },
    {
     "title": "Share Price- 1D change",
     "type": "stat",
     "gridPos": { "h": 3, "w": 6, "x": 12, "y": 59 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "yearn_vault{network=\"ETH\", param=\"pricePerShare\", vault=~\"$vaults\"} - yearn_vault{network=\"ETH\", param=\"pricePerShare\", vault=~\"$vaults\"} offset 1d",
       "legendFormat": "{{vault}}"
      }
     ]
    },
    {
     "title": "Share Price - $vault - 1D % change",
     "type": "stat",
     "gridPos": { "h": 3, "w": 6, "x": 18, "y": 59 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "(yearn_vault{network=\"ETH\", param=\"pricePerShare\", vault=~\"$vaults\"} / yearn_vault{network=\"ETH\", param=\"pricePerShare\", vault=~\"$vaults\"} offset 1d ) - 1",
       "legendFormat": "{{vault}}"
      }
     ]
    },
    {
     "title": "minReportDelay",
     "type": "stat",
     "description": "Min amount of before Keepers can call harvest again",
     "gridPos": { "h": 5, "w": 12, "x": 0, "y": 62 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "yearn_strategy{network=\"ETH\", param=\"minReportDelay\", vault=~\"$vaults\"}",
       "legendFormat": "{{strategy}}"
      }
     ]
    },
    {
     "title": "maxReportDelay",
     "type": "stat",
     "description": "Keepers need to call Havest before this time. ",
     "gridPos": { "h": 5, "w": 12, "x": 12, "y": 62 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "yearn_strategy{network=\"ETH\", param=\"maxReportDelay\", vault=~\"$vaults\"}",
       "legendFormat": "{{strategy}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Static Variables",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 },
   "collapsed": true,
   "panels": [
    {
     "title": "Date Added ",
     "type": "stat",
     "description": "Activation Date",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "time() - yearn_strategy{network=\"ETH\", param=\"activation\", vault=~\"$vaults\"}",
       "legendFormat": "{{strategy}}"
      }
     ]
    },
    {
     "title": "Deposit Limit ",
     "type": "stat",
     "description": "availableDepositLimit",
     "gridPos": { "h": 4, "w": 3, "x": 2, "y": 28 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "yearn_vault{network=\"ETH\", param=\"availableDepositLimit\", vault=~\"$vaults\"}",
       "legendFormat": "{{param}}"
      }
     ]
    },
    {
     "title": "buffer",
     "type": "stat",
     "description": "Amount of funds to keep for withdrawals",
     "gridPos": { "h": 4, "w": 3, "x": 7, "y": 28 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "yearn_strategy{network=\"ETH\", param=\"buffer\", vault=~\"$vaults\"}/1000",
       "legendFormat": "{{param}}"
      }
     ]
    },
    {
     "title": "debtRatio Vault",
     "type": "stat",
     "description": "Vault debtRatio",
     "gridPos": { "h": 4, "w": 3, "x": 13, "y": 28 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "yearn_vault{network=\"ETH\", param=\"debtRatio\", vault=~\"$vaults\"}/100",
       "legendFormat": "{{param}}"
      }
     ]
    },
    {
     "title": "debtRatio Strategies",
     "type": "stat",
     "description": "Strategies debtRatio summed",
     "gridPos": { "h": 4, "w": 3, "x": 18, "y": 28 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(yearn_strategy{network=\"ETH\", param=\"debtRatio\", vault=~\"$vaults\"}/100)",
       "legendFormat": "{{strategy}}"
      }
     ]
    },
    {
     "title": "debtRatio  Strategies",
     "type": "stat",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 32 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "yearn_strategy{network=\"ETH\", param=\"debtRatio\", vault=~\"$vaults\"}/100 > 0",
       "legendFormat": "{{strategy}}"
      }
     ]
    },
    {
     "title": "debtThreshold",
     "type": "stat",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 37 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "yearn_strategy{network=\"ETH\", param=\"debtThreshold\", vault=~\"$vaults\"}/1000000000000000",
       "legendFormat": "{{strategy}}"
      }
     ]
    },
    {
     "title": "minDebtPerHarvest",
     "type": "stat",
     "description": "Min amount of allocatable funds per harvest",
     "gridPos": { "h": 5, "w": 12, "x": 0, "y": 42 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "yearn_strategy{network=\"ETH\", param=\"minDebtPerHarvest\", vault=~\"$vaults\"}",
       "legendFormat": "{{strategy}}"
      }
     ]
    },
    {
     "title": "maxDebtPerHarvest",
     "type": "stat",
     "description": "Max amount of allocatable funds per harvest",
     "gridPos": { "h": 5, "w": 12, "x": 12, "y": 42 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "yearn_strategy{network=\"ETH\", param=\"maxDebtPerHarvest\", vault=~\"$vaults\"}",
       "legendFormat": "{{strategy}}"
      }
     ]
    }
   ]
  },
  {
   "title": "CDP info",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 },
   "collapsed": true,
   "panels": [
    {
     "title": "CDP ID",
     "type": "stat",
     "description": "CDP ID ",
     "gridPos": { "h": 4, "w": 3, "x": 0, "y": 48 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "yearn_strategy{network=\"ETH\", param=\"cdpId\", vault=~\"$vaults\"}",
       "legendFormat": "{{param}}"
      }
     ]
    },
    {
     "title": "balanceOfmVault",
     "type": "stat",
     "gridPos": { "h": 4, "w": 6, "x": 3, "y": 48 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "yearn_strategy{network=\"ETH\", param=\"balanceOfmVault\", vault=~\"$vaults\"}/1000000000000000000",
       "legendFormat": "{{param}}"
      }
     ]
    },
    {
     "title": "C",
     "type": "stat",
     "gridPos": { "h": 4, "w": 3, "x": 9, "y": 48 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "yearn_strategy{network=\"ETH\", param=\"c\", vault=~\"$vaults\"}/100",
       "legendFormat": "{{param}}"
      }
     ]
    },
    {
     "title": "shouldDraw",
     "type": "stat",
     "description": "Stablecoin printer should go brrrr?",
     "gridPos": { "h": 4, "w": 3, "x": 12, "y": 48 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "yearn_strategy{network=\"ETH\", param=\"shouldDraw\", vault=~\"$vaults\"}",
       "legendFormat": "{{param}}"
      }
     ]
    },
    {
     "title": "shouldRepay",
     "type": "stat",
     "description": "Pay off debt to reach c ratio? ",
     "gridPos": { "h": 4, "w": 3, "x": 15, "y": 48 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "yearn_strategy{network=\"ETH\", param=\"shouldRepay\", vault=~\"$vaults\"}",
       "legendFormat": "{{param}}"
      }
     ]
    },
    {
     "title": "getTotalDebtAmount",
     "type": "graph",
     "description": "?",
     "gridPos": { "h": 8, "w": 6, "x": 18, "y": 48 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "yearn_strategy{network=\"ETH\", param=\"getTotalDebtAmount\", vault=~\"$vaults\"}/1000000000000000000",
       "legendFormat": "{{param}}"
      }
     ]
    },
    {
     "title": "getUnderlyingDai",
     "type": "stat",
     "description": "Amount of Dai minted",
     "gridPos": { "h": 4, "w": 3, "x": 0, "y": 52 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "yearn_strategy{network=\"ETH\", param=\"getUnderlyingDai\", vault=~\"$vaults\"}/1000000000000000000",
       "legendFormat": "{{param}}"
      }
     ]
    },
    {
     "title": "getTotalDebtAmount",
     "type": "stat",
     "description": "?",
     "gridPos": { "h": 4, "w": 6, "x": 3, "y": 52 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "yearn_strategy{network=\"ETH\", param=\"getTotalDebtAmount\", vault=~\"$vaults\"}/1000000000000000000",
       "legendFormat": "{{param}}"
      }
     ]
    },
    {
     "title": "C_Safe",
     "type": "stat",
     "gridPos": { "h": 4, "w": 3, "x": 9, "y": 52 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "yearn_strategy{network=\"ETH\", param=\"c_safe\", vault=~\"$vaults\"}/100",
       "legendFormat": "{{param}}"
      }
     ]
    },
    {
     "title": "drawAmount",
     "type": "stat",
     "description": "Amount of DAI to mint of the debt to keep the c ratio where we want it.",
     "gridPos": { "h": 4, "w": 3, "x": 12, "y": 52 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "yearn_strategy{network=\"ETH\", param=\"drawAmount\", vault=~\"$vaults\"}/1000000000000000000",
       "legendFormat": "{{param}}"
      }
     ]
    },
    {
     "title": "repayAmount",
     "type": "stat",
     "description": "Amount of debt to repay to keep c-ratio",
     "gridPos": { "h": 4, "w": 3, "x": 15, "y": 52 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "yearn_strategy{network=\"ETH\", param=\"repayAmount\", vault=~\"$vaults\"}/1000000000000000000",
       "legendFormat": "{{param}}"
      }
     ]
    },
    {
     "title": "balanceOfmVault",
     "type": "graph",
     "description": "Maker vault amount of collateral drawn",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 56 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "yearn_strategy{network=\"ETH\", param=\"balanceOfmVault\", vault=~\"$vaults\"}/1000000000000000",
       "legendFormat": "{{param}}"
      }
     ]
    },
    {
     "title": "repayAmount",
     "type": "graph",
     "description": "Amount to repay off the debt to keep c-ratio to the level we want it",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 56 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "yearn_strategy{network=\"ETH\", param=\"repayAmount\", vault=~\"$vaults\"}/10000000000000000",
       "legendFormat": "{{param}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Health Check",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 },
   "collapsed": true,
   "panels": [
    {
     "title": "doHealthCheck",
     "type": "graph",
     "description": "Is doHealthCheck True? If yes, harvest is trying to sell more want tokens than allowed. \nThis is a newer method not on all vaults.",
     "gridPos": { "h": 12, "w": 15, "x": 0, "y": 65 },
     "fieldConfig": { "defaults": { "unit": "bool_yes_no" } },
     "targets": [
      {
       "expr": "yearn_strategy{network=\"ETH\", param=\"doHealthCheck\", vault=~\"$vaults\"}",
       "legendFormat": "{{strategy}}"
      }
     ]
    },
    {
     "title": "Health Check Delta",
     "type": "graph",
     "description": "Rate of change of doHealthCheck per strategy. ",
     "gridPos": { "h": 12, "w": 9, "x": 15, "y": 65 },
     "targets": [
      {
       "expr": "delta(yearn_strategy{network=\"ETH\", param=\"doHealthCheck\", vault=~\"$vaults\"}[1h])",
       "legendFormat": "{{strategy}}"
      }
     ]
    }
   ]
  }
 ]
}