{
 "title": "veCRV",
 "time": { "from": "now-2y", "to": "now" },
 "panels": [
  {
   "title": "veCRV balance",
   "type": "timeseries",
   "gridPos": { "h": 16, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avg(yearn{param=\"vecrv balance\"})",
     "legendFormat": "veCRV balance"
    }
   ]
  },
  {
   "title": "% of total veCRV owned",
   "type": "timeseries",
   "gridPos": { "h": 16, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "avg(yearn{param=\"vecrv balance\"}) / avg(yearn{param=\"vecrv total\"})",
     "legendFormat": "% veCRV owned"
    }
   ]
  },
  {
   "title": "$ veCRV",
   "type": "timeseries",
   "gridPos": { "h": 16, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avg(yearn{network=\"ETH\", param=\"vecrv balance\"}) or vector(0) * yearn_vault{vault=\"yveCRV\", param=\"token price\"} or vector(0)",
     "legendFormat": "veCRV * CRV Price"
    }
   ]
  },
  {
   "title": "CRV price",
   "type": "timeseries",
   "description": "From yveCRV token price Vault.",
   "gridPos": { "h": 16, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "expr": "yearn_vault{vault=\"yveCRV\", param=\"token price\"}",
     "legendFormat": "crv price"
    }
   ]
  }
 ]
}