{
 "title": "Daily Cashflow Averages",
 "time": { "from": "now-2y", "to": "now" },
 "refresh": "5m",
 "panels": [
  {
   "title": "14-day averages",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "rawSql": "select *\nfrom (\n  SELECT\n    date as time,\n    sum(average_14d),\n    'Cash Out' as metric\n  FROM treasury_time_averages a\n  left join txgroups b on a.parent_txgroup_id = b.txgroup_id\n  left join txgroups c on b.parent_txgroup = c.txgroup_id\n  left join txgroups d on c.parent_txgroup = d.txgroup_id\n  left join txgroups e on d.parent_txgroup = e.txgroup_id\n  WHERE\n    $__timeFilter(date) and\n    coalesce(e.name, d.name, c.name, b.name, a.parent_txgroup) in ('Cost of Revenue','Operating Expenses','Other Operating Expense')\n  group by date\n  union\n  SELECT\n    date as time,\n    sum(average_14d),\n    'Cash In' as metric\n  FROM treasury_time_averages a\n  left join txgroups b on a.parent_txgroup_id = b.txgroup_id\n  left join txgroups c on b.parent_txgroup = c.txgroup_id\n  left join txgroups d on c.parent_txgroup = d.txgroup_id\n  left join txgroups e on d.parent_txgroup = e.txgroup_id\n  WHERE\n    $__timeFilter(date) and\n    coalesce(e.name, d.name, c.name, b.name, a.parent_txgroup) in ('Protocol Revenue','Other Income')\n  group by date\n) final\norder by time"
    }
   ]
  },
  {
   "title": "30-day averages",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "rawSql": "select *\nfrom (\n  SELECT\n    date as time,\n    sum(average_30d),\n    'Cash Out' as metric\n  FROM treasury_time_averages a\n  left join txgroups b on a.parent_txgroup_id = b.txgroup_id\n  left join txgroups c on b.parent_txgroup = c.txgroup_id\n  left join txgroups d on c.parent_txgroup = d.txgroup_id\n  left join txgroups e on d.parent_txgroup = e.txgroup_id\n  WHERE\n    $__timeFilter(date) and\n    coalesce(e.name, d.name, c.name, b.name, a.parent_txgroup) in ('Cost of Revenue','Operating Expenses','Other Operating Expense')\n  group by date\n  union\n  SELECT\n    date as time,\n    sum(average_30d),\n    'Cash In' as metric\n  FROM treasury_time_averages a\n  left join txgroups b on a.parent_txgroup_id = b.txgroup_id\n  left join txgroups c on b.parent_txgroup = c.txgroup_id\n  left join txgroups d on c.parent_txgroup = d.txgroup_id\n  left join txgroups e on d.parent_txgroup = e.txgroup_id\n  WHERE\n    $__timeFilter(date) and\n    coalesce(e.name, d.name, c.name, b.name, a.parent_txgroup) in ('Protocol Revenue','Other Income')\n  group by date\n) final\norder by time"
    }
   ]
  },
  {
   "title": "90-day averages",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "rawSql": "select *\nfrom (\n  SELECT\n    date as time,\n    sum(average_90d),\n    'Cash Out' as metric\n  FROM treasury_time_averages a\n  left join txgroups b on a.parent_txgroup_id = b.txgroup_id\n  left join txgroups c on b.parent_txgroup = c.txgroup_id\n  left join txgroups d on c.parent_txgroup = d.txgroup_id\n  left join txgroups e on d.parent_txgroup = e.txgroup_id\n  WHERE\n    $__timeFilter(date) and\n    coalesce(e.name, d.name, c.name, b.name, a.parent_txgroup) in ('Cost of Revenue','Operating Expenses','Other Operating Expense')\n  group by date\n  union\n  SELECT\n    date as time,\n    sum(average_90d),\n    'Cash In' as metric\n  FROM treasury_time_averages a\n  left join txgroups b on a.parent_txgroup_id = b.txgroup_id\n  left join txgroups c on b.parent_txgroup = c.txgroup_id\n  left join txgroups d on c.parent_txgroup = d.txgroup_id\n  left join txgroups e on d.parent_txgroup = e.txgroup_id\n  WHERE\n    $__timeFilter(date) and\n    coalesce(e.name, d.name, c.name, b.name, a.parent_txgroup) in ('Protocol Revenue','Other Income')\n  group by date\n) final\norder by time"
    }
   ]
  }
 ]
}