version: '3.7'

volumes:
    postgres_tvl_data: {}    
    solidity_compilers: {}
    vyper_compilers: {}
    brownie: {}
    cache: {}

networks:
  yearn-exporter-tvl:
    
services:
  api:
    build: .
    entrypoint: uvicorn yearn.api:app --host 0.0.0.0 --port 4000
    ports: 
      - 4000:4000
    environment:
      - PGUSER=postgres
      - PGHOST=postgres
    restart: always
    networks:
      - yearn-exporter-tvl
  yearn-exporter-tvl:
    build: .
    command: historical_tvl
    environment:
      - WEB3_PROVIDER
      - ETHERSCAN_TOKEN
      - PGUSER=postgres
      - PGHOST=postgres
      - PGPASS=yearn
    volumes: 
      - solidity_compilers:/root/.solcx
      - vyper_compilers:/root/.vvm
      - brownie:/root/.brownie
      - cache:/app/yearn-exporter/cache
    restart: always
    networks:
      - yearn-exporter-tvl
  postgres:
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=yearn
      - POSTGRES_DB=yearn
    volumes:
      - postgres_tvl_data:/var/lib/postgresql/data
    restart: always
    networks:
      - yearn-exporter-tvl
