{
 "title": "APY Overview",
 "description": "This dashboard give you an overview of net apy for vaults",
 "tags": [
  "APY",
  "Overview"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 10, "x": 0, "y": 0 },
   "options": {
    "content": "# APY Taking the Weekly Difference of Share Price\n### With Weekly Compounding\n\n           "
   },
   "targets": [
    {}
   ]
  },
  { "title": "v2 yVaults", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 } },
  {
   "title": "v2 Net APY - Weekly Compounding ",
   "type": "bargauge",
   "description": "This looks at the share price rate of change and factors in compounding on a weekly basis. ",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sort_desc(((delta(yearn_vault{network=\"ETH\", param=\"pricePerShare\", experimental=\"false\"}[1w]) + 1) ^ (1/7)) ^ 365 - 1) ",
     "legendFormat": "{{vault}}"
    }
   ]
  },
  {
   "title": "v2 Net APY - Weekly Compouding",
   "type": "graph",
   "description": "This looks at the share price rate of change and factors in compounding on a weekly basis. ",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "((delta(yearn_vault{network=\"ETH\", param=\"pricePerShare\", experimental=\"false\"}[1w]) + 1) ^ (1/7)) ^ 365 - 1",
     "legendFormat": "{{vault}}"
    }
   ]
  },
  {
   "title": "Earn",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 },
   "collapsed": true,
   "panels": [
    {
     "title": "busd.curve.fi Earn v3 - Net APY",
     "type": "bargauge",
     "description": "This looks at the share price rate of change and factors in compounding on a weekly basis. ",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sort_desc(((delta(iearn{network=\"ETH\", param=\"price per share\", vault=~\".*v3\"}[1w]) + 1) ^ (1/7)) ^ 365 - 1) ",
       "legendFormat": "{{vault}}"
      }
     ]
    },
    {
     "title": "y.curve.fi Earn v2 - Net APY",
     "type": "bargauge",
     "description": "This looks at the share price rate of change and factors in compounding on a weekly basis. ",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 34 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sort_desc(((delta(iearn{network=\"ETH\", param=\"price per share\", vault=~\".*v2\"}[1w]) + 1) ^ (1/7)) ^ 365 - 1) ",
       "legendFormat": "{{vault}}"
      }
     ]
    },
    {
     "title": "Earn - Net APY",
     "type": "graph",
     "description": "This looks at the share price rate of change and factors in compounding on a weekly basis. ",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 45 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "((delta(iearn{network=\"ETH\", param=\"price per share\"}[1w]) + 1) ^ (1/7)) ^ 365 - 1",
       "legendFormat": "{{vault}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Experimental yVaults",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 },
   "collapsed": true,
   "panels": [
    {
     "title": "Experimental Vault's - Net APY",
     "type": "bargauge",
     "description": "This looks at the share price rate of change and factors in compounding on a weekly basis. ",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 24 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sort_desc(((delta(yearn_vault{network=\"ETH\", param=\"pricePerShare\",experimental=\"true\"}[1w]) + 1) ^ (1/7)) ^ 365 - 1)",
       "legendFormat": "{{vault}}"
      }
     ]
    },
    {
     "title": "Experimental Vault's - Net APY",
     "type": "graph",
     "description": "This looks at the share price rate of change and factors in compounding on a weekly basis. ",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 35 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "((delta(yearn_vault{network=\"ETH\", param=\"pricePerShare\",experimental=\"true\"}[1w]) + 1) ^ (1/7)) ^ 365 - 1",
       "legendFormat": "{{vault}}"
      }
     ]
    }
   ]
  },
  {
   "title": "v1 yVaults",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 },
   "collapsed": true,
   "panels": [
    {
     "title": "v1 - Net APY",
     "type": "bargauge",
     "description": "This looks at the share price rate of change and factors in compounding on a weekly basis. ",
     "gridPos": { "h": 8, "w": 20, "x": 0, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sort_desc(((delta(yearn{network=\"ETH\", param=\"share price\"}[1w]) + 1) ^ (1/7)) ^ 365 - 1) ",
       "legendFormat": "{{vault}}"
      }
     ]
    },
    {
     "title": "v1 - Net APY",
     "type": "graph",
     "description": "This looks at the share price rate of change and factors in compounding on a weekly basis. ",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 33 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "((delta(yearn{network=\"ETH\", param=\"share price\"}[1w]) + 1) ^ (1/7)) ^ 365 - 1",
       "legendFormat": "{{vault}}"
      }
     ]
    }
   ]
  }
 ]
}