{
 "title": "APY Technical",
 "description": "This dashboard give you an overview of net apy for vaults",
 "tags": [
  "APY",
  "Overview"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "networks",
    "label": "network",
    "query": {
     "query": "yearn_strategy{experimental=\"false\", param=\"totalLoss\"}"
    }
   },
   { "name": "experimental", "label": "production?", "query": "No : true, Yes : false" },
   {
    "name": "tf",
    "label": "Frequency of harvests",
    "query": "Daily harvest : 1d, Twice a Week : 2d, Thrice a Week : 3d, Four times per Week : 4d, Five times per Week : 5d, Six times per Week : 6d,Once a Week : 7d,Once a Month : 30d,Once every Three Months : 90d"
   }
  ]
 },
 "panels": [
  {
   "title": "Avg APY",
   "type": "stat",
   "description": "Avg summed apy for all production vaults. This is with weekly compounding taking the share price difference over a week.",
   "gridPos": { "h": 4, "w": 5, "x": 2, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "\r\navg(((((delta(yearn_vault{network=\"$networks\", param=\"pricePerShare\", experimental=\"$experimental\", vault!~\"yvUSDC 0.2.2|yvDAI 0.2.2|yvWBTC 0.3.1|yvHEGIC 0.3.0\"}[$tf])) / yearn_vault{network=\"$networks\", param=\"pricePerShare\", experimental=\"$experimental\"} offset $tf)  + 1) ^ (365.2425 / $tf) - 1 ) * 100000)",
     "legendFormat": "APY (avg) (%)"
    }
   ]
  },
  {
   "title": "σ APY",
   "type": "stat",
   "description": "Current Standard Deviation of summed APY ",
   "gridPos": { "h": 4, "w": 5, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "stddev((((delta(yearn_vault{param=\"pricePerShare\", experimental=\"false\", vault!~\"yvUSDC 0.2.2|yvDAI 0.2.2|yvWBTC 0.3.1|yvHEGIC 0.3.0\"}[7d]) + 1) ^ (1/7)) ^ 365 - 1) < 1000)",
     "legendFormat": "APY (std)"
    }
   ]
  },
  {
   "title": "yVaults",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Net APY",
   "type": "bargauge",
   "description": "This looks at the share price rate of change over $tf and factors in compounding on a $cr day(s) per week basis. ",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sort_desc((((((delta(yearn_vault{network=\"$networks\", param=\"pricePerShare\", experimental=\"$experimental\"}[$tf])) / yearn_vault{network=\"$networks\", param=\"pricePerShare\", experimental=\"$experimental\"} offset $tf)  + 1) ^ (365.2425 / $tf) - 1 ) * 100000) )",
     "legendFormat": "{{vault}}"
    }
   ]
  },
  {
   "title": "Net APY",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "(((((delta(yearn_vault{network=\"$networks\", param=\"pricePerShare\", experimental=\"$experimental\"}[$tf])) / yearn_vault{network=\"$networks\", param=\"pricePerShare\", experimental=\"$experimental\"} offset $tf)  + 1) ^ (365.2425 / $tf) - 1 ) * 100000) ",
     "legendFormat": "{{vault}}"
    }
   ]
  },
  {
   "title": "Share Price",
   "type": "timeseries",
   "description": "This is the Share Price over time.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "yearn_vault{network=\"$networks\", param=\"pricePerShare\", experimental=\"$experimental\"}",
     "legendFormat": "{{vault}}"
    }
   ]
  },
  {
   "title": "Total APY",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Avg APY",
   "type": "timeseries",
   "description": "Avg summed apy for all production vaults. This is with weekly compunding taking the share price difference over a week. ",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "(avg(((((delta(yearn_vault{network=\"$networks\", param=\"pricePerShare\", experimental=\"$experimental\"}[$tf])) / yearn_vault{network=\"$networks\", param=\"pricePerShare\", experimental=\"$experimental\"} offset $tf)  + 1) ^ (365.2425 / $tf) - 1 ) * 100000) < 10000)",
     "legendFormat": "APY (avg) (%)"
    },
    {
     "expr": "stddev(((((delta(yearn_vault{network=\"$networks\", param=\"pricePerShare\", experimental=\"$experimental\"}[$tf])) / yearn_vault{network=\"$networks\", param=\"pricePerShare\", experimental=\"$experimental\"} offset $tf)  + 1) ^ (365.2425 / $tf) - 1 ) * 100000) ",
     "legendFormat": "APY (σ)"
    }
   ]
  }
 ]
}