{
 "title": "Boost Stats",
 "tags": [
  "Curve yVault",
  "Boost",
  "veCRV"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "Yearn veCRV Share",
   "type": "stat",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(yearn{network=\"ETH\", vault=\"curve.fi/3pool\",param=\"vecrv balance\"}) / avg(yearn{network=\"ETH\", vault=\"curve.fi/3pool\",param=\"vecrv total\"})",
     "legendFormat": "veCRV % share"
    }
   ]
  },
  {
   "title": "Boosties",
   "type": "graph",
   "description": "This is the current boost the vaults are getting",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "yearn{network=\"ETH\", param=\"boost\"}",
     "legendFormat": "{{vault}}"
    }
   ]
  },
  {
   "title": "Yearn veCRV Share",
   "type": "graph",
   "description": "This show amount of veCRV yearn has locked via backscratcher vault vs all other veCRV locked in all of curve.",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short", "label": "Amount veCRV locked" }
   ],
   "targets": [
    {
     "expr": "yearn{network=\"ETH\", param=\"vecrv total\", vault=\"curve.fi/3pool\"}",
     "legendFormat": "veCRV Locked Total"
    },
    {
     "expr": "yearn{network=\"ETH\", param=\"vecrv balance\", vault=\"curve.fi/3pool\"}",
     "legendFormat": "Total veCRV Locked w/ Yearn"
    },
    {
     "expr": "avg(yearn{network=\"ETH\", param=\"vecrv balance\", vault=\"curve.fi/3pool\"}) / avg(yearn{network=\"ETH\", param=\"vecrv total\", vault=\"curve.fi/3pool\"}) ",
     "legendFormat": "Yearn % total veCRV"
    }
   ]
  },
  {
   "title": "veCRV Required for Max Boost",
   "type": "graph",
   "description": "If yearn's veCRV amount locked = the numbers listed here then the vault can have max boost!",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 17 },
   "yaxes": [
    { "format": "short", "label": "veCRV" }
   ],
   "targets": [
    {
     "expr": "sort(yearn{network=\"ETH\", param=\"min vecrv\"})",
     "legendFormat": "{{vault}}"
    },
    {
     "expr": "avg(yearn{network=\"ETH\", param=\"vecrv balance\"})",
     "legendFormat": "veCRV Balance"
    }
   ]
  }
 ]
}