{
 "title": "Curve yVaults Info",
 "tags": [ "Curve yVault" ],
 "time": { "from": "now-24h", "to": "now" },
 "panels": [
  {
   "title": "Relative Weight",
   "type": "graph",
   "description": "This shows the curve vault's base APY. This is their current unboosted apys",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "yearn{param=\"relative weight\"}",
     "legendFormat": "{{vault}}"
    }
   ]
  },
  {
   "title": "Relative Weight",
   "type": "graph",
   "description": "This show the curve vaults and their % of gauge weight compared to the rest of all the curve pools",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    {
     "format": "percentunit",
     "label": "% Gauge Weight relative to all curve pools"
    }
   ],
   "targets": [
    {
     "expr": "sort_desc(yearn{param=\"relative weight\"})",
     "legendFormat": "{{vault}}"
    }
   ]
  },
  {
   "title": "CRV earned",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short", "label": "Total CRV earned" }
   ],
   "targets": [
    {
     "expr": "sort_desc(yearn{param=\"earned\"})",
     "legendFormat": "{{vault}} "
    }
   ]
  },
  {
   "title": "CRV Earned",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short", "label": "CRV waiting to be harvested" }
   ],
   "targets": [
    {
     "expr": "sort_desc(yearn{param=\"earned\"})",
     "legendFormat": "{{vault}}"
    }
   ]
  },
  {
   "title": "Total CRV earned",
   "type": "graph",
   "description": "This show the curve vaults and their % of gauge weight compared to the rest of all the curve pools",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short", "label": "Total CRV earned" }
   ],
   "targets": [
    {
     "expr": "sort_desc(yearn{param=\"lifetime earned\"})",
     "legendFormat": "{{vault}} "
    }
   ]
  }
 ]
}