{
 "title": "Earn",
 "description": "This dashboard provides a general overview on all of Earn's products.",
 "tags": [ "yEarn" ],
 "time": { "from": "now-30d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "earn",
    "label": "Which yEarn Product?",
    "query": "y.curve.fi : .*v2,busd.curve.fi : .*v3"
   }
  ]
 },
 "panels": [
  {
   "title": "yEarn TVL",
   "type": "stat",
   "description": "Total Valued Locked in Yearn's yEarn products. This sum includes y.curve.fi (v2) & busd.curve.fi (v3).",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(iearn{network=\"ETH\", param=\"tvl\"})",
     "legendFormat": "{{vault}}"
    }
   ]
  },
  {
   "title": "Daily Delta",
   "type": "stat",
   "description": "Daily change in TVL in Yearn's yEarn products. This sum includes y.curve.fi (v2) & busd.curve.fi (v3).",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(delta(iearn{network=\"ETH\", param=\"tvl\"}[1d]))",
     "legendFormat": "{{vault}}"
    }
   ]
  },
  {
   "title": "Weekly Delta",
   "type": "stat",
   "description": "Weekly change in TVL in Yearn's yEarn products. This sum includes y.curve.fi (v2) & busd.curve.fi (v3).",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(delta(iearn{network=\"ETH\", param=\"tvl\"}[1w]))",
     "legendFormat": "{{vault}}"
    }
   ]
  },
  {
   "title": "Monthly Delta",
   "type": "stat",
   "description": "Monthly change in TVL in Yearn's yEarn products. This sum includes y.curve.fi (v2) & busd.curve.fi (v3).",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(delta(iearn{network=\"ETH\", param=\"tvl\"}[4w]))",
     "legendFormat": "{{vault}}"
    }
   ]
  },
  {
   "title": "TVL - Graph",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "panels": [
    {
     "title": "Earn - TVL",
     "type": "graph",
     "description": "Earn TVL and Daily inflow/outflow. ",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(iearn{network=\"ETH\", param=\"tvl\"})",
       "legendFormat": "TVL"
      },
      {
       "expr": "sum(delta(iearn{network=\"ETH\", param=\"tvl\"}[1d]))",
       "legendFormat": "net inflow/outflow - daily"
      }
     ]
    }
   ]
  },
  {
   "title": "TVL - Graphs Detailed",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "collapsed": true,
   "panels": [
    {
     "title": "tvl",
     "type": "graph",
     "description": "TVL locked in Earn v2. You can shift + right-click on v2 AUM to exclude it from the graph (making it look nicer)",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "yaxes": [
      { "format": "short", "label": "AUM" }
     ],
     "targets": [
      {
       "expr": "iearn{network=\"ETH\", param=\"tvl\", vault=~\"$earn\"}",
       "legendFormat": "{{vault}}"
      },
      {
       "expr": "sum(iearn{network=\"ETH\", param=\"tvl\", vault=~\"$earn\"})",
       "legendFormat": "TVL"
      }
     ]
    },
    {
     "title": "tvl daily change",
     "type": "graph",
     "description": "Daily Change in TVL locked in $earn. You can shift + right-click on net inflow/outflow to exclude it from the graph (making it look nicer)",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "yaxes": [
      { "format": "short", "label": "Daily Change AUM" }
     ],
     "targets": [
      {
       "expr": "delta(iearn{network=\"ETH\", param=\"tvl\", vault=~\"$earn\"}[1d]) !=0",
       "legendFormat": "{{vault}}"
      },
      {
       "expr": "sum(delta(iearn{network=\"ETH\", param=\"tvl\", vault=~\"$earn\"}[1d]))",
       "legendFormat": "net inflow/outflow"
      }
     ]
    }
   ]
  },
  {
   "title": "Share Price",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "collapsed": true,
   "panels": [
    {
     "title": "Share Price",
     "type": "stat",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sort(iearn{network=\"ETH\", param=\"price per share\", vault=~\"$earn\"})",
       "legendFormat": "{{vault}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Share Price - Graphs",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "collapsed": true,
   "panels": [
    {
     "title": "Share Price",
     "type": "timeseries",
     "description": "The current price of $earn lp token should increase steadily as the lending yield is compounded in the Earn pool.",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "iearn{network=\"ETH\", param=\"price per share\", vault=~\"$earn\"}",
       "legendFormat": "{{vault}}"
      }
     ]
    },
    {
     "title": "Share Price - Rate of Increase",
     "type": "timeseries",
     "description": "Rate of increase of Share Price. If this goes up, that Earn product is compounding their yield gained from lending! This view helps normalize and show lending yield gained compared to other Earn products. The larger the spikes the more yield gain at that time from lending which was reinvested into the Earn product. The table shows the max value harvested for the timeframe selected. This number has been increased by a factor of 10 million to visualize the changes better. ",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "delta(iearn{network=\"ETH\", param=\"price per share\", vault=~\"$earn\"}[2m])*10000000",
       "legendFormat": "{{vault}}"
      }
     ]
    },
    {
     "title": "Share Price - 1d Annualized",
     "type": "timeseries",
     "description": "The rate of change of the yEarn's share price over 1 day annualized for better visualization.",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "delta(iearn{network=\"ETH\", param=\"price per share\", vault=~\"$earn\"}[1d]) * 365",
       "legendFormat": "{{vault}}"
      }
     ]
    }
   ]
  },
  { "title": "Share Price - Delta", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Share Price Change",
   "type": "stat",
   "description": "This is the change in share price over the time range you have selected. If you put what day you deposited as the start till now, then you will see how much share price has increased since then. ",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "iearn{network=\"ETH\", param=\"price per share\", vault=~\"$earn\"} - iearn{network=\"ETH\", param=\"price per share\", vault=~\"$earn\"} offset $__range",
     "legendFormat": "{{vault}}"
    }
   ]
  },
  {
   "title": "Share Price % change",
   "type": "stat",
   "description": "This is the % change in share price over the time range you have selected. If you put what day you deposited as the start till now, then you will see how much yield you have gained.",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(iearn{network=\"ETH\", param=\"price per share\", vault=~\"$earn\"} / iearn{network=\"ETH\", param=\"price per share\", vault=~\"$earn\"} offset $__range ) - 1",
     "legendFormat": "{{vault}}"
    }
   ]
  },
  {
   "title": "Lent / Unlent Supply",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 },
   "collapsed": true,
   "panels": [
    {
     "title": "Total Balance",
     "type": "graph",
     "description": "Amount of funds in the pool. Amounts are shown in terms of the deposit token and not in the dollar amount. This shows lent-out and unlent-out coins for the pools.",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "iearn{network=\"ETH\", param=\"pooled balance\", vault=~\"$earn\"}",
       "legendFormat": "{{vault}}"
      }
     ]
    },
    {
     "title": "Lent Out Supply",
     "type": "graph",
     "description": "Amount of deposit token currently being lent out on either dydx, aave, or compound lending markets. Amounts are shown in terms of the deposit token and not in dollar amount. ",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "iearn{network=\"ETH\", param=\"total supply\", vault=~\"$earn\"}",
       "legendFormat": "{{vault}}"
      }
     ]
    },
    {
     "title": "Unlent Supply",
     "type": "graph",
     "description": "This shows the balance that has yet to be deposited into a lending protocol: dydx, aave, or compound. ",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by (vault) (iearn{network=\"ETH\", param=\"pooled balance\",vault=~\"$earn\"}) - sum by (vault) (iearn{network=\"ETH\", param=\"total supply\",vault=~\"$earn\"})",
       "legendFormat": "{{vault}}"
      }
     ]
    }
   ]
  }
 ]
}