{
 "title": "Ironbank",
 "tags": [
  "Ironbank",
  "Cream v2"
 ],
 "time": { "from": "now-30d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "networks",
    "label": "network",
    "query": {
     "query": "yearn_strategy{experimental=\"false\", param=\"totalLoss\"}"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "TVL",
   "type": "stat",
   "description": "Ironbank TVL",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "(sum(ironbank_own{network=\"$networks\", param=\"tvl\"})) + (sum(ironbank{network=\"$networks\", param=\"tvl\"} > 0) or vector(0))",
     "legendFormat": "{{vault}}"
    }
   ]
  },
  {
   "title": "Daily Delta",
   "type": "stat",
   "description": "Daily change in TVL in Ironbank.",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(delta(ironbank_own{network=\"$networks\", param=\"tvl\"}[1d])) OR (sum(delta(ironbank{network=\"$networks\", param=\"tvl\"}[1d])) or vector(0))",
     "legendFormat": "{{vault}}"
    }
   ]
  },
  {
   "title": "Weekly Delta",
   "type": "stat",
   "description": "Weekly change in TVL in Ironbank.",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(delta(ironbank_own{network=\"$networks\", param=\"tvl\"}[1w])) OR (sum(delta(ironbank{network=\"$networks\", param=\"tvl\"}[1w])) or vector(0))",
     "legendFormat": "{{vault}}"
    }
   ]
  },
  {
   "title": "Monthly Delta",
   "type": "stat",
   "description": "Monthly change in TVL in Ironbank.",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(delta(ironbank_own{network=\"$networks\", param=\"tvl\"}[4w])) OR (sum(delta(ironbank{network=\"$networks\", param=\"tvl\"}[4w])) or vector(0))",
     "legendFormat": "{{vault}}"
    }
   ]
  },
  {
   "title": "TVL - Graph",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "targets": [
    {}
   ]
  },
  {
   "title": "TVL",
   "type": "timeseries",
   "description": "Ironbank TVL and Daily inflow/outflow. ",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "expr": "(sum(ironbank_own{network=\"$networks\", param=\"tvl\"})) OR (sum(ironbank{network=\"$networks\", param=\"tvl\"}) or vector(0))",
     "legendFormat": "TVL"
    },
    {
     "expr": "sum(delta(ironbank_own{network=\"$networks\", param=\"tvl\"}[1d])) OR (sum(delta(ironbank{network=\"$networks\", param=\"tvl\"}[1d])) or vector(0))",
     "legendFormat": "net inflow/outflow - daily"
    }
   ]
  },
  {
   "title": "TVL - Graph Detailed",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Ironbank - TVL",
     "type": "timeseries",
     "description": "Ironbank TVL and Daily inflow/outflow. ",
     "gridPos": { "h": 12, "w": 24, "x": 0, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
     "targets": [
      {
       "expr": "ironbank_own{network=\"$networks\", param=\"tvl\"} OR ironbank{network=\"$networks\", param=\"tvl\"} ",
       "legendFormat": "{{vault}}"
      },
      {
       "expr": "(sum(delta(ironbank{network=\"$networks\", param=\"tvl\"}[1d])) or vector(0)) + (sum(delta(ironbank_own{network=\"$networks\", param=\"tvl\"}[1d])) or vector(0))",
       "legendFormat": "net inflow/outflow - daily"
      }
     ]
    }
   ]
  },
  {
   "title": "Annual Percentage Yield",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Supply APY",
     "type": "bargauge",
     "description": "Supply APY > 0",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sort_desc(ironbank{network=\"$networks\", param=\"supply apy\"} > 0)",
       "legendFormat": "{{vault}}"
      }
     ]
    },
    {
     "title": "Borrow APY",
     "type": "bargauge",
     "description": "Borrow APY > 0",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sort_desc(ironbank{network=\"$networks\", param=\"borrow apy\"} > 0)",
       "legendFormat": "{{vault}}"
      }
     ]
    },
    {
     "title": "Supply APY",
     "type": "graph",
     "description": "The currently Supply APY for assets in Ironbank",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "yaxes": [
      { "format": "percentunit", "label": "Share Price" }
     ],
     "targets": [
      {
       "expr": "ironbank{network=\"$networks\", param=\"supply apy\"}",
       "legendFormat": "{{vault}}"
      }
     ]
    },
    {
     "title": "Borrow APY",
     "type": "graph",
     "description": "The currently Borrow APY for assets in Ironbank",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "yaxes": [
      { "format": "percentunit", "label": "Share Price" }
     ],
     "targets": [
      {
       "expr": "ironbank{network=\"$networks\", param=\"borrow apy\"}",
       "legendFormat": "{{vault}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Annual Percentage Yield - Delta",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Supply APY - Rate of Change",
     "type": "graph",
     "description": "The Supply APY for Ironbank Rate of Change over 5m intervals",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "yaxes": [
      { "format": "percentunit", "label": "Rate of change" }
     ],
     "targets": [
      {
       "expr": "delta(ironbank{network=\"$networks\", param=\"supply apy\"}[5m])",
       "legendFormat": "{{vault}}"
      }
     ]
    },
    {
     "title": "Borrrow APY - Rate of Change",
     "type": "graph",
     "description": "The Borrow APY for Ironbank Rate of Change over 5m intervals",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "yaxes": [
      { "format": "percentunit", "label": "Rate of change" }
     ],
     "targets": [
      {
       "expr": "delta(ironbank{network=\"$networks\", param=\"borrow apy\"}[5m])",
       "legendFormat": "{{vault}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Utilization",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Ironbank Utilization",
     "type": "bargauge",
     "description": "Utilization > 0",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sort_desc(ironbank{network=\"$networks\", param=\"utilization\"} > 0)",
       "legendFormat": "{{vault}}"
      }
     ]
    },
    {
     "title": "Ironbank - Utilization",
     "type": "graph",
     "description": "Ironbank Utilization\nPercent of funds available to be lent / funds being used. Utilization = totalBorrows / (getCash + totalBorrows - totalReserves)",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "yaxes": [
      { "format": "percentunit", "label": "Utilization (%)" }
     ],
     "targets": [
      {
       "expr": "ironbank{network=\"$networks\", param=\"utilization\"}",
       "legendFormat": "{{vault}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Supplied / Borrowed",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Total Supplied",
     "type": "graph",
     "description": "Ironbank Total Supplied Assets in deposit token.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "ironbank{network=\"$networks\", param=\"total supplied\"}",
       "legendFormat": "{{vault}}"
      }
     ]
    },
    {
     "title": "Total Borrowed",
     "type": "graph",
     "description": "Ironbank Total Borrowed Assets in deposit token",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 15 },
     "yaxes": [
      { "format": "short", "label": "Vault Shares " }
     ],
     "targets": [
      {
       "expr": "ironbank{network=\"$networks\", param=\"total borrows\"}",
       "legendFormat": "{{vault}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Overview",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Total Cash",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 16 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "ironbank{network=\"$networks\", param=\"total cash\"}",
       "legendFormat": "{{vault}}"
      }
     ]
    },
    {
     "title": "Total Kept in Reserve from Lent Assets",
     "type": "graph",
     "description": "Total Kept in reserve from what is lent currently this is 5% of lent out assets. Assets with 0 value hidden.",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 16 },
     "yaxes": [
      { "format": "short", "label": "Pool Shares kept in Reserve" }
     ],
     "targets": [
      {
       "expr": "ironbank{network=\"$networks\", param=\"total reserves\"}",
       "legendFormat": "{{vault}}"
      }
     ]
    },
    {
     "title": "Exchange Rate",
     "type": "graph",
     "description": "Exchange rate * 100 for readability",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 23 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "ironbank{network=\"$networks\", param=\"exchange rate\"} * 100",
       "legendFormat": "{{vault}}"
      }
     ]
    },
    {
     "title": "Underlying Price",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 23 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "ironbank{network=\"$networks\", param=\"underlying price\"}",
       "legendFormat": "{{vault}}"
      }
     ]
    },
    {
     "title": "Token Price",
     "type": "graph",
     "description": "Underlying Price * Exchange Rate",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 30 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "ironbank{network=\"$networks\", param=\"token price\"}",
       "legendFormat": "{{vault}}"
      }
     ]
    }
   ]
  }
 ]
}