{
 "title": "Overview Copy",
 "tags": [ "Overview" ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 0 },
   "options": {
    "content": "### Total Value Locked\ntotal value locked across yearn products"
   }
  },
  {
   "title": "total",
   "type": "stat",
   "description": "This counts all tvl on both eth and fantom chains and subtracts for delegated deposited funds in vaults. This does not count Iron Bank TVL",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(yearn{network=\"ETH\", param=\"tvl\"}) or vector(0)) + (avg(yearn{network=\"ETH\", param=\"vecrv balance\"}) * avg(yearn{network=\"ETH\", param=\"crv price\"}) or vector(0)) + (sum(yearn_vault{network=\"ETH\", param=\"tvl\"}) or vector(0)) + (sum(iearn{network=\"ETH\", param=\"tvl\"}) or vector(0)) - (sum((yearn_strategy{network=\"ETH\", param=\"delegatedAssets\"} / 1000000000000000000 > 0) * on(vault, version) group_left yearn_vault{network=\"ETH\", param=\"token price\"}) or vector(0)) + (sum(yearn_vault{network=\"FTM\", param=\"tvl\"}) or vector(0)) - (sum((yearn_strategy{network=\"FTM\", param=\"delegatedAssets\"} / 1000000000000000000 > 0) * on(vault, version) group_left yearn_vault{network=\"FTM\", param=\"token price\"}) or vector(0))",
     "legendFormat": "tvl"
    }
   ]
  },
  {
   "title": "daily delta",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(delta(yearn{param=\"tvl\", network=\"ETH\"}[1d])) + sum(delta(yearn_vault{param=\"tvl\", network=\"ETH\"}[1d])) + sum(delta(iearn{param=\"tvl\", network=\"ETH\"}[1d])) + sum(delta(yearn_vault{param=\"tvl\", network=\"FTM\"}[1d]))"
    }
   ]
  },
  {
   "title": "weekly delta",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(delta(yearn{param=\"tvl\", network=\"ETH\"}[1w])) + sum(delta(yearn_vault{param=\"tvl\", network=\"ETH\"}[1w])) + sum(delta(iearn{param=\"tvl\", network=\"ETH\"}[1w])) + sum(delta(yearn_vault{param=\"tvl\", network=\"FTM\"}[1w]))"
    }
   ]
  },
  {
   "title": "vecrv balance",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(yearn{param=\"vecrv balance\"})"
    }
   ]
  },
  {
   "title": "vecrv share",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(yearn{param=\"vecrv balance\"}) / avg(yearn{param=\"vecrv total\"})"
    }
   ]
  },
  {
   "title": "total eth",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(yearn{network=\"ETH\", param=\"tvl\"}) or vector(0)) + (avg(yearn{network=\"ETH\", param=\"vecrv balance\"}) * avg(yearn{network=\"ETH\", param=\"crv price\"}) or vector(0)) + (sum(yearn_vault{network=\"ETH\", param=\"tvl\"}) or vector(0)) + (sum(iearn{network=\"ETH\", param=\"tvl\"}) or vector(0)) - (sum((yearn_strategy{network=\"ETH\", param=\"delegatedAssets\", experimental=\"false\"} / 1000000000000000000 > 0) * on(vault, version) group_left yearn_vault{network=\"ETH\", param=\"token price\", experimental=\"false\"}) or vector(0))",
     "legendFormat": "eth tvl"
    }
   ]
  },
  {
   "title": "weekly delta eth",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(delta(yearn{param=\"tvl\", network=\"ETH\"}[1w])) + sum(delta(yearn_vault{param=\"tvl\", network=\"ETH\"}[1w])) + sum(delta(iearn{param=\"tvl\", network=\"ETH\"}[1w]))"
    }
   ]
  },
  {
   "title": "total ftm",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(yearn_vault{network=\"FTM\", param=\"tvl\"}) or vector(0))",
     "legendFormat": "ftm tvl"
    }
   ]
  },
  {
   "title": "weekly delta ftm",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(delta(yearn_vault{param=\"tvl\", network=\"FTM\"}[1w]))"
    }
   ]
  },
  {
   "title": "yearn tvl",
   "type": "graph",
   "description": "Sums tvl and subtracts out vault tvl that is delegated to other vaults",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "currencyUSD" }
   ],
   "targets": [
    {
     "expr": "sum(iearn{param=\"tvl\", network=\"ETH\"})",
     "legendFormat": "earn - eth"
    },
    {
     "expr": "sum(yearn{param=\"tvl\", network=\"ETH\"})",
     "legendFormat": "v1 - eth"
    },
    {
     "expr": "sum(yearn_vault{param=\"tvl\", network=\"ETH\"}) - (sum((yearn_strategy{param=\"delegatedAssets\", network=\"ETH\"} / 1000000000000000000 > 0) * on(vault, version) group_left yearn_vault{param=\"token price\", network=\"ETH\"}) or vector(0))",
     "legendFormat": "v2 - eth"
    },
    {
     "expr": "sum(yearn_vault{param=\"tvl\", network=\"FTM\"}) - (sum((yearn_strategy{param=\"delegatedAssets\", network=\"FTM\"} / 1000000000000000000 > 0) * on(vault, version) group_left yearn_vault{param=\"token price\", network=\"FTM\"}) or vector(0))",
     "legendFormat": "v2 - ftm"
    }
   ]
  },
  {
   "title": "yearn tvl daily change",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 6 },
   "yaxes": [
    { "format": "currencyUSD" }
   ],
   "targets": [
    {
     "expr": "sum(delta(iearn{param=\"tvl\", network=\"ETH\"}[1d]))",
     "legendFormat": "earn - eth"
    },
    {
     "expr": "sum(delta(yearn{param=\"tvl\", network=\"ETH\"}[1d]))",
     "legendFormat": "v1 - eth"
    },
    {
     "expr": "sum(delta(yearn_vault{param=\"tvl\", network=\"ETH\"}[1d]))",
     "legendFormat": "v2 - eth"
    },
    {
     "expr": "sum(delta(yearn_vault{param=\"tvl\", network=\"FTM\"}[1d]))",
     "legendFormat": "v2 - ftm"
    }
   ]
  },
  {
   "title": "time since last report",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "dtdurations" }
   ],
   "targets": [
    {
     "expr": "time() - yearn_vault{param=\"lastReport\", experimental=\"false\", vault!~\"yvUSDC 0.2.2|yvDAI 0.2.2|yvWBTC 0.3.1|yvHEGIC 0.3.0\", network=\"ETH\"}",
     "legendFormat": "{{vault}}"
    },
    {
     "expr": "time() - yearn_vault{param=\"lastReport\", experimental=\"false\", network=\"FTM\"}",
     "legendFormat": "{{vault}} - FTM"
    }
   ]
  },
  {
   "title": "yVault AUM",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 13 },
   "yaxes": [
    { "format": "short", "label": "tvl" }
   ],
   "targets": [
    {
     "expr": "yearn_vault{param=\"tvl\", experimental=\"false\", vault!~\"yvUSDC 0.2.2|yvDAI 0.2.2|yvWBTC 0.3.1|yvHEGIC 0.3.0\", network=\"ETH\"}",
     "legendFormat": "{{vault}}"
    },
    {
     "expr": "yearn_vault{param=\"tvl\", experimental=\"false\", network=\"FTM\"}",
     "legendFormat": "{{vault}} - FTM"
    }
   ]
  },
  {
   "title": "vecrv balance",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "yearn{vault=\"curve.fi/3pool\",param=\"vecrv balance\"}",
     "legendFormat": "{{param}}"
    },
    {
     "expr": "avg(yearn{vault=\"curve.fi/3pool\",param=\"vecrv balance\"}) / avg(yearn{vault=\"curve.fi/3pool\",param=\"vecrv total\"})",
     "legendFormat": "vecrv share"
    }
   ]
  },
  {
   "title": "share price",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 20 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "yearn_vault{param=\"pricePerShare\",experimental=\"false\", network=\"ETH\"}",
     "legendFormat": "{{vault}}"
    },
    {
     "expr": "yearn_vault{param=\"pricePerShare\",experimental=\"false\", network=\"FTM\"}",
     "legendFormat": "{{vault}} - FTM"
    }
   ]
  },
  {
   "title": "price per share change 1d annualized",
   "type": "graph",
   "description": "Annualized Share Price change > 0",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "delta(yearn_vault{param=\"pricePerShare\",experimental=\"false\", network=\"ETH\"}[1d]) * 365 > 0",
     "legendFormat": "{{vault}}"
    },
    {
     "expr": "delta(yearn_vault{param=\"pricePerShare\",experimental=\"false\", network=\"FTM\"}[1d]) * 365 > 0",
     "legendFormat": "{{vault}} - FTM"
    }
   ]
  },
  {
   "title": "TVL Graphs - ETH",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 },
   "collapsed": true,
   "panels": [
    {
     "title": "v2 tvl",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 36 },
     "yaxes": [
      { "format": "currencyUSD" }
     ],
     "targets": [
      {
       "expr": "yearn_vault{param=\"tvl\",experimental=\"false\", network=\"ETH\"} != 0",
       "legendFormat": "{{vault}}"
      }
     ]
    },
    {
     "title": "v2 tvl daily",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 36 },
     "yaxes": [
      { "format": "currencyUSD" }
     ],
     "targets": [
      {
       "expr": "delta(yearn_vault{param=\"tvl\",experimental=\"false\", network=\"ETH\"}[1d]) != 0",
       "legendFormat": "{{vault}}"
      },
      {
       "expr": "sum(delta(yearn_vault{param=\"tvl\",experimental=\"false\", network=\"ETH\"}[1d]))",
       "legendFormat": "net inflow/outflow"
      }
     ]
    },
    {
     "title": "v1 tvl",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 44 },
     "yaxes": [
      { "format": "currencyUSD" }
     ],
     "targets": [
      {
       "expr": "yearn{param=\"tvl\", network=\"ETH\"} != 0",
       "legendFormat": "{{vault}}"
      }
     ]
    },
    {
     "title": "v1 tvl daily",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 44 },
     "yaxes": [
      { "format": "currencyUSD" }
     ],
     "targets": [
      {
       "expr": "delta(yearn{param=\"tvl\", network=\"ETH\"}[1d]) != 0",
       "legendFormat": "{{vault}}"
      },
      {
       "expr": "sum(delta(yearn{param=\"tvl\", network=\"ETH\"}[1d]))",
       "legendFormat": "net inflow/outflow"
      }
     ]
    },
    {
     "title": "iearn tvl",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 52 },
     "yaxes": [
      { "format": "currencyUSD" }
     ],
     "targets": [
      {
       "expr": "iearn{param=\"tvl\", network=\"ETH\"} != 0",
       "legendFormat": "{{vault}}"
      }
     ]
    },
    {
     "title": "iearn tvl daily",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 52 },
     "yaxes": [
      { "format": "currencyUSD" }
     ],
     "targets": [
      {
       "expr": "delta(iearn{param=\"tvl\", network=\"ETH\"}[1d]) != 0",
       "legendFormat": "{{vault}}"
      },
      {
       "expr": "sum(delta(iearn{param=\"tvl\"}[1d]))",
       "legendFormat": "net inflow/outflow"
      }
     ]
    },
    {
     "title": "ve tvl",
     "type": "graph",
     "description": "Experimental vaults on ape.tax TVL",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 60 },
     "yaxes": [
      { "format": "currencyUSD" }
     ],
     "targets": [
      {
       "expr": "yearn_vault{param=\"tvl\", experimental=\"true\", network=\"ETH\"} != 0",
       "legendFormat": "{{vault}}"
      }
     ]
    },
    {
     "title": "ve tvl daily",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 60 },
     "yaxes": [
      { "format": "currencyUSD" }
     ],
     "targets": [
      {
       "expr": "delta(yearn_vault{param=\"tvl\", experimental=\"true\", network=\"ETH\"}[1d]) != 0",
       "legendFormat": "{{vault}}"
      },
      {
       "expr": "sum(delta(yearn_vault{param=\"tvl\", experimental=\"true\", network=\"ETH\"}[1d]))",
       "legendFormat": "net inflow/outflow"
      }
     ]
    }
   ]
  },
  {
   "title": "TVL Graphs - FTM",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 },
   "collapsed": true,
   "panels": [
    {
     "title": "v2 tvl",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 37 },
     "yaxes": [
      { "format": "currencyUSD" }
     ],
     "targets": [
      {
       "expr": "yearn_vault{param=\"tvl\",experimental=\"false\", network=\"FTM\"} != 0",
       "legendFormat": "{{vault}}"
      }
     ]
    },
    {
     "title": "v2 tvl daily",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 37 },
     "yaxes": [
      { "format": "currencyUSD" }
     ],
     "targets": [
      {
       "expr": "delta(yearn_vault{param=\"tvl\", experimental=\"false\", network=\"FTM\"}[1d]) != 0",
       "legendFormat": "{{vault}}"
      },
      {
       "expr": "sum(delta(yearn_vault{param=\"tvl\", experimental=\"false\", network=\"FTM\"}[1d]))",
       "legendFormat": "net inflow/outflow"
      }
     ]
    },
    {
     "title": "ve tvl",
     "type": "graph",
     "description": "Experimental vaults on ape.tax TVL",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 45 },
     "yaxes": [
      { "format": "currencyUSD" }
     ],
     "targets": [
      {
       "expr": "yearn_vault{param=\"tvl\", experimental=\"true\", network=\"FTM\"} != 0",
       "legendFormat": "{{vault}}"
      }
     ]
    },
    {
     "title": "ve tvl daily",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 45 },
     "yaxes": [
      { "format": "currencyUSD" }
     ],
     "targets": [
      {
       "expr": "delta(yearn_vault{param=\"tvl\", experimental=\"true\", network=\"FTM\"}[1d]) != 0",
       "legendFormat": "{{vault}}"
      },
      {
       "expr": "sum(delta(yearn_vault{param=\"tvl\", experimental=\"true\", network=\"FTM\"}[1d]))",
       "legendFormat": "net inflow/outflow"
      }
     ]
    }
   ]
  }
 ]
}