{
 "title": "Overview",
 "tags": [ "Overview" ],
 "time": { "from": "now-30d", "to": "now" },
 "refresh": "5m",
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 0 },
   "options": {
    "content": "### Total Value Locked\ntotal value locked across yearn products"
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "total",
   "type": "stat",
   "description": "This counts all tvl on all chains. This does not count Iron Bank TVL and does not subtract out delegated deposit.",
   "gridPos": { "h": 3, "w": 8, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(sum by (network, vault, address, version) (yearn_vault{param=\"tvl\", experimental=\"false\"})) + sum(iearn{param=\"tvl\"}) + sum(yearn{param=\"tvl\"})",
     "legendFormat": "tvl"
    }
   ]
  },
  {
   "title": "total L1",
   "type": "stat",
   "description": "total native tvl in layer 1s",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(sum by (vault, version, address) (yearn_vault{param=\"tvl\", experimental=\"false\", network=\"ETH\"})) + sum(sum by (vault, version, address) (yearn_vault{param=\"tvl\", experimental=\"false\", network=\"FTM\"}))",
     "legendFormat": "l1 tvl"
    }
   ]
  },
  {
   "title": "total L2",
   "type": "stat",
   "description": "total native tvl in layer 2 vaults",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(sum by (vault, version, address) (yearn_vault{param=\"tvl\", experimental=\"false\", network=\"OPTI\"})) + sum(sum by (vault, version, address) (yearn_vault{param=\"tvl\", experimental=\"false\", network=\"ARB\"}))",
     "legendFormat": "ftm tvl"
    }
   ]
  },
  {
   "title": "Liquid Treasury",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(treasury_assets{param=\"usd value\",bucket=\"Cash & cash equivalents\"}) - sum(treasury_debt{param=\"usd value\"})",
     "legendFormat": "Liquid"
    }
   ]
  },
  {
   "title": "Locked CRV Balance",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(yearn{vault=\"curve.fi/3pool\",param=\"vecrv balance\"}) / avg(yearn{vault=\"curve.fi/3pool\",param=\"vecrv total\"})",
     "legendFormat": "vecrv share"
    }
   ]
  },
  {
   "title": "yearn tvl",
   "type": "timeseries",
   "description": "This is just tvl summed and does not subtract out delegated deposits",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "expr": "sum(iearn{param=\"tvl\"})",
     "legendFormat": "earn - eth"
    },
    {
     "expr": "sum(yearn{param=\"tvl\", network=\"ETH\"})",
     "legendFormat": "v1 - eth"
    },
    {
     "expr": "sum(sum by (vault, version, address) (yearn_vault{param=\"tvl\", experimental=\"false\", network=\"ETH\"}))",
     "legendFormat": "v2 - eth"
    },
    {
     "expr": "sum(sum by (vault, version, address) (yearn_vault{param=\"tvl\", experimental=\"false\", network=\"FTM\"}))",
     "legendFormat": "v2 - ftm"
    },
    {
     "expr": "sum(sum by (vault, version, address) (yearn_vault{param=\"tvl\", experimental=\"false\", network=\"OPTI\"}))",
     "legendFormat": "v2 - opt"
    },
    {
     "expr": "sum(sum by (vault, version, address) (yearn_vault{param=\"tvl\", experimental=\"false\", network=\"ARB\"}))",
     "legendFormat": "v2 - arb"
    }
   ]
  },
  {
   "title": "yearn tvl daily change",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "expr": "sum(delta(iearn{param=\"tvl\", network=\"ETH\"}[1d]))",
     "legendFormat": "earn - eth"
    },
    {
     "expr": "sum(delta(yearn{param=\"tvl\", network=\"ETH\"}[1d]))",
     "legendFormat": "v1 - eth"
    },
    {
     "expr": "sum(delta(yearn_vault{param=\"tvl\", network=\"ETH\", experimental=\"false\"}[1d]))",
     "legendFormat": "v2 - eth"
    },
    {
     "expr": "sum(delta(yearn_vault{param=\"tvl\", network=\"FTM\", experimental=\"false\"}[1d]))",
     "legendFormat": "v2 - ftm"
    },
    {
     "expr": "sum(delta(yearn_vault{param=\"tvl\", network=\"OPTI\", experimental=\"false\"}[1d]))",
     "legendFormat": "v2 - opt"
    },
    {
     "expr": "sum(delta(yearn_vault{param=\"tvl\", network=\"ARB\", experimental=\"false\"}[1d]))",
     "legendFormat": "v2 - arb"
    }
   ]
  },
  {
   "title": "vecrv balance",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "yearn{vault=\"curve.fi/3pool\",param=\"vecrv balance\"}",
     "legendFormat": "{{param}}"
    },
    {
     "expr": "avg(yearn{vault=\"curve.fi/3pool\",param=\"vecrv balance\"}) / avg(yearn{vault=\"curve.fi/3pool\",param=\"vecrv total\"})",
     "legendFormat": "vecrv share"
    }
   ]
  },
  {
   "title": "vault aum",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "yearn_vault{param=\"tvl\", experimental=\"false\", vault!~\"yvUSDC 0.2.2|yvDAI 0.2.2|yvWBTC 0.3.1|yvHEGIC 0.3.0\", network=\"ETH\"}",
     "legendFormat": "{{vault}} - {{network}}"
    },
    {
     "expr": "yearn_vault{param=\"tvl\", experimental=\"false\", network=\"FTM\"}",
     "legendFormat": "{{vault}} - FTM"
    },
    {
     "expr": "yearn_vault{param=\"tvl\", experimental=\"false\", network=\"OPTI\"}",
     "legendFormat": "{{vault}} - {{network}}"
    },
    {
     "expr": "yearn_vault{param=\"tvl\", experimental=\"false\", network=\"ARB\"}",
     "legendFormat": "{{vault}} - {{network}}"
    }
   ]
  },
  {
   "title": "time since last report",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "targets": [
    {
     "expr": "time() - yearn_vault{param=\"lastReport\", experimental=\"false\", vault!~\"yvUSDC 0.2.2|yvDAI 0.2.2|yvWBTC 0.3.1|yvHEGIC 0.3.0\", network=\"ETH\"}",
     "legendFormat": "{{vault}}"
    },
    {
     "expr": "time() - yearn_vault{param=\"lastReport\", experimental=\"false\", network=\"FTM\"}",
     "legendFormat": "{{vault}} - FTM"
    },
    {
     "expr": "time() - yearn_vault{param=\"lastReport\", experimental=\"false\", network=\"OPTI\"}",
     "legendFormat": "{{vault}} - OPTI"
    },
    {
     "expr": "time() - yearn_vault{param=\"lastReport\", experimental=\"false\", network=\"ARB\"}",
     "legendFormat": "{{vault}} - ARB"
    }
   ]
  },
  {
   "title": "share price",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "yearn_vault{param=\"pricePerShare\",experimental=\"false\", network=\"ETH\"}",
     "legendFormat": "{{vault}} - {{network}}"
    },
    {
     "expr": "yearn_vault{param=\"pricePerShare\",experimental=\"false\", network=\"FTM\"}",
     "legendFormat": "{{vault}} - {{network}}"
    },
    {
     "expr": "yearn_vault{param=\"pricePerShare\",experimental=\"false\", network=\"OPTI\"}",
     "legendFormat": "{{vault}} - {{network}}"
    },
    {
     "expr": "yearn_vault{param=\"pricePerShare\",experimental=\"false\", network=\"ARB\"}",
     "legendFormat": "{{vault}} - {{network}}"
    }
   ]
  },
  {
   "title": "price per share change 1d annualized",
   "type": "graph",
   "description": "Annualized Share Price change > 0",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "delta(yearn_vault{param=\"pricePerShare\",experimental=\"false\", network=\"ETH\"}[1d]) * 365 > 0",
     "legendFormat": "{{vault}}"
    },
    {
     "expr": "delta(yearn_vault{param=\"pricePerShare\",experimental=\"false\", network=\"FTM\"}[1d]) * 365 > 0",
     "legendFormat": "{{vault}} - FTM"
    }
   ]
  }
 ]
}