{
 "title": "Total Value Locked in the Yearn Ecosystem",
 "description": "This show TVL lacked in Yearn Finance Products",
 "tags": [ "Overview" ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "networks",
    "label": "network",
    "query": {
     "query": "yearn_strategy{experimental=\"false\", param=\"totalLoss\"}"
    }
   },
   {
    "name": "tf",
    "label": "time frame",
    "query": "one day : 1d,one week : 7d,one month : 30d,three months : 90d,one year : 1y "
   }
  ]
 },
 "panels": [
  {
   "title": "TVL",
   "type": "stat",
   "description": "Accurate TVL with duplicates funds (funds from a vault deposited into another vault) subtracted includes all networks.",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(yearn{network=\"ETH\", param=\"tvl\"}) or vector(0)) + (avg(yearn{network=\"ETH\", param=\"vecrv balance\"}) * avg(yearn{network=\"ETH\", param=\"crv price\"}) or vector(0)) + (sum(yearn_vault{network=\"ETH\", param=\"tvl\"}) or vector(0)) + (sum(iearn{network=\"ETH\", param=\"tvl\"}) or vector(0)) + (sum(ironbank{network=\"ETH\", param=\"tvl\"}) or vector(0)) - (sum((yearn_strategy{network=\"ETH\", param=\"delegatedAssets\"} / 1000000000000000000 > 0) * on(vault, version) group_left yearn_vault{network=\"ETH\", param=\"token price\"}) or vector(0)) + (sum(ironbank{network=\"FTM\", param=\"tvl\"}) or vector(0)) + (sum(yearn_vault{network=\"FTM\", param=\"tvl\"}) or vector(0))",
     "legendFormat": "TVL"
    }
   ]
  },
  { "title": "$networks tvl", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "V2 TVL",
   "type": "stat",
   "description": "Aggragate tvl for v2 vaults on $networks",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(yearn_vault{network=\"$networks\", param=\"tvl\", experimental=\"false\"}) or vector(0)) - (sum((yearn_strategy{network=\"$networks\", param=\"delegatedAssets\", experimental=\"false\"} / 1000000000000000000 > 0) * on(vault, version) group_left yearn_vault{network=\"$networks\", param=\"token price\", experimental=\"false\"}) or vector(0))",
     "legendFormat": "{{vault}}"
    }
   ]
  },
  {
   "title": "Earn TVL",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(iearn{param=\"tvl\", network=\"$networks\"}) or vector(0))",
     "legendFormat": "{{vault}}"
    }
   ]
  },
  {
   "title": "Ironbank TVL",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(ironbank{param=\"tvl\", network=\"$networks\"}) or vector(0)",
     "legendFormat": "{{vault}}"
    }
   ]
  },
  {
   "title": "veCRV TVL",
   "type": "stat",
   "description": "$ amount of veCRV Yearn.Finance has locked to boost curve vault yield. ",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(avg(yearn{param=\"vecrv balance\", network=\"$networks\"}) * avg(yearn{param=\"crv price\", network=\"$networks\"}) or vector(0))",
     "legendFormat": "{{vault}}"
    }
   ]
  },
  {
   "title": "Ape.Tax TVL",
   "type": "stat",
   "description": "TVL sum of ape.tax experimental vaults on $networks. These vaults are for testing use them with caution. ",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(yearn_vault{param=\"tvl\", experimental=\"true\", network=\"$networks\"}) - (sum((yearn_strategy{param=\"delegatedAssets\", experimental=\"true\", network=\"$networks\"} / 1000000000000000000 > 0) * on(vault, version) group_left yearn_vault{param=\"token price\", experimental=\"true\", network=\"$networks\"}) or vector(0))",
     "legendFormat": "{{vault}}"
    }
   ]
  },
  {
   "title": "V1 tvl",
   "type": "stat",
   "description": "Amount of funds in old v1 vaults. All tvl is earning 0% apy please migrate asap at yearn.finance. ",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(yearn{param=\"tvl\", network=\"$networks\"})",
     "legendFormat": "{{vault}}"
    }
   ]
  },
  { "title": "$tf - tvl delta", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "type": "stat",
   "description": "$tf tvl change - yearn v2 yvaults on $networks",
   "gridPos": { "h": 2, "w": 2, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(yearn_vault{param=\"tvl\", experimental=\"false\", network=\"$networks\"}) - sum(yearn_vault{param=\"tvl\", experimental=\"false\", network=\"$networks\"} offset $tf)",
     "legendFormat": "{{vault}}"
    }
   ]
  },
  {
   "type": "stat",
   "description": "$tf tvl % change - yearn v2 yvaults on $networks",
   "gridPos": { "h": 2, "w": 2, "x": 2, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(yearn_vault{param=\"tvl\", experimental=\"false\", network=\"$networks\"}) / sum(yearn_vault{param=\"tvl\", experimental=\"false\", network=\"$networks\"} offset $tf) - 1",
     "legendFormat": "{{vault}}"
    }
   ]
  },
  {
   "type": "stat",
   "description": "$tf tvl change - yearn v2+v3 yEarn on $networks",
   "gridPos": { "h": 2, "w": 2, "x": 4, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(iearn{param=\"tvl\", network=\"$networks\"}) - sum(iearn{param=\"tvl\", network=\"$networks\"} offset $tf)",
     "legendFormat": "{{vault}}"
    }
   ]
  },
  {
   "type": "stat",
   "description": "$tf tvl % change - yearn v2+v3 yEarn on $networks",
   "gridPos": { "h": 2, "w": 2, "x": 6, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(iearn{param=\"tvl\", network=\"$networks\"}) / sum(iearn{param=\"tvl\", network=\"$networks\"} offset $tf) - 1",
     "legendFormat": "{{vault}}"
    }
   ]
  },
  {
   "type": "stat",
   "description": "$tf tvl change - yearn ironbank on $networks",
   "gridPos": { "h": 2, "w": 2, "x": 8, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(ironbank{param=\"tvl\", network=\"$networks\"}) - sum(ironbank{param=\"tvl\", network=\"$networks\"} offset $tf)",
     "legendFormat": "{{vault}}"
    }
   ]
  },
  {
   "type": "stat",
   "description": "$tf tvl % change - yearn ironbank on $networks",
   "gridPos": { "h": 2, "w": 2, "x": 10, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(ironbank{param=\"tvl\", network=\"$networks\"}) / sum(ironbank{param=\"tvl\", network=\"$networks\"} offset $tf) - 1",
     "legendFormat": "{{vault}}"
    }
   ]
  },
  {
   "type": "stat",
   "description": "$tf tvl change - yearn locked veCRV for curve boosts. This is only on the ETH network.",
   "gridPos": { "h": 2, "w": 2, "x": 12, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(avg(yearn{param=\"vecrv balance\", network=\"$networks\"}) * avg(yearn{param=\"crv price\", network=\"$networks\"})) - (avg(yearn{param=\"vecrv balance\", network=\"$networks\"}) * avg(yearn{param=\"crv price\", network=\"$networks\"})) offset $tf",
     "legendFormat": "{{vault}}"
    }
   ]
  },
  {
   "type": "stat",
   "description": "$tf tvl % change - yearn locked veCRV for curve boosts. This is only on the ETH network.",
   "gridPos": { "h": 2, "w": 2, "x": 14, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(avg(yearn{param=\"vecrv balance\", network=\"$networks\"}) * avg(yearn{param=\"crv price\", network=\"$networks\"})) / (avg(yearn{param=\"vecrv balance\", network=\"$networks\"}) * avg(yearn{param=\"crv price\", network=\"$networks\"}) offset $tf) - 1",
     "legendFormat": "{{vault}}"
    }
   ]
  },
  {
   "type": "stat",
   "description": "$tf tvl change - yearn ape.tax vaults on $networks",
   "gridPos": { "h": 2, "w": 2, "x": 16, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(yearn_vault{param=\"tvl\", experimental=\"true\", network=\"$networks\"}) - sum(yearn_vault{param=\"tvl\", experimental=\"true\", network=\"$networks\"} offset $tf)",
     "legendFormat": "{{vault}}"
    }
   ]
  },
  {
   "type": "stat",
   "description": "$tf tvl % change - yearn ape.tax yvaults on $networks",
   "gridPos": { "h": 2, "w": 2, "x": 18, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(yearn_vault{param=\"tvl\", experimental=\"true\", network=\"$networks\"}) / sum(yearn_vault{param=\"tvl\", experimental=\"true\", network=\"$networks\"} offset $tf) - 1",
     "legendFormat": "{{vault}}"
    }
   ]
  },
  {
   "type": "stat",
   "description": "$tf tvl change - yearn v1 on $networks. If you have funds in yearn v1 please migrate at yearn.finance you are no longer earning yield, all v1 vaults are 0% apy. ",
   "gridPos": { "h": 2, "w": 2, "x": 20, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(yearn{param=\"tvl\", network=\"$networks\"}) - sum(yearn{param=\"tvl\", network=\"$networks\"} offset $tf)",
     "legendFormat": "{{vault}}"
    }
   ]
  },
  {
   "type": "stat",
   "description": "$tf tvl % change - yearn v1 on $networks. If you have funds in yearn v1 please migrate at yearn.finance you are no longer earning yield, all v1 vaults are 0% apy. ",
   "gridPos": { "h": 2, "w": 2, "x": 22, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(yearn{param=\"tvl\", network=\"$networks\"}) / sum(yearn{param=\"tvl\", network=\"$networks\"} offset $tf) - 1",
     "legendFormat": "{{vault}}"
    }
   ]
  },
  {
   "title": "Charts",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 },
   "collapsed": true,
   "panels": [
    {
     "title": "v2 TVL",
     "type": "graph",
     "gridPos": { "h": 11, "w": 12, "x": 0, "y": 14 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "yearn_vault{param=\"tvl\", experimental=\"false\", network=\"$networks\"}",
       "legendFormat": "{{vault}}"
      }
     ]
    },
    {
     "title": "v2 TVL",
     "type": "graph",
     "gridPos": { "h": 11, "w": 12, "x": 12, "y": 14 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "(sum(yearn_vault{network=\"$networks\", param=\"tvl\"})) - (sum((yearn_strategy{network=\"$networks\", param=\"delegatedAssets\", experimental=\"false\"} / 1000000000000000000 > 0) * on(vault, version) group_left yearn_vault{network=\"$networks\", param=\"token price\", experimental=\"false\"} or vector(0)))",
       "legendFormat": "v2 Total Value Locked"
      }
     ]
    },
    {
     "title": "Ironbank TVL",
     "type": "graph",
     "gridPos": { "h": 11, "w": 12, "x": 0, "y": 25 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "ironbank{param=\"tvl\", network=\"$networks\"}",
       "legendFormat": "{{vault}}"
      }
     ]
    },
    {
     "title": "Ironbank TVL",
     "type": "graph",
     "gridPos": { "h": 11, "w": 12, "x": 12, "y": 25 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(ironbank{param=\"tvl\", network=\"$networks\"})",
       "legendFormat": "Ironbank Total Value Locked"
      }
     ]
    },
    {
     "title": "Ape.Tax TVL",
     "type": "graph",
     "description": "Experimental v2 vaults on $network use at your own risk. ",
     "gridPos": { "h": 11, "w": 12, "x": 0, "y": 36 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "yearn_vault{param=\"tvl\", experimental=\"true\", network=\"$networks\"}",
       "legendFormat": "{{vault}}"
      }
     ]
    },
    {
     "title": "Ape.Tax TVL",
     "type": "graph",
     "description": "Experimental v2 vaults on $network use at your own risk. ",
     "gridPos": { "h": 11, "w": 12, "x": 12, "y": 36 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(yearn_vault{param=\"tvl\", experimental=\"true\", network=\"$networks\"})",
       "legendFormat": "Experimental Total Value Locked -"
      }
     ]
    },
    {
     "title": "Earn TVL",
     "type": "graph",
     "description": "Earn v2 and v3 tvl",
     "gridPos": { "h": 11, "w": 12, "x": 0, "y": 47 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "iearn{param=\"tvl\", network=\"$networks\"}",
       "legendFormat": "{{vault}}"
      }
     ]
    },
    {
     "title": "Earn TVL",
     "type": "graph",
     "description": "Earn v2 and v3 aggregated tvl",
     "gridPos": { "h": 11, "w": 12, "x": 12, "y": 47 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(iearn{param=\"tvl\", network=\"$networks\"})",
       "legendFormat": "Earn Total Value Locked"
      }
     ]
    },
    {
     "title": "v1 TVL",
     "type": "graph",
     "gridPos": { "h": 11, "w": 12, "x": 0, "y": 58 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "yearn{param=\"tvl\", network=\"$networks\"}",
       "legendFormat": "{{vault}}"
      }
     ]
    },
    {
     "title": "v1 TVL",
     "type": "graph",
     "gridPos": { "h": 11, "w": 12, "x": 12, "y": 58 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(yearn{param=\"tvl\", network=\"$networks\"})",
       "legendFormat": "v1 Total Value Locked"
      }
     ]
    }
   ]
  }
 ]
}