{
 "title": "V1 Vaults",
 "tags": [
  "yVault",
  "Deprecated",
  "Version 1"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "panels": [
  {
   "title": "Total Value Locked",
   "type": "stat",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(yearn{network=\"ETH\", param=\"tvl\"})",
     "legendFormat": "v1 AUM"
    }
   ]
  },
  {
   "title": "Daily Delta",
   "type": "stat",
   "description": "Daily change in TVL in Yearn's yVault products. ",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(delta(yearn{network=\"ETH\", param=\"tvl\"}[1d]))",
     "legendFormat": "v1 AUM"
    }
   ]
  },
  {
   "title": "Weekly Delta",
   "type": "stat",
   "description": "Weekly change in TVL in Yearn's yVault products.",
   "gridPos": { "h": 4, "w": 6, "x": 9, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(delta(yearn{network=\"ETH\", param=\"tvl\"}[1w]))",
     "legendFormat": "v1 AUM"
    }
   ]
  },
  {
   "title": "Monthly Delta",
   "type": "stat",
   "description": "Monthly change in TVL in Yearn's yVault products. ",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(delta(yearn{network=\"ETH\", param=\"tvl\"}[4w]))",
     "legendFormat": "v1 AUM"
    }
   ]
  },
  {
   "title": "TVL - Graphs",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "collapsed": true,
   "panels": [
    {
     "title": "Total Value Locked",
     "type": "graph",
     "description": "This shows Total Value Locked in v1 Vaults. If you see a quick sharp dip just ignore it, that isn't someone withdrawing and depositing quickly but a problem with the exporter at that time. ",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 10 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(yearn{network=\"ETH\", param=\"tvl\"})",
       "legendFormat": "v1 AUM"
      },
      {
       "expr": "sum(delta(yearn{network=\"ETH\", param=\"tvl\"}[1d]))",
       "legendFormat": "v1 net inflow/outflow"
      }
     ]
    },
    {
     "title": "Daily Change",
     "type": "graph",
     "description": "Show the Daily change in v1 yVault's Assets Under Management. \n",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 19 },
     "yaxes": [
      { "format": "short", "label": "Change in Vault TVL" }
     ],
     "targets": [
      {
       "expr": "delta(yearn{network=\"ETH\", param=\"tvl\"}[1d]) != 0",
       "legendFormat": "{{vault}}"
      },
      {
       "expr": "sum(delta(yearn{network=\"ETH\", param=\"tvl\"}[1d]))",
       "legendFormat": "net inflow/outflow"
      }
     ]
    }
   ]
  },
  {
   "title": "Share Price - Graphs",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "collapsed": true,
   "panels": [
    {
     "title": "Price Per Share - Rate of Change",
     "type": "graph",
     "description": "Rate of change of Vault Share price. If this goes up the vaults are selling their farmed asset for more vault tokens! This helps normalize and show harvests compared to other vaults. The larger the spikes the more assets sold on that harvest call. The table shows the max value harvested for the timeframe selected.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "delta(yearn{network=\"ETH\", param=\"share price\"}[5m])",
       "legendFormat": "{{vault}}",
       "panelId": 6
      }
     ]
    },
    {
     "title": "Share Price",
     "type": "graph",
     "description": "The current price of the vault's lp token, should increase steadily as vault's farmed assets are sold.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "yearn{network=\"ETH\", param=\"share price\"}",
       "legendFormat": "{{vault}}",
       "panelId": 6
      }
     ]
    },
    {
     "title": "Price Per Share - 1d Annualized",
     "type": "graph",
     "description": "The current share price of the v1 yVault's token. This should increase steadily as yield is compounded into the vault.",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 19 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "delta(yearn{network=\"ETH\", param=\"share price\"}[1d]) * 365",
       "legendFormat": "{{vault}}",
       "panelId": 6
      }
     ]
    }
   ]
  },
  {
   "title": "TVL - Graphs Detailed",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 },
   "collapsed": true,
   "panels": [
    {
     "title": "Total Assets - In Deposit Token",
     "type": "graph",
     "description": "Amount of the deposit token in the vault. This includes funds in all strategies + idle funds yet to be deployed.",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 12 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "yearn{network=\"ETH\", param=\"strategy balance\"}",
       "legendFormat": "{{vault}}"
      }
     ]
    },
    {
     "title": "Total Assets ($)",
     "type": "graph",
     "description": "Amount of the deposit asset in USD terms in the vault. This includes funds in all strategies + idle funds yet to be deployed.",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 12 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "yearn{network=\"ETH\", param=\"tvl\"} ",
       "legendFormat": "{{vault}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Number of Strategies",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 },
   "collapsed": true,
   "panels": [
    {
     "title": "Count of yVaults by TVL",
     "type": "bargauge",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 13 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "count(yearn{network=\"ETH\", param=\"tvl\"} > 10000000)",
       "legendFormat": "# v1 yVaults > $10m"
      },
      {
       "expr": "count(yearn{network=\"ETH\", param=\"tvl\"} > 1000000)",
       "legendFormat": "# v1 yVaults > $1m"
      },
      {
       "expr": "count(yearn{network=\"ETH\", param=\"tvl\"} > 100000)",
       "legendFormat": "# v1 yVaults > $100k "
      },
      {
       "expr": "count(yearn{network=\"ETH\", param=\"tvl\"} > 10000)",
       "legendFormat": "# v1 yVaults > $10k"
      },
      {
       "expr": "count(yearn{network=\"ETH\", param=\"tvl\"} > 100)",
       "legendFormat": "# v1 yVaults > $100"
      },
      {
       "expr": "count(yearn{network=\"ETH\", param=\"tvl\"} > 0)",
       "legendFormat": "# v1 yVaults > $0"
      }
     ]
    }
   ]
  }
 ]
}