{
 "title": "VE Vaults",
 "tags": [
  "yVault",
  "Experimental"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "panels": [
  {
   "title": "Total Value Locked",
   "type": "stat",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(yearn_vault{param=\"tvl\", experimental=\"true\"})",
     "legendFormat": "vE AUM"
    }
   ]
  },
  {
   "title": "Daily Delta",
   "type": "stat",
   "description": "Daily change in TVL in Experimental vaults.",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(delta(yearn_vault{param=\"tvl\", experimental=\"true\"}[1d]))",
     "legendFormat": "v2 AUM"
    }
   ]
  },
  {
   "title": "Weekly Delta",
   "type": "stat",
   "description": "Weekly change in TVL in Yearn's yVault products. This sum does not include experimental vaults.  ",
   "gridPos": { "h": 4, "w": 6, "x": 9, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(delta(yearn_vault{param=\"tvl\", experimental=\"true\"}[1w]))",
     "legendFormat": "v2 AUM"
    }
   ]
  },
  {
   "title": "Monthly Delta",
   "type": "stat",
   "description": "Monthly change in TVL in Yearn's yVault products. This sum does not include experimental vaults.  ",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(delta(yearn_vault{param=\"tvl\", experimental=\"true\"}[4w]))",
     "legendFormat": "v2 AUM"
    }
   ]
  },
  {
   "title": "TVL - Graphs",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "collapsed": true,
   "panels": [
    {
     "title": "Total Value Locked",
     "type": "graph",
     "description": "This show Total Value Locked in v2 Vaults. If you see a quick sharp dip just ignore it, that isn't someone withdrawing and depositing quickly but a problem with the exporter at that time. ",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 10 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(yearn_vault{param=\"tvl\", experimental=\"true\"})",
       "legendFormat": "v2 AUM"
      },
      {
       "expr": "sum(delta(yearn_vault{param=\"tvl\",experimental=\"true\"}[1d]))",
       "legendFormat": "v2 net inflow/outflow"
      }
     ]
    },
    {
     "title": "Daily Change",
     "type": "graph",
     "description": "Show the Daily change in v2 yVault's Assets Under Management. \n",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 19 },
     "yaxes": [
      { "format": "short", "label": "Change in Vault TVL" }
     ],
     "targets": [
      {
       "expr": "delta(yearn_vault{param=\"tvl\",experimental=\"true\"}[1d]) != 0",
       "legendFormat": "{{vault}}"
      },
      {
       "expr": "sum(delta(yearn_vault{param=\"tvl\",experimental=\"true\"}[1d]))",
       "legendFormat": "net inflow/outflow"
      }
     ]
    }
   ]
  },
  {
   "title": "Share Price - Graphs",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "collapsed": true,
   "panels": [
    {
     "title": "Price Per Share - Rate of Increase",
     "type": "graph",
     "description": "Rate of increase of Vault Share price. If this goes up the vaults are selling their farmed asset for more vault tokens! This helps normalize and show harvests compared to other vaults. The larger the spikes the more assets sold on that harvest call. The table shows the max value harvested for the timeframe selected. Note share price can dip when harvest is called as fees are collected and the harvest is paid out to vault holders over 6 hours to prevent sandwich attacks. This is a new feature of vault version 0.3.2",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "delta(yearn_vault{param=\"pricePerShare\", experimental=\"true\"}[5m])",
       "legendFormat": "{{vault}}",
       "panelId": 6
      }
     ]
    },
    {
     "title": "Share Price",
     "type": "graph",
     "description": "The current price of the vault's lp token, should increase steadily as vault's farmed assets are sold.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "yearn_vault{param=\"pricePerShare\", experimental=\"true\"}",
       "legendFormat": "{{vault}}",
       "panelId": 6
      }
     ]
    },
    {
     "title": "Price Per Share - 1d Annualized",
     "type": "graph",
     "description": "The current share price of the v2 yVault's token. This should increase steadily as yield is compounded into the vault.",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 19 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "delta(yearn_vault{param=\"pricePerShare\", experimental=\"true\"}[1d]) * 365",
       "legendFormat": "{{vault}}",
       "panelId": 6
      }
     ]
    }
   ]
  },
  {
   "title": "TVL - Graphs Detailed",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 },
   "collapsed": true,
   "panels": [
    {
     "title": "Total Assets - In Deposit Token",
     "type": "graph",
     "description": "Amount of the deposit token in the vault. This includes funds in all strategies + idle funds yet to be deployed.",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 12 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "yearn_vault{param=\"totalAssets\", experimental=\"true\"}",
       "legendFormat": "{{vault}}"
      }
     ]
    },
    {
     "title": "Total Assets ($)",
     "type": "graph",
     "description": "Amount of the deposit asset in USD terms in the vault. This includes funds in all strategies + idle funds yet to be deployed.",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 12 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "yearn_vault{param=\"tvl\", experimental=\"true\"} ",
       "legendFormat": "{{vault}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Last Report aka Harvest",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 },
   "collapsed": true,
   "panels": [
    {
     "title": "Time Since Last Report - Log Base (2) view",
     "type": "graph",
     "description": "This is the time since harvest was called on any strategy in the yVault. This does not mean the Share Price has increased, but that a harvest has occurred and farmed tokens might have been converted into the deposit token and compounded back into the vault.",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 13 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "time() - yearn_vault{param=\"lastReport\", experimental=\"true\", vault!~\"yvUSDC 0.2.2|yvDAI 0.2.2|yvWBTC 0.3.1|yvHEGIC 0.3.0\"}",
       "legendFormat": "{{vault}}"
      }
     ]
    },
    {
     "title": "Time Since Last Report - Linear View",
     "type": "graph",
     "description": "This is the time since harvest was called on any strategy in the yVault. This does not mean the Share Price has increased, but that a harvest has occurred and farmed tokens might have been converted into the deposit token and compounded back into the vault.",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 24 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "time() - yearn_vault{param=\"lastReport\", experimental=\"true\", vault!~\"yvUSDC 0.2.2|yvDAI 0.2.2|yvWBTC 0.3.1|yvHEGIC 0.3.0\"}",
       "legendFormat": "{{vault}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Allocation",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 },
   "collapsed": true,
   "panels": [
    {
     "title": "Percent of Funds Allocated to Strategies",
     "type": "graph",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 14 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "(avg by (vault) (yearn_vault{param=\"totalDebt\", experimental=\"true\", vault!~\"yvUSDC 0.2.2|yvDAI 0.2.2|yvWBTC 0.3.1|yvHEGIC 0.3.0\"}) / avg by (vault) (yearn_vault{param=\"totalAssets\", experimental=\"true\", vault!~\"yvUSDC 0.2.2|yvDAI 0.2.2|yvWBTC 0.3.1|yvHEGIC 0.3.0\"}) )",
       "legendFormat": "{{vault}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Number of Strategies",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 },
   "collapsed": true,
   "panels": [
    {
     "title": "Number of Strategies",
     "type": "graph",
     "description": "isActive is strategies in the vault that have this function set to true. Assets Deployed > 0, sums the count of strategies that have more than 0.1 of capital deployed. Unallocated simply minus the two numbers. Unallocated, could be strategies being depreciated or new strategies being added to the vault. ",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 15 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(yearn_strategy{param=\"isActive\", experimental=\"true\"})",
       "legendFormat": "isActive"
      },
      {
       "expr": "count(yearn_strategy{param=\"totalDebt\", experimental=\"true\"} > 0.1)",
       "legendFormat": "Assets Deployed > 0"
      },
      {
       "expr": "sum(yearn_strategy{param=\"isActive\", experimental=\"true\"}) - count(yearn_strategy{param=\"totalDebt\", experimental=\"true\"} > 0.1)",
       "legendFormat": "Unallocated Strategies"
      }
     ]
    }
   ]
  },
  {
   "title": "Activation",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 },
   "collapsed": true,
   "panels": [
    {
     "title": "Start of the Vault in weeks",
     "type": "piechart",
     "description": "Time since the vault was created in weeks.",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "time() - sort_desc((yearn_vault{param=\"activation\", experimental=\"true\", vault!~\"yvUSDC 0.2.2|yvDAI 0.2.2|yvWBTC 0.3.1|yvHEGIC 0.3.0\"}))",
       "legendFormat": "{{vault}}"
      }
     ]
    }
   ]
  }
 ]
}