{
 "title": "veYFI",
 "tags": [ "veYFI" ],
 "time": { "from": "now-7d", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Locked YFI",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "veyfi{network=\"ETH\", param=\"supply\"} / 10^18",
     "legendFormat": "veYFI"
    }
   ]
  },
  {
   "title": "YFI - Circulating Supply",
   "type": "stat",
   "description": "CS from coingecko - locked YFI",
   "gridPos": { "h": 5, "w": 6, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "31231 - veyfi{network=\"ETH\", param=\"supply\"} / 10^18",
     "legendFormat": "veYFI"
    }
   ]
  },
  {
   "title": "veYFI",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 19, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "veyfi{network=\"ETH\", param=\"totalSupply\"} / 10^18",
     "legendFormat": "veYFI"
    }
   ]
  },
  {
   "title": "Locked YFI in $",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(veyfi{network=\"ETH\", param=\"supply\"} / 10^18) * yearn_vault{vault=\"yvYFI 0.4.3\", param=\"token price\", network=\"ETH\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "YFI - Market Capitalization",
   "type": "stat",
   "description": "Circulating Supply of YFI * YFI Price",
   "gridPos": { "h": 3, "w": 6, "x": 9, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(31231 - veyfi{network=\"ETH\", param=\"supply\"} / 10^18) * yearn_vault{vault=\"yvYFI 0.4.3\", param=\"token price\", network=\"ETH\"}",
     "legendFormat": "veYFI"
    }
   ]
  },
  {
   "title": "Locked veYFI in $",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 19, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(veyfi{network=\"ETH\", param=\"totalSupply\"} / 10^18) * yearn_vault{vault=\"yvYFI 0.4.3\", param=\"token price\", network=\"ETH\"}",
     "legendFormat": "veYFI"
    }
   ]
  },
  {
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "veyfi{network=\"ETH\", param=\"totalSupply\"} / 1000000000000000000",
     "legendFormat": "Locked veYFI"
    },
    {
     "expr": "veyfi{network=\"ETH\", param=\"supply\"} / 1000000000000000000",
     "legendFormat": "Locked YFI"
    }
   ]
  },
  {
   "title": "Locked YFI",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 8, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "veyfi{network=\"ETH\", param=\"supply\"} / 10^18",
     "legendFormat": "Locked YFI"
    }
   ]
  },
  {
   "title": "Circulating Supply",
   "type": "timeseries",
   "description": "CS from coingecko - locked YFI",
   "gridPos": { "h": 12, "w": 9, "x": 8, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "31231 - veyfi{network=\"ETH\", param=\"supply\"} / 10^18",
     "legendFormat": "Circulating Supply"
    }
   ]
  },
  {
   "title": "veYFI",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 7, "x": 17, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "veyfi{network=\"ETH\", param=\"totalSupply\"} / 10^18",
     "legendFormat": "veYFI"
    }
   ]
  }
 ]
}