{
 "title": "Who uses Yearn?",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "Lifetime Wallets",
   "type": "stat",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "aggregate{param=\"total wallets\"}",
     "legendFormat": "Total Wallets"
    },
    {
     "expr": "yearn_vault{param=\"total wallets\", vault=\"\"}",
     "legendFormat": "V2"
    },
    {
     "expr": "yearn{param=\"total wallets\", vault = \"\"}",
     "legendFormat": "V1"
    }
   ]
  },
  {
   "title": "Active Wallets",
   "type": "stat",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "aggregate{param=\"active wallets\"}",
     "legendFormat": "Total Active Wallets"
    },
    {
     "expr": "yearn_vault{param=\"active wallets\", vault=\"\"}",
     "legendFormat": "V2"
    },
    {
     "expr": "yearn{param=\"active wallets\", vault=\"\"}",
     "legendFormat": "V1"
    }
   ]
  },
  {
   "title": "Wallets with balance > 5k",
   "type": "stat",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "aggregate{param=\"wallets > $5k\"}",
     "legendFormat": "yearn"
    },
    {
     "expr": "yearn_vault{param=\"wallets > $5k\",vault=\"\"}",
     "legendFormat": "v2"
    },
    {
     "expr": "yearn{param=\"wallets > $5k\",vault=\"\"}",
     "legendFormat": "v1"
    }
   ]
  },
  {
   "title": "Wallets with balance > 50k",
   "type": "stat",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "aggregate{param=\"wallets > $50k\"}",
     "legendFormat": "yearn"
    },
    {
     "expr": "yearn_vault{param=\"wallets > $50k\",vault=\"\"}",
     "legendFormat": "v2"
    },
    {
     "expr": "yearn{param=\"wallets > $50k\",vault=\"\"}",
     "legendFormat": "v1"
    }
   ]
  },
  {
   "title": "AUM from users with balance",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "yaxes": [
    { "format": "currencyUSD" }
   ],
   "targets": [
    {
     "expr": "sum(aggregate{param=\"balance usd\"} < 50000)",
     "legendFormat": "< 50k"
    },
    {
     "expr": "sum(aggregate{param=\"balance usd\"} >= 50000 < 500000)",
     "legendFormat": "50k - 500k"
    },
    {
     "expr": "sum(aggregate{param=\"balance usd\"} >= 500000 < 5000000)",
     "legendFormat": "500k - 5m "
    },
    {
     "expr": "sum(aggregate{param=\"balance usd\"} >= 5000000)",
     "legendFormat": "> 5m"
    }
   ]
  },
  {
   "title": "AUM from users with balance (%)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "yaxes": [
    { "format": "currencyUSD" }
   ],
   "targets": [
    {
     "expr": "sum(aggregate{param=\"balance usd\"} < 50000)",
     "legendFormat": "< 50k"
    },
    {
     "expr": "sum(aggregate{param=\"balance usd\"} >= 50000 < 500000)",
     "legendFormat": "50k - 500k"
    },
    {
     "expr": "sum(aggregate{param=\"balance usd\"} >= 500000 < 5000000)",
     "legendFormat": "500k - 5m "
    },
    {
     "expr": "sum(aggregate{param=\"balance usd\"} >= 5000000)",
     "legendFormat": "> 5m"
    }
   ]
  },
  {
   "title": "Total Wallets per v2 vault",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "yearn_vault{param=\"total wallets\", experimental=\"false\"} ",
     "legendFormat": "{{vault}}"
    }
   ]
  },
  {
   "title": "Active Wallets per v2 vault",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "yearn_vault{param=\"active wallets\", experimental=\"false\"}",
     "legendFormat": "{{vault}}"
    }
   ]
  },
  {
   "title": "Whale Tracker",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "aggregate{param=\"balance usd\"} > 10000000",
     "legendFormat": "{{wallet}}"
    }
   ]
  }
 ]
}