{
 "title": "yETH LST",
 "time": { "from": "now-90d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "lst",
    "label": "LST",
    "query": {
     "query": "yeth{product!=\"st-yETH\"}"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "$lst virtual balance",
   "type": "stat",
   "description": "Amount of ETH in the st-yETH amm for $lst.",
   "gridPos": { "h": 3, "w": 4.8, "x": 0, "y": 0 },
   "repeat": "lst",
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "yeth{param=\"virtual_balance\", product=\"$lst\"}",
     "legendFormat": "{{product}}"
    }
   ]
  },
  {
   "title": "LST composition percentage",
   "type": "stat",
   "gridPos": { "h": 24, "w": 3, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sort_desc(yeth{product!=\"st-yETH\", param=\"virtual_balance\"} / sum(yeth{product!=\"st-yETH\", param=\"virtual_balance\"}))",
     "legendFormat": "{{product}}"
    }
   ]
  },
  {
   "title": "LST composition percentage",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 15, "x": 3, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sort_desc(yeth{param=\"virtual_balance\"})",
     "legendFormat": "{{product}}"
    }
   ]
  },
  {
   "title": "LST composition percentage",
   "type": "piechart",
   "gridPos": { "h": 12, "w": 6, "x": 18, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "yeth{product!=\"st-yETH\", param=\"virtual_balance\"}",
     "legendFormat": "{{product}}"
    }
   ]
  },
  {
   "title": "LST composition in ETH",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 21, "x": 3, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "yeth{product=~\"$lst\", param=\"virtual_balance\"} * on(product) yeth{product=~\"$lst\", param=\"rate\"} ",
     "legendFormat": "{{product}}"
    }
   ]
  },
  {
   "title": "Virtual balance vs rate in the st-yETH AMM pool",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "yeth{product=~\"$lst\",param=\"rate\"}",
     "legendFormat": "rate: {{product}}"
    },
    {
     "expr": "yeth{product=~\"$lst\",param=\"virtual_balance\"}",
     "legendFormat": "virtual_balance: {{product}}"
    }
   ]
  },
  {
   "title": "Diff target-weight",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 18, "x": 0, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "yeth{product=~\"$lst\", param=\"target\"} - on(product) yeth{product=~\"$lst\", param=\"weight\"}",
     "legendFormat": "{{product}}"
    }
   ]
  },
  {
   "title": "LST composition target",
   "type": "stat",
   "gridPos": { "h": 24, "w": 3, "x": 18, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sort_desc(yeth{product=~\"$lst\", param=\"target\"})",
     "legendFormat": "{{product}}"
    }
   ]
  },
  {
   "title": "LST composition weight",
   "type": "stat",
   "gridPos": { "h": 24, "w": 3, "x": 21, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sort_desc(yeth{product=~\"$lst\", param=\"weight\"})",
     "legendFormat": "{{product}}"
    }
   ]
  },
  {
   "title": "Target vs weight",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 18, "x": 0, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "yeth{product=~\"$lst\", param=\"target\"}",
     "legendFormat": "{{param}}: {{product}}"
    },
    {
     "expr": "yeth{product=~\"$lst\", param=\"weight\"}",
     "legendFormat": "{{param}}: {{product}}"
    }
   ]
  },
  {
   "title": "Summed swap volume",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 62 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "expr": "sum(yeth{param=\"volume_in_usd\",product=~\"$lst\"})",
     "legendFormat": "Sum Daily swap volume incoming"
    },
    {
     "expr": "sum(yeth{param=\"volume_out_usd\",product=~\"$lst\"})",
     "legendFormat": "sum daily swap volume outgoing"
    }
   ]
  },
  {
   "title": "Daily swap volume incoming ETH",
   "type": "barchart",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 72 },
   "fieldConfig": { "defaults": { "unit": "ETH" } },
   "targets": [
    {
     "expr": "yeth{param=\"volume_in_eth\",product=~\"$lst\"}",
     "legendFormat": "{{product}}"
    }
   ]
  },
  {
   "title": "Daily swap volume outgoing ETH",
   "type": "barchart",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 72 },
   "fieldConfig": { "defaults": { "unit": "ETH" } },
   "targets": [
    {
     "expr": "yeth{param=\"volume_out_eth\",product=~\"$lst\"}",
     "legendFormat": "{{product}}"
    }
   ]
  },
  {
   "title": "Daily swap volume incoming USD",
   "type": "barchart",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 83 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "expr": "yeth{param=\"volume_in_usd\",product=~\"$lst\"}",
     "legendFormat": "{{product}}"
    }
   ]
  },
  {
   "title": "Daily swap volume outgoing USD",
   "type": "barchart",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 83 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "expr": "yeth{param=\"volume_out_usd\",product=~\"$lst\"}",
     "legendFormat": "{{product}}"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 94 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "yeth{param=\"net_apy\", product=\"st-yETH\"}",
     "legendFormat": "{{product}}"
    }
   ]
  },
  {
   "type": "stat",
   "description": "APY of $lst",
   "gridPos": { "h": 6, "w": 4.8, "x": 0, "y": 98 },
   "repeat": "lst",
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "yeth{param=\"gross_apr\", product=\"$lst\",  product!=\"st-yETH\"}",
     "legendFormat": "{{product}}"
    }
   ]
  },
  {
   "title": "LST APY composition",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 104 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "yeth{product!=\"st-yETH\", product=~\"$lst\",param=\"net_apy\"}",
     "legendFormat": "{{product}}"
    }
   ]
  }
 ]
}