{
 "title": "yETH",
 "time": { "from": "now-90d", "to": "now" },
 "panels": [
  {
   "title": "st-yETH APY",
   "type": "stat",
   "description": "Weekly APY updated once per day, takes the now time and updates it against the lp prices a week ago.",
   "gridPos": { "h": 4, "w": 5, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "yeth{product=\"st-yETH\",param=\"net_apy\"}"
    }
   ]
  },
  {
   "title": "Amount of st-yETH",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 14, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "yeth{product=\"st-yETH\", param=\"totalSupply\"}"
    }
   ]
  },
  {
   "title": "% staked yETH",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 19, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "yeth{product=\"st-yETH\", param=\"boost\"}"
    }
   ]
  },
  {
   "title": "st-yETH APY vs % Staked in st-yETH",
   "type": "timeseries",
   "description": "Boost is how much yETH is staked into st-yETH custom amm. If more yETH goes to lp in the curve yETH-eth pool then less % is staked in st-yETH causing the boost to increase. \nIf pool_supply < total_assets boost > 100%",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "yeth{product=\"st-yETH\",param=\"net_apy\"}",
     "legendFormat": "{{param}}"
    },
    {
     "expr": "yeth{product=\"st-yETH\", param=\"boost\"}",
     "legendFormat": "% yETH staked in st-yETH"
    }
   ]
  },
  {
   "title": "Total Supply of st-yETH in the AMM pool",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "yeth{product=\"st-yETH\",param=\"totalSupply\"}",
     "legendFormat": "{{product}}"
    }
   ]
  }
 ]
}