{
 "title": "yMonitor exporter",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "network", "query": { "query": "ymonitor_node_block_number" } },
   { "name": "type", "query": "api, apy, website" }
  ]
 },
 "panels": [
  { "title": "APY data", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "APY datetime UTC",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsIso" } },
   "targets": [
    {
     "expr": "ymonitor_node_apy_timestamp*1000",
     "legendFormat": "{{host}} - {{network}}"
    }
   ]
  },
  {
   "title": "APY timestamp (seconds)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 1 },
   "targets": [
    { "expr": "ymonitor_node_apy_timestamp", "legendFormat": "{{host}} - {{network}}" }
   ]
  },
  { "title": "Network data", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "failed checks (!= 200)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 11 },
   "targets": [
    {
     "expr": "increase(ymonitor_node_request_counter{code!=\"200\",type!=\"node\", network=\"$network\"}[$__interval])",
     "legendFormat": "{{host}}"
    }
   ]
  }
 ]
}