{
 "title": "Total Value Locked in Vaults",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "TVL",
   "type": "stat",
   "description": "Accurate TVL with duplicates subtracted. The ones below are simple sums",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(yearn{param=\"tvl\"}) + sum(yearn_vault{param=\"tvl\"}) + sum(iearn{param=\"tvl\"}) + sum(ironbank{param=\"tvl\"}) - sum(yearn{param=\"tvl\",vault=~\"curve.fi/(y|busd)\"})"
    }
   ]
  },
  {
   "title": "V1 TVL",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(yearn{param=\"tvl\"})",
     "legendFormat": "{{vault}}"
    }
   ]
  },
  {
   "title": "V2 TVL",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 5, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(yearn_vault{param=\"tvl\"})",
     "legendFormat": "{{vault}}"
    }
   ]
  },
  {
   "title": "Earn TVL",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 10, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(iearn{param=\"tvl\"})",
     "legendFormat": "{{vault}}"
    }
   ]
  },
  {
   "title": "Ironbank TVL",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 15, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(ironbank{param=\"tvl\"})",
     "legendFormat": "{{vault}}"
    }
   ]
  },
  {
   "title": "VE TVL",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(yearn_experimental{param=\"tvl\"})",
     "legendFormat": "{{vault}}"
    }
   ]
  },
  {
   "title": "v1 TVL",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "yearn{param=\"tvl\"}",
     "legendFormat": "{{vault}}"
    }
   ]
  },
  {
   "title": "v1 TVL",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(yearn{param=\"tvl\"})",
     "legendFormat": "{{vault}}"
    }
   ]
  },
  {
   "title": "v2 TVL",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "yearn_vault{param=\"tvl\"}",
     "legendFormat": "{{vault}}"
    }
   ]
  },
  {
   "title": "v2 TVL",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(yearn_vault{param=\"tvl\"})",
     "legendFormat": "{{vault}}"
    }
   ]
  },
  {
   "title": "vE TVL",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "yearn_experimental{param=\"tvl\"}",
     "legendFormat": "{{vault}}"
    }
   ]
  },
  {
   "title": "vE TVL",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(yearn_experimental{param=\"tvl\"})",
     "legendFormat": "{{vault}}"
    }
   ]
  },
  {
   "title": "Earn TVL",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 43 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "iearn{param=\"tvl\"}",
     "legendFormat": "{{vault}}"
    }
   ]
  },
  {
   "title": "Earn TVL",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 43 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(iearn{param=\"tvl\"})",
     "legendFormat": "{{vault}}"
    }
   ]
  },
  {
   "title": "Ironbank TVL",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 54 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "ironbank{param=\"tvl\"}",
     "legendFormat": "{{vault}}"
    }
   ]
  },
  {
   "title": "Ironbank TVL",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 54 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(ironbank{param=\"tvl\"})",
     "legendFormat": "{{vault}}"
    }
   ]
  }
 ]
}