{
 "title": "Are the Exporters Working?",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Prometheus",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{job=\"prometheus\"}",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "V1 Vaults",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 3, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{job=\"yearn-v1\"}",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "V2 Vaults",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 9, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{job=\"yearn-v2\"}",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "VE Vaults",
   "type": "stat",
   "description": "Experimental Vaults",
   "gridPos": { "h": 6, "w": 3, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{job=\"yearn-experimental\"}",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Earn",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 18, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{job=\"iearn\"}",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Ironbank",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 21, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{job=\"ironbank\"}",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Up?",
   "type": "graph",
   "gridPos": { "h": 16, "w": 24, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "up{job=\"yearn-v1\"}",
     "legendFormat": "{{job}}"
    },
    {
     "expr": "up{job=\"yearn-experimental\"}",
     "legendFormat": "{{job}}"
    },
    {
     "expr": "up{job=\"yearn-v2\"}",
     "legendFormat": "{{job}}"
    },
    {
     "expr": "up{job=\"prometheus\"}",
     "legendFormat": "{{job}}"
    },
    {
     "expr": "up{job=\"iearn\"}",
     "legendFormat": "{{job}}"
    },
    {
     "expr": "up{job=\"ironbank\"}",
     "legendFormat": "{{job}}"
    }
   ]
  }
 ]
}