{
 "title": "Are the Exporters Working?",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Prometheus",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 1, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{job=\"prometheus\"}",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "V1 Vaults",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 7, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{job=\"yearn-v1\"}",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "V2 Vaults",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 13, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{job=\"yearn-v2\"}",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "VE Vaults",
   "type": "stat",
   "description": "Experimental Vaults",
   "gridPos": { "h": 7, "w": 4, "x": 19, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{job=\"yearn-experimental\"}",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Up?",
   "type": "graph",
   "gridPos": { "h": 16, "w": 24, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "up{job=\"yearn-v1\"}",
     "legendFormat": "{{job}}"
    },
    {
     "expr": "up{job=\"yearn-experimental\"}",
     "legendFormat": "{{job}}"
    },
    {
     "expr": "up{job=\"yearn-v2\"}",
     "legendFormat": "{{job}}"
    },
    {
     "expr": "up{job=\"prometheus\"}",
     "legendFormat": "{{job}}"
    }
   ]
  }
 ]
}