{
 "title": "V1 Vaults2",
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Share Price - Rate of Increase",
   "type": "graph",
   "description": "Rate of increase of Vault Share price. If this goes up the vaults are selling their farmed asset for more vault tokens! This helps normalize and show harvests compared to other vaults. The larger the spikes the more assets sold on that harvest call. The table shows the max value harvested for the timeframe selected.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "rate(yearn{param=\"share price\", vault!=\"GUSD\"}[2m])",
     "legendFormat": "{{vault}}"
    }
   ]
  },
  {
   "title": "Share Price",
   "type": "graph",
   "description": "The current price of the vault's lp token, should increase steadily as vault's farmed assets are sold.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "Share Price" }
   ],
   "targets": [
    {
     "expr": "yearn{param=\"share price\", vault!=\"GUSD\"}",
     "legendFormat": "{{vault}}"
    }
   ]
  },
  {
   "title": "Virtual Price - Rate of Increase",
   "type": "graph",
   "description": "Rate of Increase of the underlying curve pools' shares. If this goes up the curvepools are accruing swap fees. This helps normalize and show pool swap fees gained across curve pools. The larger the spikes the more swap fee gained for the pool. The table shows the max swap fee for the timeframe selected.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "rate(yearn{param=\"virtual price\"}[2m])",
     "legendFormat": "{{vault}}"
    }
   ]
  },
  {
   "title": "Virtual Price",
   "type": "graph",
   "description": "Price of the underlying curvepools",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short", "label": "Virtual Price" }
   ],
   "targets": [
    {
     "expr": "yearn{param=\"virtual price\"}",
     "legendFormat": "{{vault}}"
    }
   ]
  },
  {
   "title": "Vault Balances",
   "type": "graph",
   "description": "Yearn Vault Balances",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short", "label": "Vault Shares " }
   ],
   "targets": [
    {
     "expr": "yearn{param=\"vault balance\"}",
     "legendFormat": "{{vault}}"
    }
   ]
  },
  {
   "title": "Boosties",
   "type": "graph",
   "description": "Boosts for the Yearn Vaults. 100% is no boost, and 250% is max 2.5x boost. If a vault show 100% usually that means it has no funds in the vault.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "percentunit", "label": "Boosties" }
   ],
   "targets": [
    {
     "expr": "yearn{param=\"boost\"}",
     "legendFormat": "{{vault}}"
    }
   ]
  },
  {
   "title": "Vault Assets Free",
   "type": "graph",
   "description": "Vaults which have liquidity that is free to withdrawal. If not show on the side you will have a fee",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "yaxes": [
    { "format": "currencyUSD" }
   ],
   "targets": [
    {
     "expr": "sort(yearn{param=\"available\"})",
     "legendFormat": "{{vault}}"
    }
   ]
  },
  {
   "title": "% of Vault Funds Deployed in Strategy",
   "type": "bargauge",
   "description": "This shows the amount of funds deployed to the vaults' strategy. If it shows 0 its an error so ignore it.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sort(yearn{param=\"strategy buffer\", vault!=\"DAI\", vault!=\"TUSD\",vault!=\"USDC\",vault!=\"USDT\"})",
     "legendFormat": "{{vault}}"
    }
   ]
  },
  {
   "title": "V1 - Total Assets Under Management",
   "type": "stat",
   "description": "Yearn Vault Total",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 32 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(yearn{param=\"tvl\"})",
     "legendFormat": "{{vault}}"
    }
   ]
  },
  {
   "title": "V1 - Total Assets Under Management",
   "type": "graph",
   "description": "Yearn Vault Total",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 38 },
   "yaxes": [
    { "format": "short", "label": "Total $ Amount in v1 Vaults" }
   ],
   "targets": [
    {
     "expr": "sum(yearn{param=\"tvl\"})",
     "legendFormat": "V1 AUM"
    }
   ]
  },
  {
   "title": "CRV Price",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 44 },
   "yaxes": [
    { "format": "currencyUSD", "label": "Price" }
   ],
   "targets": [
    {
     "expr": "avg(yearn{param=\"crv price\", job=\"yearn-v1\"})",
     "legendFormat": "Crv Price"
    }
   ]
  }
 ]
}