{
 "title": "VE - Experimental Vaults",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "Price Per Share - Rate of Increase",
   "type": "graph",
   "description": "Rate of increase of Vault Share price. If this goes up the vaults are selling their farmed asset for more vault tokens! This helps normalize and show harvests compared to other vaults. The larger the spikes the more assets sold on that harvest call. The table shows the max value harvested for the timeframe selected.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(yearn_experimental{param=\"pricePerShare\"}[2m])",
     "legendFormat": "{{vault}}",
     "panelId": 6
    }
   ]
  },
  {
   "title": "Price Per Share",
   "type": "graph",
   "description": "The current price of the vault's lp token, should increase steadily as vault's farmed assets are sold.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "yearn_experimental{param=\"pricePerShare\"}",
     "legendFormat": "{{vault}}",
     "panelId": 6
    }
   ]
  },
  {
   "title": "Total Assets",
   "type": "graph",
   "description": "Total Amount of AUM in the vault in their native deposit token.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "yearn_experimental{param=\"totalAssets\"}",
     "legendFormat": "{{vault}}"
    }
   ]
  },
  {
   "title": "Total Value Locked",
   "type": "graph",
   "description": "Total amount of AUM in the vault in USD terms.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "yearn_experimental{param=\"tvl\"} ",
     "legendFormat": "{{vault}}"
    }
   ]
  },
  {
   "title": "Total Value Locked",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "short", "label": "Total Value locked in $" }
   ],
   "targets": [
    {
     "expr": "yearn_experimental{param=\"tvl\"} ",
     "legendFormat": "{{vault}}"
    }
   ]
  },
  {
   "title": "Deposit Limit",
   "type": "stat",
   "gridPos": { "h": 5, "w": 23, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "yearn_experimental{param=\"depositLimit\"}",
     "legendFormat": "{{vault}}"
    }
   ]
  },
  {
   "title": "Emergency Shutdown",
   "type": "stat",
   "description": "0 is no 1 is yes",
   "gridPos": { "h": 2, "w": 22, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "yearn_experimental{param=\"emergencyShutdown\"}",
     "legendFormat": "{{vault}}"
    }
   ]
  }
 ]
}