{
 "title": "Total Value Locked in Vaults",
 "time": { "from": "now-24h", "to": "now" },
 "panels": [
  {
   "title": "TVL",
   "type": "stat",
   "description": "For now, this is a basic sum of all the vaults and doesn't subtract vaults delegated to other vaults.",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "yearn_vault{param=\"tvl\"}",
     "legendFormat": "{{vault}}"
    },
    {
     "expr": "yearn{param=\"tvl\"}",
     "legendFormat": "{{vault}}"
    },
    {
     "expr": "yearn_experimental{param=\"tvl\"}",
     "legendFormat": "{{vault}}"
    }
   ]
  },
  {
   "title": "V1 TVL",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "yearn{param=\"tvl\"}",
     "legendFormat": "{{vault}}"
    }
   ]
  },
  {
   "title": "V2 TVL",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "yearn_vault{param=\"tvl\"}",
     "legendFormat": "{{vault}}"
    }
   ]
  },
  {
   "title": "VE TVL",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "yearn_experimental{param=\"tvl\"}",
     "legendFormat": "{{vault}}"
    }
   ]
  },
  {
   "title": "v1 TVL",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "yearn{param=\"tvl\"}",
     "legendFormat": "{{vault}}"
    }
   ]
  },
  {
   "title": "v1 TVL",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "yearn{param=\"tvl\"}",
     "legendFormat": "{{vault}}"
    }
   ]
  },
  {
   "title": "v2 TVL",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "yearn_vault{param=\"tvl\"}",
     "legendFormat": "{{vault}}"
    }
   ]
  },
  {
   "title": "v2 TVL",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "yearn_vault{param=\"tvl\"}",
     "legendFormat": "{{vault}}"
    }
   ]
  },
  {
   "title": "vE TVL",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "yearn_experimental{param=\"tvl\"}",
     "legendFormat": "{{vault}}"
    }
   ]
  },
  {
   "title": "vE TVL",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "yearn_experimental{param=\"tvl\"}",
     "legendFormat": "{{vault}}"
    }
   ]
  }
 ]
}