# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import schema.schema_pb2 as schema__pb2


class HashBrownieStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetAbi = channel.unary_unary(
                '/HashBrownie/GetAbi',
                request_serializer=schema__pb2.GetAbiRequest.SerializeToString,
                response_deserializer=schema__pb2.Abi.FromString,
                )
        self.GetLogs = channel.unary_unary(
                '/HashBrownie/GetLogs',
                request_serializer=schema__pb2.GetLogsRequest.SerializeToString,
                response_deserializer=schema__pb2.Logs.FromString,
                )


class HashBrownieServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetAbi(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetLogs(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_HashBrownieServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetAbi': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAbi,
                    request_deserializer=schema__pb2.GetAbiRequest.FromString,
                    response_serializer=schema__pb2.Abi.SerializeToString,
            ),
            'GetLogs': grpc.unary_unary_rpc_method_handler(
                    servicer.GetLogs,
                    request_deserializer=schema__pb2.GetLogsRequest.FromString,
                    response_serializer=schema__pb2.Logs.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'HashBrownie', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class HashBrownie(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetAbi(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/HashBrownie/GetAbi',
            schema__pb2.GetAbiRequest.SerializeToString,
            schema__pb2.Abi.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetLogs(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/HashBrownie/GetLogs',
            schema__pb2.GetLogsRequest.SerializeToString,
            schema__pb2.Logs.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
