{
 "title": "Are the Exporters Working?",
 "tags": [ "Status" ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Prometheus",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{job=\"prometheus\"}",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Node Exporter",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{job=\"node\"}",
     "legendFormat": "Node Exporter"
    }
   ]
  },
  {
   "title": "Yearn",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{job=\"yearn\"}",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Nginx",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{job=\"nginx\"}",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Up?",
   "type": "graph",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "bool_yes_no" }
   ],
   "targets": [
    {
     "expr": "up{job=\"yearn\"}",
     "legendFormat": "{{job}}"
    },
    {
     "expr": "up{job=\"prometheus\"}",
     "legendFormat": "{{job}}"
    },
    {
     "expr": "up{job=\"node\"}",
     "legendFormat": "node exporter"
    },
    {
     "expr": "up{job=\"nginx\"}",
     "legendFormat": "{{job}}"
    }
   ]
  }
 ]
}