{
 "title": "Exporter Durations Copy",
 "tags": [ "Exporter" ],
 "time": { "from": "now-6M", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   { "name": "Direction", "label": "direction", "query": { "query": "export_duration{}" } },
   { "name": "networks", "label": "network", "query": { "query": "export_duration{}" } },
   { "name": "Pool_Size", "label": "pool_size", "query": { "query": "export_duration{}" } }
  ]
 },
 "panels": [
  {
   "title": "Exporter Duration",
   "type": "graph",
   "gridPos": { "h": 18, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "yaxes": [
    { "format": "s", "label": "Historical Exporter" }
   ],
   "targets": [
    {
     "expr": "export_duration{direction=\"mighty_exporter\"}",
     "legendFormat": "{{network}} - {{direction}} - {{pool_size}}"
    },
    {
     "expr": "export_duration{direction=\"partners\"}",
     "legendFormat": "{{network}} - {{direction}} - {{pool_size}}"
    }
   ]
  },
  {
   "title": "Last Duration",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Delta Exporter Duration",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "delta(export_duration{} ) ",
     "legendFormat": "{{direction}} - {{network}} - {{pool_size}}"
    }
   ]
  },
  {
   "title": "Last: Export Duration",
   "type": "stat",
   "gridPos": { "h": 43, "w": 24, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg_over_time(export_duration)",
     "legendFormat": "{{network}} - {{direction}} - {{pool_size}}"
    }
   ]
  },
  {
   "title": "Individual Stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 72 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Exporter Duration - Individual View",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 73 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "export_duration{direction=\"$Direction\", network=\"$networks\", pool_size=\"$Pool_Size\"}",
     "legendFormat": "{{direction}} - {{network}} - {{pool_size}}"
    }
   ]
  }
 ]
}