version: '3.7'

volumes:
  brownie: {}
  cache: {}

networks:
  yearn-exporter-ipfs:

services:
  yearn-exporter-ipfs:
    build: .
    command: ipfs
    environment:
      - WEB3_PROVIDER
      - ETHERSCAN_TOKEN
      - EXPLORER
      - IPFS_NODE_ADDRESS
      - IPFS_NODE_KEY
      - IPFS_NODE_SECRET
      - SENTRY_RELEASE
      - SENTRY_ENVIRONMENT=${SENTRY_ENVIRONMENT:-development}
      - SENTRY_DSN
    volumes:
      - brownie:/root/.brownie
      - cache:/app/yearn-exporter/cache
    restart: always
    networks:
      - yearn-exporter-ipfs
