version: '3.7'

volumes:
    solidity_compilers: {}
    vyper_compilers: {}
    brownie: {}
    cache: {}

networks:
  yearn-exporter-ipfs:

services:
  yearn-exporter-ipfs:
    build: .
    command: ipfs
    environment:
      - WEB3_PROVIDER
      - ETHERSCAN_TOKEN
      - EXPLORER
      - IPFS_NODE_ADDRESS
      - IPFS_NODE_KEY
      - IPFS_NODE_SECRET
      - ENV
      - SENTRY_DSN
    volumes:
      - solidity_compilers:/root/.solcx
      - vyper_compilers:/root/.vvm
      - brownie:/root/.brownie
      - cache:/app/yearn-exporter/cache
    restart: always
    networks:
      - yearn-exporter-ipfs
