name: 🐛 Debug apy-script PRODUCTION
on:
  workflow_dispatch:
    inputs:
      docker_image_tag:
        description: Docker image tag
        required: true
        default: latest
      network:
        description: Network
        required: true
        default: ethereum

jobs:
  deployment:
    runs-on: ubuntu-latest
    steps:
      - name: Debug APY on production
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.APY_PRODUCTION_HOST }}
          username: ${{ secrets.APY_PRODUCTION_USERNAME }}
          key: ${{ secrets.APY_PRODUCTION_KEY }}
          port: ${{ secrets.APY_PRODUCTION_PORT }}
          script: curl "https://raw.githubusercontent.com/yearn/yearn-exporter/master/debug_apy.sh" -o debug_apy.sh && chmod +x debug_apy.sh && ./debug_apy.sh "${{ github.event.inputs.docker_image_tag }}" "${{ github.event.inputs.network }}"
